-- =============================================================================
-- Registry-aligned template seed batch 2 of 10
-- Templates 51–100 of 500
-- Generated by ctrl_checks/scripts/generate-workflow-templates-sql.ts
-- Run 00_delete_all_templates.sql first if replacing the full catalog.
-- =============================================================================

BEGIN;

-- Template #51
INSERT INTO public.templates (name, description, category, nodes, edges, difficulty, estimated_setup_time, tags, is_active, is_featured, created_by)
VALUES (
  'E-commerce: Automate survey results',
  'Starter workflow: E-commerce: Automate survey results. Linear flow (manual_trigger → openai_gpt → ai_agent → log_output). Configure credentials and fields per node; extend in the canvas.',
  'Commerce & Retail',
  '[{"id":"n1","type":"custom","position":{"x":100,"y":200},"data":{"type":"manual_trigger","label":"Manual Trigger (1)"}},{"id":"n2","type":"custom","position":{"x":360,"y":200},"data":{"type":"openai_gpt","label":"Openai Gpt (2)"}},{"id":"n3","type":"custom","position":{"x":620,"y":200},"data":{"type":"ai_agent","label":"Ai Agent (3)"}},{"id":"n4","type":"custom","position":{"x":880,"y":200},"data":{"type":"log_output","label":"Log Output (4)"}}]'::jsonb,
  '[{"id":"e1","source":"n1","target":"n2","sourceHandle":"output","targetHandle":"input"},{"id":"e2","source":"n2","target":"n3","sourceHandle":"output","targetHandle":"input"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"output","targetHandle":"input"}]'::jsonb,
  'Advanced',
  5,
  ARRAY['Commerce & Retail', 'manual-trigger', 'openai-gpt', 'ai-agent', 'log-output'],
  true,
  false,
  COALESCE((SELECT user_id FROM public.user_roles WHERE role = 'admin' LIMIT 1), (SELECT id FROM auth.users ORDER BY created_at LIMIT 1))
);


-- Template #52
INSERT INTO public.templates (name, description, category, nodes, edges, difficulty, estimated_setup_time, tags, is_active, is_featured, created_by)
VALUES (
  'Healthcare: Deduplicate grant submissions',
  'Starter workflow: Healthcare: Deduplicate grant submissions. Linear flow (schedule → google_drive → filter → log_output). Configure credentials and fields per node; extend in the canvas.',
  'Healthcare',
  '[{"id":"n1","type":"custom","position":{"x":100,"y":200},"data":{"type":"schedule","label":"Schedule (1)"}},{"id":"n2","type":"custom","position":{"x":360,"y":200},"data":{"type":"google_drive","label":"Google Drive (2)"}},{"id":"n3","type":"custom","position":{"x":620,"y":200},"data":{"type":"filter","label":"Filter (3)"}},{"id":"n4","type":"custom","position":{"x":880,"y":200},"data":{"type":"log_output","label":"Log Output (4)"}}]'::jsonb,
  '[{"id":"e1","source":"n1","target":"n2","sourceHandle":"output","targetHandle":"input"},{"id":"e2","source":"n2","target":"n3","sourceHandle":"output","targetHandle":"input"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"output","targetHandle":"input"}]'::jsonb,
  'Beginner',
  6,
  ARRAY['Healthcare', 'schedule', 'google-drive', 'filter', 'log-output'],
  true,
  false,
  COALESCE((SELECT user_id FROM public.user_roles WHERE role = 'admin' LIMIT 1), (SELECT id FROM auth.users ORDER BY created_at LIMIT 1))
);


-- Template #53
INSERT INTO public.templates (name, description, category, nodes, edges, difficulty, estimated_setup_time, tags, is_active, is_featured, created_by)
VALUES (
  'Finance & Accounting: Parse CSV uploads',
  'Starter workflow: Finance & Accounting: Parse CSV uploads. Linear flow (webhook → twitter → google_calendar → log_output). Configure credentials and fields per node; extend in the canvas.',
  'Finance',
  '[{"id":"n1","type":"custom","position":{"x":100,"y":200},"data":{"type":"webhook","label":"Webhook (1)"}},{"id":"n2","type":"custom","position":{"x":360,"y":200},"data":{"type":"twitter","label":"Twitter (2)"}},{"id":"n3","type":"custom","position":{"x":620,"y":200},"data":{"type":"google_calendar","label":"Google Calendar (3)"}},{"id":"n4","type":"custom","position":{"x":880,"y":200},"data":{"type":"log_output","label":"Log Output (4)"}}]'::jsonb,
  '[{"id":"e1","source":"n1","target":"n2","sourceHandle":"output","targetHandle":"input"},{"id":"e2","source":"n2","target":"n3","sourceHandle":"output","targetHandle":"input"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"output","targetHandle":"input"}]'::jsonb,
  'Intermediate',
  7,
  ARRAY['Finance', 'webhook', 'twitter', 'google-calendar', 'log-output'],
  true,
  false,
  COALESCE((SELECT user_id FROM public.user_roles WHERE role = 'admin' LIMIT 1), (SELECT id FROM auth.users ORDER BY created_at LIMIT 1))
);


-- Template #54
INSERT INTO public.templates (name, description, category, nodes, edges, difficulty, estimated_setup_time, tags, is_active, is_featured, created_by)
VALUES (
  'HR & People: Monitor patient intake forms',
  'Starter workflow: HR & People: Monitor patient intake forms. Linear flow (form → function → clickup → log_output). Configure credentials and fields per node; extend in the canvas.',
  'HR',
  '[{"id":"n1","type":"custom","position":{"x":100,"y":200},"data":{"type":"form","label":"Form (1)"}},{"id":"n2","type":"custom","position":{"x":360,"y":200},"data":{"type":"function","label":"Function (2)"}},{"id":"n3","type":"custom","position":{"x":620,"y":200},"data":{"type":"clickup","label":"Clickup (3)"}},{"id":"n4","type":"custom","position":{"x":880,"y":200},"data":{"type":"log_output","label":"Log Output (4)"}}]'::jsonb,
  '[{"id":"e1","source":"n1","target":"n2","sourceHandle":"output","targetHandle":"input"},{"id":"e2","source":"n2","target":"n3","sourceHandle":"output","targetHandle":"input"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"output","targetHandle":"input"}]'::jsonb,
  'Advanced',
  8,
  ARRAY['HR', 'form', 'function', 'clickup', 'log-output'],
  true,
  false,
  COALESCE((SELECT user_id FROM public.user_roles WHERE role = 'admin' LIMIT 1), (SELECT id FROM auth.users ORDER BY created_at LIMIT 1))
);


-- Template #55
INSERT INTO public.templates (name, description, category, nodes, edges, difficulty, estimated_setup_time, tags, is_active, is_featured, created_by)
VALUES (
  'DevOps & SRE: Aggregate backup manifests',
  'Starter workflow: DevOps & SRE: Aggregate backup manifests. Linear flow (interval → slack_message → ai_service → log_output). Configure credentials and fields per node; extend in the canvas.',
  'Developer Tools',
  '[{"id":"n1","type":"custom","position":{"x":100,"y":200},"data":{"type":"interval","label":"Interval (1)"}},{"id":"n2","type":"custom","position":{"x":360,"y":200},"data":{"type":"slack_message","label":"Slack Message (2)"}},{"id":"n3","type":"custom","position":{"x":620,"y":200},"data":{"type":"ai_service","label":"Ai Service (3)"}},{"id":"n4","type":"custom","position":{"x":880,"y":200},"data":{"type":"log_output","label":"Log Output (4)"}}]'::jsonb,
  '[{"id":"e1","source":"n1","target":"n2","sourceHandle":"output","targetHandle":"input"},{"id":"e2","source":"n2","target":"n3","sourceHandle":"output","targetHandle":"input"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"output","targetHandle":"input"}]'::jsonb,
  'Beginner',
  9,
  ARRAY['Developer Tools', 'interval', 'slack-message', 'ai-service', 'log-output'],
  true,
  false,
  COALESCE((SELECT user_id FROM public.user_roles WHERE role = 'admin' LIMIT 1), (SELECT id FROM auth.users ORDER BY created_at LIMIT 1))
);


-- Template #56
INSERT INTO public.templates (name, description, category, nodes, edges, difficulty, estimated_setup_time, tags, is_active, is_featured, created_by)
VALUES (
  'Marketing: Validate experiment logs',
  'Starter workflow: Marketing: Validate experiment logs. Linear flow (manual_trigger → json_parser → csv → log_output). Configure credentials and fields per node; extend in the canvas.',
  'Marketing & Growth',
  '[{"id":"n1","type":"custom","position":{"x":100,"y":200},"data":{"type":"manual_trigger","label":"Manual Trigger (1)"}},{"id":"n2","type":"custom","position":{"x":360,"y":200},"data":{"type":"json_parser","label":"Json Parser (2)"}},{"id":"n3","type":"custom","position":{"x":620,"y":200},"data":{"type":"csv","label":"Csv (3)"}},{"id":"n4","type":"custom","position":{"x":880,"y":200},"data":{"type":"log_output","label":"Log Output (4)"}}]'::jsonb,
  '[{"id":"e1","source":"n1","target":"n2","sourceHandle":"output","targetHandle":"input"},{"id":"e2","source":"n2","target":"n3","sourceHandle":"output","targetHandle":"input"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"output","targetHandle":"input"}]'::jsonb,
  'Intermediate',
  10,
  ARRAY['Marketing & Growth', 'manual-trigger', 'json-parser', 'csv', 'log-output'],
  true,
  false,
  COALESCE((SELECT user_id FROM public.user_roles WHERE role = 'admin' LIMIT 1), (SELECT id FROM auth.users ORDER BY created_at LIMIT 1))
);


-- Template #57
INSERT INTO public.templates (name, description, category, nodes, edges, difficulty, estimated_setup_time, tags, is_active, is_featured, created_by)
VALUES (
  'Customer Support: Reconcile court filings',
  'Starter workflow: Customer Support: Reconcile court filings. Linear flow (schedule → airtable → google_gmail → log_output). Configure credentials and fields per node; extend in the canvas.',
  'Support',
  '[{"id":"n1","type":"custom","position":{"x":100,"y":200},"data":{"type":"schedule","label":"Schedule (1)"}},{"id":"n2","type":"custom","position":{"x":360,"y":200},"data":{"type":"airtable","label":"Airtable (2)"}},{"id":"n3","type":"custom","position":{"x":620,"y":200},"data":{"type":"google_gmail","label":"Google Gmail (3)"}},{"id":"n4","type":"custom","position":{"x":880,"y":200},"data":{"type":"log_output","label":"Log Output (4)"}}]'::jsonb,
  '[{"id":"e1","source":"n1","target":"n2","sourceHandle":"output","targetHandle":"input"},{"id":"e2","source":"n2","target":"n3","sourceHandle":"output","targetHandle":"input"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"output","targetHandle":"input"}]'::jsonb,
  'Advanced',
  11,
  ARRAY['Support', 'schedule', 'airtable', 'google-gmail', 'log-output'],
  true,
  false,
  COALESCE((SELECT user_id FROM public.user_roles WHERE role = 'admin' LIMIT 1), (SELECT id FROM auth.users ORDER BY created_at LIMIT 1))
);


-- Template #58
INSERT INTO public.templates (name, description, category, nodes, edges, difficulty, estimated_setup_time, tags, is_active, is_featured, created_by)
VALUES (
  'Education: Notify stakeholders about form responses',
  'Starter workflow: Education: Notify stakeholders about form responses. Linear flow (webhook → ai_agent → notion → log_output). Configure credentials and fields per node; extend in the canvas.',
  'Education',
  '[{"id":"n1","type":"custom","position":{"x":100,"y":200},"data":{"type":"webhook","label":"Webhook (1)"}},{"id":"n2","type":"custom","position":{"x":360,"y":200},"data":{"type":"ai_agent","label":"Ai Agent (2)"}},{"id":"n3","type":"custom","position":{"x":620,"y":200},"data":{"type":"notion","label":"Notion (3)"}},{"id":"n4","type":"custom","position":{"x":880,"y":200},"data":{"type":"log_output","label":"Log Output (4)"}}]'::jsonb,
  '[{"id":"e1","source":"n1","target":"n2","sourceHandle":"output","targetHandle":"input"},{"id":"e2","source":"n2","target":"n3","sourceHandle":"output","targetHandle":"input"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"output","targetHandle":"input"}]'::jsonb,
  'Beginner',
  12,
  ARRAY['Education', 'webhook', 'ai-agent', 'notion', 'log-output'],
  true,
  false,
  COALESCE((SELECT user_id FROM public.user_roles WHERE role = 'admin' LIMIT 1), (SELECT id FROM auth.users ORDER BY created_at LIMIT 1))
);


-- Template #59
INSERT INTO public.templates (name, description, category, nodes, edges, difficulty, estimated_setup_time, tags, is_active, is_featured, created_by)
VALUES (
  'Real Estate: Tag and classify sensor readings',
  'Starter workflow: Real Estate: Tag and classify sensor readings. Linear flow (form → google_calendar → twitter → log_output). Configure credentials and fields per node; extend in the canvas.',
  'Real Estate',
  '[{"id":"n1","type":"custom","position":{"x":100,"y":200},"data":{"type":"form","label":"Form (1)"}},{"id":"n2","type":"custom","position":{"x":360,"y":200},"data":{"type":"google_calendar","label":"Google Calendar (2)"}},{"id":"n3","type":"custom","position":{"x":620,"y":200},"data":{"type":"twitter","label":"Twitter (3)"}},{"id":"n4","type":"custom","position":{"x":880,"y":200},"data":{"type":"log_output","label":"Log Output (4)"}}]'::jsonb,
  '[{"id":"e1","source":"n1","target":"n2","sourceHandle":"output","targetHandle":"input"},{"id":"e2","source":"n2","target":"n3","sourceHandle":"output","targetHandle":"input"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"output","targetHandle":"input"}]'::jsonb,
  'Intermediate',
  13,
  ARRAY['Real Estate', 'form', 'google-calendar', 'twitter', 'log-output'],
  true,
  false,
  COALESCE((SELECT user_id FROM public.user_roles WHERE role = 'admin' LIMIT 1), (SELECT id FROM auth.users ORDER BY created_at LIMIT 1))
);


-- Template #60
INSERT INTO public.templates (name, description, category, nodes, edges, difficulty, estimated_setup_time, tags, is_active, is_featured, created_by)
VALUES (
  'Legal Ops: Handshake compliance exports',
  'Starter workflow: Legal Ops: Handshake compliance exports. Linear flow (interval → linkedin → set_variable → log_output). Configure credentials and fields per node; extend in the canvas.',
  'Legal',
  '[{"id":"n1","type":"custom","position":{"x":100,"y":200},"data":{"type":"interval","label":"Interval (1)"}},{"id":"n2","type":"custom","position":{"x":360,"y":200},"data":{"type":"linkedin","label":"Linkedin (2)"}},{"id":"n3","type":"custom","position":{"x":620,"y":200},"data":{"type":"set_variable","label":"Set Variable (3)"}},{"id":"n4","type":"custom","position":{"x":880,"y":200},"data":{"type":"log_output","label":"Log Output (4)"}}]'::jsonb,
  '[{"id":"e1","source":"n1","target":"n2","sourceHandle":"output","targetHandle":"input"},{"id":"e2","source":"n2","target":"n3","sourceHandle":"output","targetHandle":"input"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"output","targetHandle":"input"}]'::jsonb,
  'Advanced',
  14,
  ARRAY['Legal', 'interval', 'linkedin', 'set-variable', 'log-output'],
  true,
  false,
  COALESCE((SELECT user_id FROM public.user_roles WHERE role = 'admin' LIMIT 1), (SELECT id FROM auth.users ORDER BY created_at LIMIT 1))
);


-- Template #61
INSERT INTO public.templates (name, description, category, nodes, edges, difficulty, estimated_setup_time, tags, is_active, is_featured, created_by)
VALUES (
  'Manufacturing: Enrich feature flags',
  'Starter workflow: Manufacturing: Enrich feature flags. Linear flow (manual_trigger → http_request → google_sheets → log_output). Configure credentials and fields per node; extend in the canvas.',
  'Operations',
  '[{"id":"n1","type":"custom","position":{"x":100,"y":200},"data":{"type":"manual_trigger","label":"Manual Trigger (1)"}},{"id":"n2","type":"custom","position":{"x":360,"y":200},"data":{"type":"http_request","label":"Http Request (2)"}},{"id":"n3","type":"custom","position":{"x":620,"y":200},"data":{"type":"google_sheets","label":"Google Sheets (3)"}},{"id":"n4","type":"custom","position":{"x":880,"y":200},"data":{"type":"log_output","label":"Log Output (4)"}}]'::jsonb,
  '[{"id":"e1","source":"n1","target":"n2","sourceHandle":"output","targetHandle":"input"},{"id":"e2","source":"n2","target":"n3","sourceHandle":"output","targetHandle":"input"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"output","targetHandle":"input"}]'::jsonb,
  'Beginner',
  15,
  ARRAY['Operations', 'manual-trigger', 'http-request', 'google-sheets', 'log-output'],
  true,
  false,
  COALESCE((SELECT user_id FROM public.user_roles WHERE role = 'admin' LIMIT 1), (SELECT id FROM auth.users ORDER BY created_at LIMIT 1))
);


-- Template #62
INSERT INTO public.templates (name, description, category, nodes, edges, difficulty, estimated_setup_time, tags, is_active, is_featured, created_by)
VALUES (
  'Nonprofit: Redact asset depreciations',
  'Starter workflow: Nonprofit: Redact asset depreciations. Linear flow (schedule → telegram → mongodb → log_output). Configure credentials and fields per node; extend in the canvas.',
  'Nonprofit',
  '[{"id":"n1","type":"custom","position":{"x":100,"y":200},"data":{"type":"schedule","label":"Schedule (1)"}},{"id":"n2","type":"custom","position":{"x":360,"y":200},"data":{"type":"telegram","label":"Telegram (2)"}},{"id":"n3","type":"custom","position":{"x":620,"y":200},"data":{"type":"mongodb","label":"Mongodb (3)"}},{"id":"n4","type":"custom","position":{"x":880,"y":200},"data":{"type":"log_output","label":"Log Output (4)"}}]'::jsonb,
  '[{"id":"e1","source":"n1","target":"n2","sourceHandle":"output","targetHandle":"input"},{"id":"e2","source":"n2","target":"n3","sourceHandle":"output","targetHandle":"input"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"output","targetHandle":"input"}]'::jsonb,
  'Intermediate',
  16,
  ARRAY['Nonprofit', 'schedule', 'telegram', 'mongodb', 'log-output'],
  true,
  false,
  COALESCE((SELECT user_id FROM public.user_roles WHERE role = 'admin' LIMIT 1), (SELECT id FROM auth.users ORDER BY created_at LIMIT 1))
);


-- Template #63
INSERT INTO public.templates (name, description, category, nodes, edges, difficulty, estimated_setup_time, tags, is_active, is_featured, created_by)
VALUES (
  'Media & Publishing: Extract metrics from webhook payloads',
  'Starter workflow: Media & Publishing: Extract metrics from webhook payloads. Linear flow (webhook → csv → email → log_output). Configure credentials and fields per node; extend in the canvas.',
  'Media',
  '[{"id":"n1","type":"custom","position":{"x":100,"y":200},"data":{"type":"webhook","label":"Webhook (1)"}},{"id":"n2","type":"custom","position":{"x":360,"y":200},"data":{"type":"csv","label":"Csv (2)"}},{"id":"n3","type":"custom","position":{"x":620,"y":200},"data":{"type":"email","label":"Email (3)"}},{"id":"n4","type":"custom","position":{"x":880,"y":200},"data":{"type":"log_output","label":"Log Output (4)"}}]'::jsonb,
  '[{"id":"e1","source":"n1","target":"n2","sourceHandle":"output","targetHandle":"input"},{"id":"e2","source":"n2","target":"n3","sourceHandle":"output","targetHandle":"input"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"output","targetHandle":"input"}]'::jsonb,
  'Advanced',
  17,
  ARRAY['Media', 'webhook', 'csv', 'email', 'log-output'],
  true,
  false,
  COALESCE((SELECT user_id FROM public.user_roles WHERE role = 'admin' LIMIT 1), (SELECT id FROM auth.users ORDER BY created_at LIMIT 1))
);


-- Template #64
INSERT INTO public.templates (name, description, category, nodes, edges, difficulty, estimated_setup_time, tags, is_active, is_featured, created_by)
VALUES (
  'Logistics: Triage shipment events',
  'Starter workflow: Logistics: Triage shipment events. Linear flow (form → notion → ai_agent → log_output). Configure credentials and fields per node; extend in the canvas.',
  'Logistics',
  '[{"id":"n1","type":"custom","position":{"x":100,"y":200},"data":{"type":"form","label":"Form (1)"}},{"id":"n2","type":"custom","position":{"x":360,"y":200},"data":{"type":"notion","label":"Notion (2)"}},{"id":"n3","type":"custom","position":{"x":620,"y":200},"data":{"type":"ai_agent","label":"Ai Agent (3)"}},{"id":"n4","type":"custom","position":{"x":880,"y":200},"data":{"type":"log_output","label":"Log Output (4)"}}]'::jsonb,
  '[{"id":"e1","source":"n1","target":"n2","sourceHandle":"output","targetHandle":"input"},{"id":"e2","source":"n2","target":"n3","sourceHandle":"output","targetHandle":"input"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"output","targetHandle":"input"}]'::jsonb,
  'Beginner',
  18,
  ARRAY['Logistics', 'form', 'notion', 'ai-agent', 'log-output'],
  true,
  false,
  COALESCE((SELECT user_id FROM public.user_roles WHERE role = 'admin' LIMIT 1), (SELECT id FROM auth.users ORDER BY created_at LIMIT 1))
);


-- Template #65
INSERT INTO public.templates (name, description, category, nodes, edges, difficulty, estimated_setup_time, tags, is_active, is_featured, created_by)
VALUES (
  'Hospitality: Transform security findings',
  'Starter workflow: Hospitality: Transform security findings. Linear flow (interval → ai_chat_model → text_formatter → log_output). Configure credentials and fields per node; extend in the canvas.',
  'Hospitality',
  '[{"id":"n1","type":"custom","position":{"x":100,"y":200},"data":{"type":"interval","label":"Interval (1)"}},{"id":"n2","type":"custom","position":{"x":360,"y":200},"data":{"type":"ai_chat_model","label":"Ai Chat Model (2)"}},{"id":"n3","type":"custom","position":{"x":620,"y":200},"data":{"type":"text_formatter","label":"Text Formatter (3)"}},{"id":"n4","type":"custom","position":{"x":880,"y":200},"data":{"type":"log_output","label":"Log Output (4)"}}]'::jsonb,
  '[{"id":"e1","source":"n1","target":"n2","sourceHandle":"output","targetHandle":"input"},{"id":"e2","source":"n2","target":"n3","sourceHandle":"output","targetHandle":"input"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"output","targetHandle":"input"}]'::jsonb,
  'Intermediate',
  19,
  ARRAY['Hospitality', 'interval', 'ai-chat-model', 'text-formatter', 'log-output'],
  true,
  false,
  COALESCE((SELECT user_id FROM public.user_roles WHERE role = 'admin' LIMIT 1), (SELECT id FROM auth.users ORDER BY created_at LIMIT 1))
);


-- Template #66
INSERT INTO public.templates (name, description, category, nodes, edges, difficulty, estimated_setup_time, tags, is_active, is_featured, created_by)
VALUES (
  'SaaS Product: Back up release notes',
  'Starter workflow: SaaS Product: Back up release notes. Linear flow (manual_trigger → postgresql → mysql → log_output). Configure credentials and fields per node; extend in the canvas.',
  'Product',
  '[{"id":"n1","type":"custom","position":{"x":100,"y":200},"data":{"type":"manual_trigger","label":"Manual Trigger (1)"}},{"id":"n2","type":"custom","position":{"x":360,"y":200},"data":{"type":"postgresql","label":"Postgresql (2)"}},{"id":"n3","type":"custom","position":{"x":620,"y":200},"data":{"type":"mysql","label":"Mysql (3)"}},{"id":"n4","type":"custom","position":{"x":880,"y":200},"data":{"type":"log_output","label":"Log Output (4)"}}]'::jsonb,
  '[{"id":"e1","source":"n1","target":"n2","sourceHandle":"output","targetHandle":"input"},{"id":"e2","source":"n2","target":"n3","sourceHandle":"output","targetHandle":"input"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"output","targetHandle":"input"}]'::jsonb,
  'Advanced',
  20,
  ARRAY['Product', 'manual-trigger', 'postgresql', 'mysql', 'log-output'],
  true,
  false,
  COALESCE((SELECT user_id FROM public.user_roles WHERE role = 'admin' LIMIT 1), (SELECT id FROM auth.users ORDER BY created_at LIMIT 1))
);


-- Template #67
INSERT INTO public.templates (name, description, category, nodes, edges, difficulty, estimated_setup_time, tags, is_active, is_featured, created_by)
VALUES (
  'IT Service Desk: Sync course enrollments',
  'Starter workflow: IT Service Desk: Sync course enrollments. Linear flow (schedule → ai_service → slack_message → log_output). Configure credentials and fields per node; extend in the canvas.',
  'IT',
  '[{"id":"n1","type":"custom","position":{"x":100,"y":200},"data":{"type":"schedule","label":"Schedule (1)"}},{"id":"n2","type":"custom","position":{"x":360,"y":200},"data":{"type":"ai_service","label":"Ai Service (2)"}},{"id":"n3","type":"custom","position":{"x":620,"y":200},"data":{"type":"slack_message","label":"Slack Message (3)"}},{"id":"n4","type":"custom","position":{"x":880,"y":200},"data":{"type":"log_output","label":"Log Output (4)"}}]'::jsonb,
  '[{"id":"e1","source":"n1","target":"n2","sourceHandle":"output","targetHandle":"input"},{"id":"e2","source":"n2","target":"n3","sourceHandle":"output","targetHandle":"input"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"output","targetHandle":"input"}]'::jsonb,
  'Beginner',
  21,
  ARRAY['IT', 'schedule', 'ai-service', 'slack-message', 'log-output'],
  true,
  false,
  COALESCE((SELECT user_id FROM public.user_roles WHERE role = 'admin' LIMIT 1), (SELECT id FROM auth.users ORDER BY created_at LIMIT 1))
);


-- Template #68
INSERT INTO public.templates (name, description, category, nodes, edges, difficulty, estimated_setup_time, tags, is_active, is_featured, created_by)
VALUES (
  'Sales Ops: Score daily KPIs',
  'Starter workflow: Sales Ops: Score daily KPIs. Linear flow (webhook → google_sheets → ollama → log_output). Configure credentials and fields per node; extend in the canvas.',
  'CRM & Sales',
  '[{"id":"n1","type":"custom","position":{"x":100,"y":200},"data":{"type":"webhook","label":"Webhook (1)"}},{"id":"n2","type":"custom","position":{"x":360,"y":200},"data":{"type":"google_sheets","label":"Google Sheets (2)"}},{"id":"n3","type":"custom","position":{"x":620,"y":200},"data":{"type":"ollama","label":"Ollama (3)"}},{"id":"n4","type":"custom","position":{"x":880,"y":200},"data":{"type":"log_output","label":"Log Output (4)"}}]'::jsonb,
  '[{"id":"e1","source":"n1","target":"n2","sourceHandle":"output","targetHandle":"input"},{"id":"e2","source":"n2","target":"n3","sourceHandle":"output","targetHandle":"input"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"output","targetHandle":"input"}]'::jsonb,
  'Intermediate',
  22,
  ARRAY['CRM & Sales', 'webhook', 'google-sheets', 'ollama', 'log-output'],
  true,
  false,
  COALESCE((SELECT user_id FROM public.user_roles WHERE role = 'admin' LIMIT 1), (SELECT id FROM auth.users ORDER BY created_at LIMIT 1))
);


-- Template #69
INSERT INTO public.templates (name, description, category, nodes, edges, difficulty, estimated_setup_time, tags, is_active, is_featured, created_by)
VALUES (
  'Data Analytics: Normalize social mentions',
  'Starter workflow: Data Analytics: Normalize social mentions. Linear flow (form → email → csv → log_output). Configure credentials and fields per node; extend in the canvas.',
  'Data & BI',
  '[{"id":"n1","type":"custom","position":{"x":100,"y":200},"data":{"type":"form","label":"Form (1)"}},{"id":"n2","type":"custom","position":{"x":360,"y":200},"data":{"type":"email","label":"Email (2)"}},{"id":"n3","type":"custom","position":{"x":620,"y":200},"data":{"type":"csv","label":"Csv (3)"}},{"id":"n4","type":"custom","position":{"x":880,"y":200},"data":{"type":"log_output","label":"Log Output (4)"}}]'::jsonb,
  '[{"id":"e1","source":"n1","target":"n2","sourceHandle":"output","targetHandle":"input"},{"id":"e2","source":"n2","target":"n3","sourceHandle":"output","targetHandle":"input"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"output","targetHandle":"input"}]'::jsonb,
  'Advanced',
  23,
  ARRAY['Data & BI', 'form', 'email', 'csv', 'log-output'],
  true,
  false,
  COALESCE((SELECT user_id FROM public.user_roles WHERE role = 'admin' LIMIT 1), (SELECT id FROM auth.users ORDER BY created_at LIMIT 1))
);


-- Template #70
INSERT INTO public.templates (name, description, category, nodes, edges, difficulty, estimated_setup_time, tags, is_active, is_featured, created_by)
VALUES (
  'Security & GRC: Route partner SLAs',
  'Starter workflow: Security & GRC: Route partner SLAs. Linear flow (interval → filter → google_drive → log_output). Configure credentials and fields per node; extend in the canvas.',
  'Security',
  '[{"id":"n1","type":"custom","position":{"x":100,"y":200},"data":{"type":"interval","label":"Interval (1)"}},{"id":"n2","type":"custom","position":{"x":360,"y":200},"data":{"type":"filter","label":"Filter (2)"}},{"id":"n3","type":"custom","position":{"x":620,"y":200},"data":{"type":"google_drive","label":"Google Drive (3)"}},{"id":"n4","type":"custom","position":{"x":880,"y":200},"data":{"type":"log_output","label":"Log Output (4)"}}]'::jsonb,
  '[{"id":"e1","source":"n1","target":"n2","sourceHandle":"output","targetHandle":"input"},{"id":"e2","source":"n2","target":"n3","sourceHandle":"output","targetHandle":"input"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"output","targetHandle":"input"}]'::jsonb,
  'Beginner',
  24,
  ARRAY['Security', 'interval', 'filter', 'google-drive', 'log-output'],
  true,
  true,
  COALESCE((SELECT user_id FROM public.user_roles WHERE role = 'admin' LIMIT 1), (SELECT id FROM auth.users ORDER BY created_at LIMIT 1))
);


-- Template #71
INSERT INTO public.templates (name, description, category, nodes, edges, difficulty, estimated_setup_time, tags, is_active, is_featured, created_by)
VALUES (
  'Construction: Watermark on-call incidents',
  'Starter workflow: Construction: Watermark on-call incidents. Linear flow (manual_trigger → hubspot → clickup → log_output). Configure credentials and fields per node; extend in the canvas.',
  'Construction',
  '[{"id":"n1","type":"custom","position":{"x":100,"y":200},"data":{"type":"manual_trigger","label":"Manual Trigger (1)"}},{"id":"n2","type":"custom","position":{"x":360,"y":200},"data":{"type":"hubspot","label":"Hubspot (2)"}},{"id":"n3","type":"custom","position":{"x":620,"y":200},"data":{"type":"clickup","label":"Clickup (3)"}},{"id":"n4","type":"custom","position":{"x":880,"y":200},"data":{"type":"log_output","label":"Log Output (4)"}}]'::jsonb,
  '[{"id":"e1","source":"n1","target":"n2","sourceHandle":"output","targetHandle":"input"},{"id":"e2","source":"n2","target":"n3","sourceHandle":"output","targetHandle":"input"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"output","targetHandle":"input"}]'::jsonb,
  'Intermediate',
  25,
  ARRAY['Construction', 'manual-trigger', 'hubspot', 'clickup', 'log-output'],
  true,
  false,
  COALESCE((SELECT user_id FROM public.user_roles WHERE role = 'admin' LIMIT 1), (SELECT id FROM auth.users ORDER BY created_at LIMIT 1))
);


-- Template #72
INSERT INTO public.templates (name, description, category, nodes, edges, difficulty, estimated_setup_time, tags, is_active, is_featured, created_by)
VALUES (
  'Agriculture: Schedule room bookings',
  'Starter workflow: Agriculture: Schedule room bookings. Linear flow (schedule → set_variable → linkedin → log_output). Configure credentials and fields per node; extend in the canvas.',
  'Agriculture',
  '[{"id":"n1","type":"custom","position":{"x":100,"y":200},"data":{"type":"schedule","label":"Schedule (1)"}},{"id":"n2","type":"custom","position":{"x":360,"y":200},"data":{"type":"set_variable","label":"Set Variable (2)"}},{"id":"n3","type":"custom","position":{"x":620,"y":200},"data":{"type":"linkedin","label":"Linkedin (3)"}},{"id":"n4","type":"custom","position":{"x":880,"y":200},"data":{"type":"log_output","label":"Log Output (4)"}}]'::jsonb,
  '[{"id":"e1","source":"n1","target":"n2","sourceHandle":"output","targetHandle":"input"},{"id":"e2","source":"n2","target":"n3","sourceHandle":"output","targetHandle":"input"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"output","targetHandle":"input"}]'::jsonb,
  'Advanced',
  26,
  ARRAY['Agriculture', 'schedule', 'set-variable', 'linkedin', 'log-output'],
  true,
  false,
  COALESCE((SELECT user_id FROM public.user_roles WHERE role = 'admin' LIMIT 1), (SELECT id FROM auth.users ORDER BY created_at LIMIT 1))
);


-- Template #73
INSERT INTO public.templates (name, description, category, nodes, edges, difficulty, estimated_setup_time, tags, is_active, is_featured, created_by)
VALUES (
  'Energy: Publish calendar holds',
  'Starter workflow: Energy: Publish calendar holds. Linear flow (webhook → mysql → javascript → log_output). Configure credentials and fields per node; extend in the canvas.',
  'Energy',
  '[{"id":"n1","type":"custom","position":{"x":100,"y":200},"data":{"type":"webhook","label":"Webhook (1)"}},{"id":"n2","type":"custom","position":{"x":360,"y":200},"data":{"type":"mysql","label":"Mysql (2)"}},{"id":"n3","type":"custom","position":{"x":620,"y":200},"data":{"type":"javascript","label":"Javascript (3)"}},{"id":"n4","type":"custom","position":{"x":880,"y":200},"data":{"type":"log_output","label":"Log Output (4)"}}]'::jsonb,
  '[{"id":"e1","source":"n1","target":"n2","sourceHandle":"output","targetHandle":"input"},{"id":"e2","source":"n2","target":"n3","sourceHandle":"output","targetHandle":"input"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"output","targetHandle":"input"}]'::jsonb,
  'Beginner',
  27,
  ARRAY['Energy', 'webhook', 'mysql', 'javascript', 'log-output'],
  true,
  false,
  COALESCE((SELECT user_id FROM public.user_roles WHERE role = 'admin' LIMIT 1), (SELECT id FROM auth.users ORDER BY created_at LIMIT 1))
);


-- Template #74
INSERT INTO public.templates (name, description, category, nodes, edges, difficulty, estimated_setup_time, tags, is_active, is_featured, created_by)
VALUES (
  'Telecom: Archive help-center articles',
  'Starter workflow: Telecom: Archive help-center articles. Linear flow (form → ollama → google_sheets → log_output). Configure credentials and fields per node; extend in the canvas.',
  'Telecom',
  '[{"id":"n1","type":"custom","position":{"x":100,"y":200},"data":{"type":"form","label":"Form (1)"}},{"id":"n2","type":"custom","position":{"x":360,"y":200},"data":{"type":"ollama","label":"Ollama (2)"}},{"id":"n3","type":"custom","position":{"x":620,"y":200},"data":{"type":"google_sheets","label":"Google Sheets (3)"}},{"id":"n4","type":"custom","position":{"x":880,"y":200},"data":{"type":"log_output","label":"Log Output (4)"}}]'::jsonb,
  '[{"id":"e1","source":"n1","target":"n2","sourceHandle":"output","targetHandle":"input"},{"id":"e2","source":"n2","target":"n3","sourceHandle":"output","targetHandle":"input"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"output","targetHandle":"input"}]'::jsonb,
  'Intermediate',
  28,
  ARRAY['Telecom', 'form', 'ollama', 'google-sheets', 'log-output'],
  true,
  false,
  COALESCE((SELECT user_id FROM public.user_roles WHERE role = 'admin' LIMIT 1), (SELECT id FROM auth.users ORDER BY created_at LIMIT 1))
);


-- Template #75
INSERT INTO public.templates (name, description, category, nodes, edges, difficulty, estimated_setup_time, tags, is_active, is_featured, created_by)
VALUES (
  'Gov & Public Sector: Summarize board packets',
  'Starter workflow: Gov & Public Sector: Summarize board packets. Linear flow (interval → google_gmail → airtable → log_output). Configure credentials and fields per node; extend in the canvas.',
  'Public Sector',
  '[{"id":"n1","type":"custom","position":{"x":100,"y":200},"data":{"type":"interval","label":"Interval (1)"}},{"id":"n2","type":"custom","position":{"x":360,"y":200},"data":{"type":"google_gmail","label":"Google Gmail (2)"}},{"id":"n3","type":"custom","position":{"x":620,"y":200},"data":{"type":"airtable","label":"Airtable (3)"}},{"id":"n4","type":"custom","position":{"x":880,"y":200},"data":{"type":"log_output","label":"Log Output (4)"}}]'::jsonb,
  '[{"id":"e1","source":"n1","target":"n2","sourceHandle":"output","targetHandle":"input"},{"id":"e2","source":"n2","target":"n3","sourceHandle":"output","targetHandle":"input"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"output","targetHandle":"input"}]'::jsonb,
  'Advanced',
  29,
  ARRAY['Public Sector', 'interval', 'google-gmail', 'airtable', 'log-output'],
  true,
  false,
  COALESCE((SELECT user_id FROM public.user_roles WHERE role = 'admin' LIMIT 1), (SELECT id FROM auth.users ORDER BY created_at LIMIT 1))
);


-- Template #76
INSERT INTO public.templates (name, description, category, nodes, edges, difficulty, estimated_setup_time, tags, is_active, is_featured, created_by)
VALUES (
  'E-commerce: Automate vendor bills',
  'Starter workflow: E-commerce: Automate vendor bills. Linear flow (manual_trigger → outlook → twitter → log_output). Configure credentials and fields per node; extend in the canvas.',
  'Commerce & Retail',
  '[{"id":"n1","type":"custom","position":{"x":100,"y":200},"data":{"type":"manual_trigger","label":"Manual Trigger (1)"}},{"id":"n2","type":"custom","position":{"x":360,"y":200},"data":{"type":"outlook","label":"Outlook (2)"}},{"id":"n3","type":"custom","position":{"x":620,"y":200},"data":{"type":"twitter","label":"Twitter (3)"}},{"id":"n4","type":"custom","position":{"x":880,"y":200},"data":{"type":"log_output","label":"Log Output (4)"}}]'::jsonb,
  '[{"id":"e1","source":"n1","target":"n2","sourceHandle":"output","targetHandle":"input"},{"id":"e2","source":"n2","target":"n3","sourceHandle":"output","targetHandle":"input"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"output","targetHandle":"input"}]'::jsonb,
  'Beginner',
  5,
  ARRAY['Commerce & Retail', 'manual-trigger', 'outlook', 'twitter', 'log-output'],
  true,
  false,
  COALESCE((SELECT user_id FROM public.user_roles WHERE role = 'admin' LIMIT 1), (SELECT id FROM auth.users ORDER BY created_at LIMIT 1))
);


-- Template #77
INSERT INTO public.templates (name, description, category, nodes, edges, difficulty, estimated_setup_time, tags, is_active, is_featured, created_by)
VALUES (
  'Healthcare: Deduplicate prescription refills',
  'Starter workflow: Healthcare: Deduplicate prescription refills. Linear flow (schedule → text_formatter → ai_chat_model → log_output). Configure credentials and fields per node; extend in the canvas.',
  'Healthcare',
  '[{"id":"n1","type":"custom","position":{"x":100,"y":200},"data":{"type":"schedule","label":"Schedule (1)"}},{"id":"n2","type":"custom","position":{"x":360,"y":200},"data":{"type":"text_formatter","label":"Text Formatter (2)"}},{"id":"n3","type":"custom","position":{"x":620,"y":200},"data":{"type":"ai_chat_model","label":"Ai Chat Model (3)"}},{"id":"n4","type":"custom","position":{"x":880,"y":200},"data":{"type":"log_output","label":"Log Output (4)"}}]'::jsonb,
  '[{"id":"e1","source":"n1","target":"n2","sourceHandle":"output","targetHandle":"input"},{"id":"e2","source":"n2","target":"n3","sourceHandle":"output","targetHandle":"input"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"output","targetHandle":"input"}]'::jsonb,
  'Intermediate',
  6,
  ARRAY['Healthcare', 'schedule', 'text-formatter', 'ai-chat-model', 'log-output'],
  true,
  false,
  COALESCE((SELECT user_id FROM public.user_roles WHERE role = 'admin' LIMIT 1), (SELECT id FROM auth.users ORDER BY created_at LIMIT 1))
);


-- Template #78
INSERT INTO public.templates (name, description, category, nodes, edges, difficulty, estimated_setup_time, tags, is_active, is_featured, created_by)
VALUES (
  'Finance & Accounting: Parse inventory deltas',
  'Starter workflow: Finance & Accounting: Parse inventory deltas. Linear flow (webhook → clickup → function → log_output). Configure credentials and fields per node; extend in the canvas.',
  'Finance',
  '[{"id":"n1","type":"custom","position":{"x":100,"y":200},"data":{"type":"webhook","label":"Webhook (1)"}},{"id":"n2","type":"custom","position":{"x":360,"y":200},"data":{"type":"clickup","label":"Clickup (2)"}},{"id":"n3","type":"custom","position":{"x":620,"y":200},"data":{"type":"function","label":"Function (3)"}},{"id":"n4","type":"custom","position":{"x":880,"y":200},"data":{"type":"log_output","label":"Log Output (4)"}}]'::jsonb,
  '[{"id":"e1","source":"n1","target":"n2","sourceHandle":"output","targetHandle":"input"},{"id":"e2","source":"n2","target":"n3","sourceHandle":"output","targetHandle":"input"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"output","targetHandle":"input"}]'::jsonb,
  'Advanced',
  7,
  ARRAY['Finance', 'webhook', 'clickup', 'function', 'log-output'],
  true,
  false,
  COALESCE((SELECT user_id FROM public.user_roles WHERE role = 'admin' LIMIT 1), (SELECT id FROM auth.users ORDER BY created_at LIMIT 1))
);


-- Template #79
INSERT INTO public.templates (name, description, category, nodes, edges, difficulty, estimated_setup_time, tags, is_active, is_featured, created_by)
VALUES (
  'HR & People: Monitor warehouse scans',
  'Starter workflow: HR & People: Monitor warehouse scans. Linear flow (form → javascript → mysql → log_output). Configure credentials and fields per node; extend in the canvas.',
  'HR',
  '[{"id":"n1","type":"custom","position":{"x":100,"y":200},"data":{"type":"form","label":"Form (1)"}},{"id":"n2","type":"custom","position":{"x":360,"y":200},"data":{"type":"javascript","label":"Javascript (2)"}},{"id":"n3","type":"custom","position":{"x":620,"y":200},"data":{"type":"mysql","label":"Mysql (3)"}},{"id":"n4","type":"custom","position":{"x":880,"y":200},"data":{"type":"log_output","label":"Log Output (4)"}}]'::jsonb,
  '[{"id":"e1","source":"n1","target":"n2","sourceHandle":"output","targetHandle":"input"},{"id":"e2","source":"n2","target":"n3","sourceHandle":"output","targetHandle":"input"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"output","targetHandle":"input"}]'::jsonb,
  'Beginner',
  8,
  ARRAY['HR', 'form', 'javascript', 'mysql', 'log-output'],
  true,
  false,
  COALESCE((SELECT user_id FROM public.user_roles WHERE role = 'admin' LIMIT 1), (SELECT id FROM auth.users ORDER BY created_at LIMIT 1))
);


-- Template #80
INSERT INTO public.templates (name, description, category, nodes, edges, difficulty, estimated_setup_time, tags, is_active, is_featured, created_by)
VALUES (
  'DevOps & SRE: Aggregate NPS feedback',
  'Starter workflow: DevOps & SRE: Aggregate NPS feedback. Linear flow (interval → mongodb → telegram → log_output). Configure credentials and fields per node; extend in the canvas.',
  'Developer Tools',
  '[{"id":"n1","type":"custom","position":{"x":100,"y":200},"data":{"type":"interval","label":"Interval (1)"}},{"id":"n2","type":"custom","position":{"x":360,"y":200},"data":{"type":"mongodb","label":"Mongodb (2)"}},{"id":"n3","type":"custom","position":{"x":620,"y":200},"data":{"type":"telegram","label":"Telegram (3)"}},{"id":"n4","type":"custom","position":{"x":880,"y":200},"data":{"type":"log_output","label":"Log Output (4)"}}]'::jsonb,
  '[{"id":"e1","source":"n1","target":"n2","sourceHandle":"output","targetHandle":"input"},{"id":"e2","source":"n2","target":"n3","sourceHandle":"output","targetHandle":"input"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"output","targetHandle":"input"}]'::jsonb,
  'Intermediate',
  9,
  ARRAY['Developer Tools', 'interval', 'mongodb', 'telegram', 'log-output'],
  true,
  false,
  COALESCE((SELECT user_id FROM public.user_roles WHERE role = 'admin' LIMIT 1), (SELECT id FROM auth.users ORDER BY created_at LIMIT 1))
);


-- Template #81
INSERT INTO public.templates (name, description, category, nodes, edges, difficulty, estimated_setup_time, tags, is_active, is_featured, created_by)
VALUES (
  'Marketing: Validate subscription renewals',
  'Starter workflow: Marketing: Validate subscription renewals. Linear flow (manual_trigger → openai_gpt → ai_agent → log_output). Configure credentials and fields per node; extend in the canvas.',
  'Marketing & Growth',
  '[{"id":"n1","type":"custom","position":{"x":100,"y":200},"data":{"type":"manual_trigger","label":"Manual Trigger (1)"}},{"id":"n2","type":"custom","position":{"x":360,"y":200},"data":{"type":"openai_gpt","label":"Openai Gpt (2)"}},{"id":"n3","type":"custom","position":{"x":620,"y":200},"data":{"type":"ai_agent","label":"Ai Agent (3)"}},{"id":"n4","type":"custom","position":{"x":880,"y":200},"data":{"type":"log_output","label":"Log Output (4)"}}]'::jsonb,
  '[{"id":"e1","source":"n1","target":"n2","sourceHandle":"output","targetHandle":"input"},{"id":"e2","source":"n2","target":"n3","sourceHandle":"output","targetHandle":"input"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"output","targetHandle":"input"}]'::jsonb,
  'Advanced',
  10,
  ARRAY['Marketing & Growth', 'manual-trigger', 'openai-gpt', 'ai-agent', 'log-output'],
  true,
  false,
  COALESCE((SELECT user_id FROM public.user_roles WHERE role = 'admin' LIMIT 1), (SELECT id FROM auth.users ORDER BY created_at LIMIT 1))
);


-- Template #82
INSERT INTO public.templates (name, description, category, nodes, edges, difficulty, estimated_setup_time, tags, is_active, is_featured, created_by)
VALUES (
  'Customer Support: Reconcile IoT heartbeats',
  'Starter workflow: Customer Support: Reconcile IoT heartbeats. Linear flow (schedule → google_drive → filter → log_output). Configure credentials and fields per node; extend in the canvas.',
  'Support',
  '[{"id":"n1","type":"custom","position":{"x":100,"y":200},"data":{"type":"schedule","label":"Schedule (1)"}},{"id":"n2","type":"custom","position":{"x":360,"y":200},"data":{"type":"google_drive","label":"Google Drive (2)"}},{"id":"n3","type":"custom","position":{"x":620,"y":200},"data":{"type":"filter","label":"Filter (3)"}},{"id":"n4","type":"custom","position":{"x":880,"y":200},"data":{"type":"log_output","label":"Log Output (4)"}}]'::jsonb,
  '[{"id":"e1","source":"n1","target":"n2","sourceHandle":"output","targetHandle":"input"},{"id":"e2","source":"n2","target":"n3","sourceHandle":"output","targetHandle":"input"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"output","targetHandle":"input"}]'::jsonb,
  'Beginner',
  11,
  ARRAY['Support', 'schedule', 'google-drive', 'filter', 'log-output'],
  true,
  false,
  COALESCE((SELECT user_id FROM public.user_roles WHERE role = 'admin' LIMIT 1), (SELECT id FROM auth.users ORDER BY created_at LIMIT 1))
);


-- Template #83
INSERT INTO public.templates (name, description, category, nodes, edges, difficulty, estimated_setup_time, tags, is_active, is_featured, created_by)
VALUES (
  'Education: Notify stakeholders about invoice lines',
  'Starter workflow: Education: Notify stakeholders about invoice lines. Linear flow (webhook → twitter → google_calendar → log_output). Configure credentials and fields per node; extend in the canvas.',
  'Education',
  '[{"id":"n1","type":"custom","position":{"x":100,"y":200},"data":{"type":"webhook","label":"Webhook (1)"}},{"id":"n2","type":"custom","position":{"x":360,"y":200},"data":{"type":"twitter","label":"Twitter (2)"}},{"id":"n3","type":"custom","position":{"x":620,"y":200},"data":{"type":"google_calendar","label":"Google Calendar (3)"}},{"id":"n4","type":"custom","position":{"x":880,"y":200},"data":{"type":"log_output","label":"Log Output (4)"}}]'::jsonb,
  '[{"id":"e1","source":"n1","target":"n2","sourceHandle":"output","targetHandle":"input"},{"id":"e2","source":"n2","target":"n3","sourceHandle":"output","targetHandle":"input"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"output","targetHandle":"input"}]'::jsonb,
  'Intermediate',
  12,
  ARRAY['Education', 'webhook', 'twitter', 'google-calendar', 'log-output'],
  true,
  false,
  COALESCE((SELECT user_id FROM public.user_roles WHERE role = 'admin' LIMIT 1), (SELECT id FROM auth.users ORDER BY created_at LIMIT 1))
);


-- Template #84
INSERT INTO public.templates (name, description, category, nodes, edges, difficulty, estimated_setup_time, tags, is_active, is_featured, created_by)
VALUES (
  'Real Estate: Tag and classify policy attestations',
  'Starter workflow: Real Estate: Tag and classify policy attestations. Linear flow (form → function → clickup → log_output). Configure credentials and fields per node; extend in the canvas.',
  'Real Estate',
  '[{"id":"n1","type":"custom","position":{"x":100,"y":200},"data":{"type":"form","label":"Form (1)"}},{"id":"n2","type":"custom","position":{"x":360,"y":200},"data":{"type":"function","label":"Function (2)"}},{"id":"n3","type":"custom","position":{"x":620,"y":200},"data":{"type":"clickup","label":"Clickup (3)"}},{"id":"n4","type":"custom","position":{"x":880,"y":200},"data":{"type":"log_output","label":"Log Output (4)"}}]'::jsonb,
  '[{"id":"e1","source":"n1","target":"n2","sourceHandle":"output","targetHandle":"input"},{"id":"e2","source":"n2","target":"n3","sourceHandle":"output","targetHandle":"input"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"output","targetHandle":"input"}]'::jsonb,
  'Advanced',
  13,
  ARRAY['Real Estate', 'form', 'function', 'clickup', 'log-output'],
  true,
  false,
  COALESCE((SELECT user_id FROM public.user_roles WHERE role = 'admin' LIMIT 1), (SELECT id FROM auth.users ORDER BY created_at LIMIT 1))
);


-- Template #85
INSERT INTO public.templates (name, description, category, nodes, edges, difficulty, estimated_setup_time, tags, is_active, is_featured, created_by)
VALUES (
  'Legal Ops: Handshake new leads',
  'Starter workflow: Legal Ops: Handshake new leads. Linear flow (interval → slack_message → ai_service → log_output). Configure credentials and fields per node; extend in the canvas.',
  'Legal',
  '[{"id":"n1","type":"custom","position":{"x":100,"y":200},"data":{"type":"interval","label":"Interval (1)"}},{"id":"n2","type":"custom","position":{"x":360,"y":200},"data":{"type":"slack_message","label":"Slack Message (2)"}},{"id":"n3","type":"custom","position":{"x":620,"y":200},"data":{"type":"ai_service","label":"Ai Service (3)"}},{"id":"n4","type":"custom","position":{"x":880,"y":200},"data":{"type":"log_output","label":"Log Output (4)"}}]'::jsonb,
  '[{"id":"e1","source":"n1","target":"n2","sourceHandle":"output","targetHandle":"input"},{"id":"e2","source":"n2","target":"n3","sourceHandle":"output","targetHandle":"input"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"output","targetHandle":"input"}]'::jsonb,
  'Beginner',
  14,
  ARRAY['Legal', 'interval', 'slack-message', 'ai-service', 'log-output'],
  true,
  false,
  COALESCE((SELECT user_id FROM public.user_roles WHERE role = 'admin' LIMIT 1), (SELECT id FROM auth.users ORDER BY created_at LIMIT 1))
);


-- Template #86
INSERT INTO public.templates (name, description, category, nodes, edges, difficulty, estimated_setup_time, tags, is_active, is_featured, created_by)
VALUES (
  'Manufacturing: Enrich expense receipts',
  'Starter workflow: Manufacturing: Enrich expense receipts. Linear flow (manual_trigger → json_parser → csv → log_output). Configure credentials and fields per node; extend in the canvas.',
  'Operations',
  '[{"id":"n1","type":"custom","position":{"x":100,"y":200},"data":{"type":"manual_trigger","label":"Manual Trigger (1)"}},{"id":"n2","type":"custom","position":{"x":360,"y":200},"data":{"type":"json_parser","label":"Json Parser (2)"}},{"id":"n3","type":"custom","position":{"x":620,"y":200},"data":{"type":"csv","label":"Csv (3)"}},{"id":"n4","type":"custom","position":{"x":880,"y":200},"data":{"type":"log_output","label":"Log Output (4)"}}]'::jsonb,
  '[{"id":"e1","source":"n1","target":"n2","sourceHandle":"output","targetHandle":"input"},{"id":"e2","source":"n2","target":"n3","sourceHandle":"output","targetHandle":"input"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"output","targetHandle":"input"}]'::jsonb,
  'Intermediate',
  15,
  ARRAY['Operations', 'manual-trigger', 'json-parser', 'csv', 'log-output'],
  true,
  false,
  COALESCE((SELECT user_id FROM public.user_roles WHERE role = 'admin' LIMIT 1), (SELECT id FROM auth.users ORDER BY created_at LIMIT 1))
);


-- Template #87
INSERT INTO public.templates (name, description, category, nodes, edges, difficulty, estimated_setup_time, tags, is_active, is_featured, created_by)
VALUES (
  'Nonprofit: Redact API error bursts',
  'Starter workflow: Nonprofit: Redact API error bursts. Linear flow (schedule → airtable → google_gmail → log_output). Configure credentials and fields per node; extend in the canvas.',
  'Nonprofit',
  '[{"id":"n1","type":"custom","position":{"x":100,"y":200},"data":{"type":"schedule","label":"Schedule (1)"}},{"id":"n2","type":"custom","position":{"x":360,"y":200},"data":{"type":"airtable","label":"Airtable (2)"}},{"id":"n3","type":"custom","position":{"x":620,"y":200},"data":{"type":"google_gmail","label":"Google Gmail (3)"}},{"id":"n4","type":"custom","position":{"x":880,"y":200},"data":{"type":"log_output","label":"Log Output (4)"}}]'::jsonb,
  '[{"id":"e1","source":"n1","target":"n2","sourceHandle":"output","targetHandle":"input"},{"id":"e2","source":"n2","target":"n3","sourceHandle":"output","targetHandle":"input"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"output","targetHandle":"input"}]'::jsonb,
  'Advanced',
  16,
  ARRAY['Nonprofit', 'schedule', 'airtable', 'google-gmail', 'log-output'],
  true,
  false,
  COALESCE((SELECT user_id FROM public.user_roles WHERE role = 'admin' LIMIT 1), (SELECT id FROM auth.users ORDER BY created_at LIMIT 1))
);


-- Template #88
INSERT INTO public.templates (name, description, category, nodes, edges, difficulty, estimated_setup_time, tags, is_active, is_featured, created_by)
VALUES (
  'Media & Publishing: Extract metrics from contract PDFs',
  'Starter workflow: Media & Publishing: Extract metrics from contract PDFs. Linear flow (webhook → ai_agent → notion → log_output). Configure credentials and fields per node; extend in the canvas.',
  'Media',
  '[{"id":"n1","type":"custom","position":{"x":100,"y":200},"data":{"type":"webhook","label":"Webhook (1)"}},{"id":"n2","type":"custom","position":{"x":360,"y":200},"data":{"type":"ai_agent","label":"Ai Agent (2)"}},{"id":"n3","type":"custom","position":{"x":620,"y":200},"data":{"type":"notion","label":"Notion (3)"}},{"id":"n4","type":"custom","position":{"x":880,"y":200},"data":{"type":"log_output","label":"Log Output (4)"}}]'::jsonb,
  '[{"id":"e1","source":"n1","target":"n2","sourceHandle":"output","targetHandle":"input"},{"id":"e2","source":"n2","target":"n3","sourceHandle":"output","targetHandle":"input"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"output","targetHandle":"input"}]'::jsonb,
  'Beginner',
  17,
  ARRAY['Media', 'webhook', 'ai-agent', 'notion', 'log-output'],
  true,
  false,
  COALESCE((SELECT user_id FROM public.user_roles WHERE role = 'admin' LIMIT 1), (SELECT id FROM auth.users ORDER BY created_at LIMIT 1))
);


-- Template #89
INSERT INTO public.templates (name, description, category, nodes, edges, difficulty, estimated_setup_time, tags, is_active, is_featured, created_by)
VALUES (
  'Logistics: Triage loan applications',
  'Starter workflow: Logistics: Triage loan applications. Linear flow (form → google_calendar → twitter → log_output). Configure credentials and fields per node; extend in the canvas.',
  'Logistics',
  '[{"id":"n1","type":"custom","position":{"x":100,"y":200},"data":{"type":"form","label":"Form (1)"}},{"id":"n2","type":"custom","position":{"x":360,"y":200},"data":{"type":"google_calendar","label":"Google Calendar (2)"}},{"id":"n3","type":"custom","position":{"x":620,"y":200},"data":{"type":"twitter","label":"Twitter (3)"}},{"id":"n4","type":"custom","position":{"x":880,"y":200},"data":{"type":"log_output","label":"Log Output (4)"}}]'::jsonb,
  '[{"id":"e1","source":"n1","target":"n2","sourceHandle":"output","targetHandle":"input"},{"id":"e2","source":"n2","target":"n3","sourceHandle":"output","targetHandle":"input"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"output","targetHandle":"input"}]'::jsonb,
  'Intermediate',
  18,
  ARRAY['Logistics', 'form', 'google-calendar', 'twitter', 'log-output'],
  true,
  false,
  COALESCE((SELECT user_id FROM public.user_roles WHERE role = 'admin' LIMIT 1), (SELECT id FROM auth.users ORDER BY created_at LIMIT 1))
);


-- Template #90
INSERT INTO public.templates (name, description, category, nodes, edges, difficulty, estimated_setup_time, tags, is_active, is_featured, created_by)
VALUES (
  'Hospitality: Transform ticket updates',
  'Starter workflow: Hospitality: Transform ticket updates. Linear flow (interval → linkedin → set_variable → log_output). Configure credentials and fields per node; extend in the canvas.',
  'Hospitality',
  '[{"id":"n1","type":"custom","position":{"x":100,"y":200},"data":{"type":"interval","label":"Interval (1)"}},{"id":"n2","type":"custom","position":{"x":360,"y":200},"data":{"type":"linkedin","label":"Linkedin (2)"}},{"id":"n3","type":"custom","position":{"x":620,"y":200},"data":{"type":"set_variable","label":"Set Variable (3)"}},{"id":"n4","type":"custom","position":{"x":880,"y":200},"data":{"type":"log_output","label":"Log Output (4)"}}]'::jsonb,
  '[{"id":"e1","source":"n1","target":"n2","sourceHandle":"output","targetHandle":"input"},{"id":"e2","source":"n2","target":"n3","sourceHandle":"output","targetHandle":"input"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"output","targetHandle":"input"}]'::jsonb,
  'Advanced',
  19,
  ARRAY['Hospitality', 'interval', 'linkedin', 'set-variable', 'log-output'],
  true,
  false,
  COALESCE((SELECT user_id FROM public.user_roles WHERE role = 'admin' LIMIT 1), (SELECT id FROM auth.users ORDER BY created_at LIMIT 1))
);


-- Template #91
INSERT INTO public.templates (name, description, category, nodes, edges, difficulty, estimated_setup_time, tags, is_active, is_featured, created_by)
VALUES (
  'SaaS Product: Back up candidate applications',
  'Starter workflow: SaaS Product: Back up candidate applications. Linear flow (manual_trigger → http_request → google_sheets → log_output). Configure credentials and fields per node; extend in the canvas.',
  'Product',
  '[{"id":"n1","type":"custom","position":{"x":100,"y":200},"data":{"type":"manual_trigger","label":"Manual Trigger (1)"}},{"id":"n2","type":"custom","position":{"x":360,"y":200},"data":{"type":"http_request","label":"Http Request (2)"}},{"id":"n3","type":"custom","position":{"x":620,"y":200},"data":{"type":"google_sheets","label":"Google Sheets (3)"}},{"id":"n4","type":"custom","position":{"x":880,"y":200},"data":{"type":"log_output","label":"Log Output (4)"}}]'::jsonb,
  '[{"id":"e1","source":"n1","target":"n2","sourceHandle":"output","targetHandle":"input"},{"id":"e2","source":"n2","target":"n3","sourceHandle":"output","targetHandle":"input"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"output","targetHandle":"input"}]'::jsonb,
  'Beginner',
  20,
  ARRAY['Product', 'manual-trigger', 'http-request', 'google-sheets', 'log-output'],
  true,
  false,
  COALESCE((SELECT user_id FROM public.user_roles WHERE role = 'admin' LIMIT 1), (SELECT id FROM auth.users ORDER BY created_at LIMIT 1))
);


-- Template #92
INSERT INTO public.templates (name, description, category, nodes, edges, difficulty, estimated_setup_time, tags, is_active, is_featured, created_by)
VALUES (
  'IT Service Desk: Sync schema migrations',
  'Starter workflow: IT Service Desk: Sync schema migrations. Linear flow (schedule → telegram → mongodb → log_output). Configure credentials and fields per node; extend in the canvas.',
  'IT',
  '[{"id":"n1","type":"custom","position":{"x":100,"y":200},"data":{"type":"schedule","label":"Schedule (1)"}},{"id":"n2","type":"custom","position":{"x":360,"y":200},"data":{"type":"telegram","label":"Telegram (2)"}},{"id":"n3","type":"custom","position":{"x":620,"y":200},"data":{"type":"mongodb","label":"Mongodb (3)"}},{"id":"n4","type":"custom","position":{"x":880,"y":200},"data":{"type":"log_output","label":"Log Output (4)"}}]'::jsonb,
  '[{"id":"e1","source":"n1","target":"n2","sourceHandle":"output","targetHandle":"input"},{"id":"e2","source":"n2","target":"n3","sourceHandle":"output","targetHandle":"input"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"output","targetHandle":"input"}]'::jsonb,
  'Intermediate',
  21,
  ARRAY['IT', 'schedule', 'telegram', 'mongodb', 'log-output'],
  true,
  false,
  COALESCE((SELECT user_id FROM public.user_roles WHERE role = 'admin' LIMIT 1), (SELECT id FROM auth.users ORDER BY created_at LIMIT 1))
);


-- Template #93
INSERT INTO public.templates (name, description, category, nodes, edges, difficulty, estimated_setup_time, tags, is_active, is_featured, created_by)
VALUES (
  'Sales Ops: Score survey results',
  'Starter workflow: Sales Ops: Score survey results. Linear flow (webhook → csv → email → log_output). Configure credentials and fields per node; extend in the canvas.',
  'CRM & Sales',
  '[{"id":"n1","type":"custom","position":{"x":100,"y":200},"data":{"type":"webhook","label":"Webhook (1)"}},{"id":"n2","type":"custom","position":{"x":360,"y":200},"data":{"type":"csv","label":"Csv (2)"}},{"id":"n3","type":"custom","position":{"x":620,"y":200},"data":{"type":"email","label":"Email (3)"}},{"id":"n4","type":"custom","position":{"x":880,"y":200},"data":{"type":"log_output","label":"Log Output (4)"}}]'::jsonb,
  '[{"id":"e1","source":"n1","target":"n2","sourceHandle":"output","targetHandle":"input"},{"id":"e2","source":"n2","target":"n3","sourceHandle":"output","targetHandle":"input"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"output","targetHandle":"input"}]'::jsonb,
  'Advanced',
  22,
  ARRAY['CRM & Sales', 'webhook', 'csv', 'email', 'log-output'],
  true,
  true,
  COALESCE((SELECT user_id FROM public.user_roles WHERE role = 'admin' LIMIT 1), (SELECT id FROM auth.users ORDER BY created_at LIMIT 1))
);


-- Template #94
INSERT INTO public.templates (name, description, category, nodes, edges, difficulty, estimated_setup_time, tags, is_active, is_featured, created_by)
VALUES (
  'Data Analytics: Normalize grant submissions',
  'Starter workflow: Data Analytics: Normalize grant submissions. Linear flow (form → notion → ai_agent → log_output). Configure credentials and fields per node; extend in the canvas.',
  'Data & BI',
  '[{"id":"n1","type":"custom","position":{"x":100,"y":200},"data":{"type":"form","label":"Form (1)"}},{"id":"n2","type":"custom","position":{"x":360,"y":200},"data":{"type":"notion","label":"Notion (2)"}},{"id":"n3","type":"custom","position":{"x":620,"y":200},"data":{"type":"ai_agent","label":"Ai Agent (3)"}},{"id":"n4","type":"custom","position":{"x":880,"y":200},"data":{"type":"log_output","label":"Log Output (4)"}}]'::jsonb,
  '[{"id":"e1","source":"n1","target":"n2","sourceHandle":"output","targetHandle":"input"},{"id":"e2","source":"n2","target":"n3","sourceHandle":"output","targetHandle":"input"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"output","targetHandle":"input"}]'::jsonb,
  'Beginner',
  23,
  ARRAY['Data & BI', 'form', 'notion', 'ai-agent', 'log-output'],
  true,
  false,
  COALESCE((SELECT user_id FROM public.user_roles WHERE role = 'admin' LIMIT 1), (SELECT id FROM auth.users ORDER BY created_at LIMIT 1))
);


-- Template #95
INSERT INTO public.templates (name, description, category, nodes, edges, difficulty, estimated_setup_time, tags, is_active, is_featured, created_by)
VALUES (
  'Security & GRC: Route CSV uploads',
  'Starter workflow: Security & GRC: Route CSV uploads. Linear flow (interval → ai_chat_model → text_formatter → log_output). Configure credentials and fields per node; extend in the canvas.',
  'Security',
  '[{"id":"n1","type":"custom","position":{"x":100,"y":200},"data":{"type":"interval","label":"Interval (1)"}},{"id":"n2","type":"custom","position":{"x":360,"y":200},"data":{"type":"ai_chat_model","label":"Ai Chat Model (2)"}},{"id":"n3","type":"custom","position":{"x":620,"y":200},"data":{"type":"text_formatter","label":"Text Formatter (3)"}},{"id":"n4","type":"custom","position":{"x":880,"y":200},"data":{"type":"log_output","label":"Log Output (4)"}}]'::jsonb,
  '[{"id":"e1","source":"n1","target":"n2","sourceHandle":"output","targetHandle":"input"},{"id":"e2","source":"n2","target":"n3","sourceHandle":"output","targetHandle":"input"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"output","targetHandle":"input"}]'::jsonb,
  'Intermediate',
  24,
  ARRAY['Security', 'interval', 'ai-chat-model', 'text-formatter', 'log-output'],
  true,
  false,
  COALESCE((SELECT user_id FROM public.user_roles WHERE role = 'admin' LIMIT 1), (SELECT id FROM auth.users ORDER BY created_at LIMIT 1))
);


-- Template #96
INSERT INTO public.templates (name, description, category, nodes, edges, difficulty, estimated_setup_time, tags, is_active, is_featured, created_by)
VALUES (
  'Construction: Watermark patient intake forms',
  'Starter workflow: Construction: Watermark patient intake forms. Linear flow (manual_trigger → postgresql → mysql → log_output). Configure credentials and fields per node; extend in the canvas.',
  'Construction',
  '[{"id":"n1","type":"custom","position":{"x":100,"y":200},"data":{"type":"manual_trigger","label":"Manual Trigger (1)"}},{"id":"n2","type":"custom","position":{"x":360,"y":200},"data":{"type":"postgresql","label":"Postgresql (2)"}},{"id":"n3","type":"custom","position":{"x":620,"y":200},"data":{"type":"mysql","label":"Mysql (3)"}},{"id":"n4","type":"custom","position":{"x":880,"y":200},"data":{"type":"log_output","label":"Log Output (4)"}}]'::jsonb,
  '[{"id":"e1","source":"n1","target":"n2","sourceHandle":"output","targetHandle":"input"},{"id":"e2","source":"n2","target":"n3","sourceHandle":"output","targetHandle":"input"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"output","targetHandle":"input"}]'::jsonb,
  'Advanced',
  25,
  ARRAY['Construction', 'manual-trigger', 'postgresql', 'mysql', 'log-output'],
  true,
  false,
  COALESCE((SELECT user_id FROM public.user_roles WHERE role = 'admin' LIMIT 1), (SELECT id FROM auth.users ORDER BY created_at LIMIT 1))
);


-- Template #97
INSERT INTO public.templates (name, description, category, nodes, edges, difficulty, estimated_setup_time, tags, is_active, is_featured, created_by)
VALUES (
  'Agriculture: Schedule backup manifests',
  'Starter workflow: Agriculture: Schedule backup manifests. Linear flow (schedule → ai_service → slack_message → log_output). Configure credentials and fields per node; extend in the canvas.',
  'Agriculture',
  '[{"id":"n1","type":"custom","position":{"x":100,"y":200},"data":{"type":"schedule","label":"Schedule (1)"}},{"id":"n2","type":"custom","position":{"x":360,"y":200},"data":{"type":"ai_service","label":"Ai Service (2)"}},{"id":"n3","type":"custom","position":{"x":620,"y":200},"data":{"type":"slack_message","label":"Slack Message (3)"}},{"id":"n4","type":"custom","position":{"x":880,"y":200},"data":{"type":"log_output","label":"Log Output (4)"}}]'::jsonb,
  '[{"id":"e1","source":"n1","target":"n2","sourceHandle":"output","targetHandle":"input"},{"id":"e2","source":"n2","target":"n3","sourceHandle":"output","targetHandle":"input"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"output","targetHandle":"input"}]'::jsonb,
  'Beginner',
  26,
  ARRAY['Agriculture', 'schedule', 'ai-service', 'slack-message', 'log-output'],
  true,
  false,
  COALESCE((SELECT user_id FROM public.user_roles WHERE role = 'admin' LIMIT 1), (SELECT id FROM auth.users ORDER BY created_at LIMIT 1))
);


-- Template #98
INSERT INTO public.templates (name, description, category, nodes, edges, difficulty, estimated_setup_time, tags, is_active, is_featured, created_by)
VALUES (
  'Energy: Publish experiment logs',
  'Starter workflow: Energy: Publish experiment logs. Linear flow (webhook → google_sheets → ollama → log_output). Configure credentials and fields per node; extend in the canvas.',
  'Energy',
  '[{"id":"n1","type":"custom","position":{"x":100,"y":200},"data":{"type":"webhook","label":"Webhook (1)"}},{"id":"n2","type":"custom","position":{"x":360,"y":200},"data":{"type":"google_sheets","label":"Google Sheets (2)"}},{"id":"n3","type":"custom","position":{"x":620,"y":200},"data":{"type":"ollama","label":"Ollama (3)"}},{"id":"n4","type":"custom","position":{"x":880,"y":200},"data":{"type":"log_output","label":"Log Output (4)"}}]'::jsonb,
  '[{"id":"e1","source":"n1","target":"n2","sourceHandle":"output","targetHandle":"input"},{"id":"e2","source":"n2","target":"n3","sourceHandle":"output","targetHandle":"input"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"output","targetHandle":"input"}]'::jsonb,
  'Intermediate',
  27,
  ARRAY['Energy', 'webhook', 'google-sheets', 'ollama', 'log-output'],
  true,
  false,
  COALESCE((SELECT user_id FROM public.user_roles WHERE role = 'admin' LIMIT 1), (SELECT id FROM auth.users ORDER BY created_at LIMIT 1))
);


-- Template #99
INSERT INTO public.templates (name, description, category, nodes, edges, difficulty, estimated_setup_time, tags, is_active, is_featured, created_by)
VALUES (
  'Telecom: Archive court filings',
  'Starter workflow: Telecom: Archive court filings. Linear flow (form → email → csv → log_output). Configure credentials and fields per node; extend in the canvas.',
  'Telecom',
  '[{"id":"n1","type":"custom","position":{"x":100,"y":200},"data":{"type":"form","label":"Form (1)"}},{"id":"n2","type":"custom","position":{"x":360,"y":200},"data":{"type":"email","label":"Email (2)"}},{"id":"n3","type":"custom","position":{"x":620,"y":200},"data":{"type":"csv","label":"Csv (3)"}},{"id":"n4","type":"custom","position":{"x":880,"y":200},"data":{"type":"log_output","label":"Log Output (4)"}}]'::jsonb,
  '[{"id":"e1","source":"n1","target":"n2","sourceHandle":"output","targetHandle":"input"},{"id":"e2","source":"n2","target":"n3","sourceHandle":"output","targetHandle":"input"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"output","targetHandle":"input"}]'::jsonb,
  'Advanced',
  28,
  ARRAY['Telecom', 'form', 'email', 'csv', 'log-output'],
  true,
  false,
  COALESCE((SELECT user_id FROM public.user_roles WHERE role = 'admin' LIMIT 1), (SELECT id FROM auth.users ORDER BY created_at LIMIT 1))
);


-- Template #100
INSERT INTO public.templates (name, description, category, nodes, edges, difficulty, estimated_setup_time, tags, is_active, is_featured, created_by)
VALUES (
  'Gov & Public Sector: Summarize form responses',
  'Starter workflow: Gov & Public Sector: Summarize form responses. Linear flow (interval → filter → google_drive → log_output). Configure credentials and fields per node; extend in the canvas.',
  'Public Sector',
  '[{"id":"n1","type":"custom","position":{"x":100,"y":200},"data":{"type":"interval","label":"Interval (1)"}},{"id":"n2","type":"custom","position":{"x":360,"y":200},"data":{"type":"filter","label":"Filter (2)"}},{"id":"n3","type":"custom","position":{"x":620,"y":200},"data":{"type":"google_drive","label":"Google Drive (3)"}},{"id":"n4","type":"custom","position":{"x":880,"y":200},"data":{"type":"log_output","label":"Log Output (4)"}}]'::jsonb,
  '[{"id":"e1","source":"n1","target":"n2","sourceHandle":"output","targetHandle":"input"},{"id":"e2","source":"n2","target":"n3","sourceHandle":"output","targetHandle":"input"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"output","targetHandle":"input"}]'::jsonb,
  'Beginner',
  29,
  ARRAY['Public Sector', 'interval', 'filter', 'google-drive', 'log-output'],
  true,
  false,
  COALESCE((SELECT user_id FROM public.user_roles WHERE role = 'admin' LIMIT 1), (SELECT id FROM auth.users ORDER BY created_at LIMIT 1))
);


COMMIT;
