-- =============================================================================
-- Registry-aligned template seed batch 4 of 10
-- Templates 151–200 of 500
-- Generated by ctrl_checks/scripts/generate-workflow-templates-sql.ts
-- Run 00_delete_all_templates.sql first if replacing the full catalog.
-- =============================================================================

BEGIN;

-- Template #151
INSERT INTO public.templates (name, description, category, nodes, edges, difficulty, estimated_setup_time, tags, is_active, is_featured, created_by)
VALUES (
  'E-commerce: Automate course enrollments',
  'Starter workflow: E-commerce: Automate course enrollments. Linear flow (manual_trigger → http_request → google_sheets → log_output). Configure credentials and fields per node; extend in the canvas.',
  'Commerce & Retail',
  '[{"id":"n1","type":"custom","position":{"x":100,"y":200},"data":{"type":"manual_trigger","label":"Manual Trigger (1)"}},{"id":"n2","type":"custom","position":{"x":360,"y":200},"data":{"type":"http_request","label":"Http Request (2)"}},{"id":"n3","type":"custom","position":{"x":620,"y":200},"data":{"type":"google_sheets","label":"Google Sheets (3)"}},{"id":"n4","type":"custom","position":{"x":880,"y":200},"data":{"type":"log_output","label":"Log Output (4)"}}]'::jsonb,
  '[{"id":"e1","source":"n1","target":"n2","sourceHandle":"output","targetHandle":"input"},{"id":"e2","source":"n2","target":"n3","sourceHandle":"output","targetHandle":"input"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"output","targetHandle":"input"}]'::jsonb,
  'Beginner',
  5,
  ARRAY['Commerce & Retail', 'manual-trigger', 'http-request', 'google-sheets', 'log-output'],
  true,
  false,
  COALESCE((SELECT user_id FROM public.user_roles WHERE role = 'admin' LIMIT 1), (SELECT id FROM auth.users ORDER BY created_at LIMIT 1))
);


-- Template #152
INSERT INTO public.templates (name, description, category, nodes, edges, difficulty, estimated_setup_time, tags, is_active, is_featured, created_by)
VALUES (
  'Healthcare: Deduplicate daily KPIs',
  'Starter workflow: Healthcare: Deduplicate daily KPIs. Linear flow (schedule → telegram → mongodb → log_output). Configure credentials and fields per node; extend in the canvas.',
  'Healthcare',
  '[{"id":"n1","type":"custom","position":{"x":100,"y":200},"data":{"type":"schedule","label":"Schedule (1)"}},{"id":"n2","type":"custom","position":{"x":360,"y":200},"data":{"type":"telegram","label":"Telegram (2)"}},{"id":"n3","type":"custom","position":{"x":620,"y":200},"data":{"type":"mongodb","label":"Mongodb (3)"}},{"id":"n4","type":"custom","position":{"x":880,"y":200},"data":{"type":"log_output","label":"Log Output (4)"}}]'::jsonb,
  '[{"id":"e1","source":"n1","target":"n2","sourceHandle":"output","targetHandle":"input"},{"id":"e2","source":"n2","target":"n3","sourceHandle":"output","targetHandle":"input"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"output","targetHandle":"input"}]'::jsonb,
  'Intermediate',
  6,
  ARRAY['Healthcare', 'schedule', 'telegram', 'mongodb', 'log-output'],
  true,
  false,
  COALESCE((SELECT user_id FROM public.user_roles WHERE role = 'admin' LIMIT 1), (SELECT id FROM auth.users ORDER BY created_at LIMIT 1))
);


-- Template #153
INSERT INTO public.templates (name, description, category, nodes, edges, difficulty, estimated_setup_time, tags, is_active, is_featured, created_by)
VALUES (
  'Finance & Accounting: Parse social mentions',
  'Starter workflow: Finance & Accounting: Parse social mentions. Linear flow (webhook → csv → email → log_output). Configure credentials and fields per node; extend in the canvas.',
  'Finance',
  '[{"id":"n1","type":"custom","position":{"x":100,"y":200},"data":{"type":"webhook","label":"Webhook (1)"}},{"id":"n2","type":"custom","position":{"x":360,"y":200},"data":{"type":"csv","label":"Csv (2)"}},{"id":"n3","type":"custom","position":{"x":620,"y":200},"data":{"type":"email","label":"Email (3)"}},{"id":"n4","type":"custom","position":{"x":880,"y":200},"data":{"type":"log_output","label":"Log Output (4)"}}]'::jsonb,
  '[{"id":"e1","source":"n1","target":"n2","sourceHandle":"output","targetHandle":"input"},{"id":"e2","source":"n2","target":"n3","sourceHandle":"output","targetHandle":"input"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"output","targetHandle":"input"}]'::jsonb,
  'Advanced',
  7,
  ARRAY['Finance', 'webhook', 'csv', 'email', 'log-output'],
  true,
  false,
  COALESCE((SELECT user_id FROM public.user_roles WHERE role = 'admin' LIMIT 1), (SELECT id FROM auth.users ORDER BY created_at LIMIT 1))
);


-- Template #154
INSERT INTO public.templates (name, description, category, nodes, edges, difficulty, estimated_setup_time, tags, is_active, is_featured, created_by)
VALUES (
  'HR & People: Monitor partner SLAs',
  'Starter workflow: HR & People: Monitor partner SLAs. Linear flow (form → notion → ai_agent → log_output). Configure credentials and fields per node; extend in the canvas.',
  'HR',
  '[{"id":"n1","type":"custom","position":{"x":100,"y":200},"data":{"type":"form","label":"Form (1)"}},{"id":"n2","type":"custom","position":{"x":360,"y":200},"data":{"type":"notion","label":"Notion (2)"}},{"id":"n3","type":"custom","position":{"x":620,"y":200},"data":{"type":"ai_agent","label":"Ai Agent (3)"}},{"id":"n4","type":"custom","position":{"x":880,"y":200},"data":{"type":"log_output","label":"Log Output (4)"}}]'::jsonb,
  '[{"id":"e1","source":"n1","target":"n2","sourceHandle":"output","targetHandle":"input"},{"id":"e2","source":"n2","target":"n3","sourceHandle":"output","targetHandle":"input"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"output","targetHandle":"input"}]'::jsonb,
  'Beginner',
  8,
  ARRAY['HR', 'form', 'notion', 'ai-agent', 'log-output'],
  true,
  false,
  COALESCE((SELECT user_id FROM public.user_roles WHERE role = 'admin' LIMIT 1), (SELECT id FROM auth.users ORDER BY created_at LIMIT 1))
);


-- Template #155
INSERT INTO public.templates (name, description, category, nodes, edges, difficulty, estimated_setup_time, tags, is_active, is_featured, created_by)
VALUES (
  'DevOps & SRE: Aggregate on-call incidents',
  'Starter workflow: DevOps & SRE: Aggregate on-call incidents. Linear flow (interval → ai_chat_model → text_formatter → log_output). Configure credentials and fields per node; extend in the canvas.',
  'Developer Tools',
  '[{"id":"n1","type":"custom","position":{"x":100,"y":200},"data":{"type":"interval","label":"Interval (1)"}},{"id":"n2","type":"custom","position":{"x":360,"y":200},"data":{"type":"ai_chat_model","label":"Ai Chat Model (2)"}},{"id":"n3","type":"custom","position":{"x":620,"y":200},"data":{"type":"text_formatter","label":"Text Formatter (3)"}},{"id":"n4","type":"custom","position":{"x":880,"y":200},"data":{"type":"log_output","label":"Log Output (4)"}}]'::jsonb,
  '[{"id":"e1","source":"n1","target":"n2","sourceHandle":"output","targetHandle":"input"},{"id":"e2","source":"n2","target":"n3","sourceHandle":"output","targetHandle":"input"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"output","targetHandle":"input"}]'::jsonb,
  'Intermediate',
  9,
  ARRAY['Developer Tools', 'interval', 'ai-chat-model', 'text-formatter', 'log-output'],
  true,
  false,
  COALESCE((SELECT user_id FROM public.user_roles WHERE role = 'admin' LIMIT 1), (SELECT id FROM auth.users ORDER BY created_at LIMIT 1))
);


-- Template #156
INSERT INTO public.templates (name, description, category, nodes, edges, difficulty, estimated_setup_time, tags, is_active, is_featured, created_by)
VALUES (
  'Marketing: Validate room bookings',
  'Starter workflow: Marketing: Validate room bookings. Linear flow (manual_trigger → postgresql → mysql → log_output). Configure credentials and fields per node; extend in the canvas.',
  'Marketing & Growth',
  '[{"id":"n1","type":"custom","position":{"x":100,"y":200},"data":{"type":"manual_trigger","label":"Manual Trigger (1)"}},{"id":"n2","type":"custom","position":{"x":360,"y":200},"data":{"type":"postgresql","label":"Postgresql (2)"}},{"id":"n3","type":"custom","position":{"x":620,"y":200},"data":{"type":"mysql","label":"Mysql (3)"}},{"id":"n4","type":"custom","position":{"x":880,"y":200},"data":{"type":"log_output","label":"Log Output (4)"}}]'::jsonb,
  '[{"id":"e1","source":"n1","target":"n2","sourceHandle":"output","targetHandle":"input"},{"id":"e2","source":"n2","target":"n3","sourceHandle":"output","targetHandle":"input"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"output","targetHandle":"input"}]'::jsonb,
  'Advanced',
  10,
  ARRAY['Marketing & Growth', 'manual-trigger', 'postgresql', 'mysql', 'log-output'],
  true,
  false,
  COALESCE((SELECT user_id FROM public.user_roles WHERE role = 'admin' LIMIT 1), (SELECT id FROM auth.users ORDER BY created_at LIMIT 1))
);


-- Template #157
INSERT INTO public.templates (name, description, category, nodes, edges, difficulty, estimated_setup_time, tags, is_active, is_featured, created_by)
VALUES (
  'Customer Support: Reconcile calendar holds',
  'Starter workflow: Customer Support: Reconcile calendar holds. Linear flow (schedule → ai_service → slack_message → log_output). Configure credentials and fields per node; extend in the canvas.',
  'Support',
  '[{"id":"n1","type":"custom","position":{"x":100,"y":200},"data":{"type":"schedule","label":"Schedule (1)"}},{"id":"n2","type":"custom","position":{"x":360,"y":200},"data":{"type":"ai_service","label":"Ai Service (2)"}},{"id":"n3","type":"custom","position":{"x":620,"y":200},"data":{"type":"slack_message","label":"Slack Message (3)"}},{"id":"n4","type":"custom","position":{"x":880,"y":200},"data":{"type":"log_output","label":"Log Output (4)"}}]'::jsonb,
  '[{"id":"e1","source":"n1","target":"n2","sourceHandle":"output","targetHandle":"input"},{"id":"e2","source":"n2","target":"n3","sourceHandle":"output","targetHandle":"input"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"output","targetHandle":"input"}]'::jsonb,
  'Beginner',
  11,
  ARRAY['Support', 'schedule', 'ai-service', 'slack-message', 'log-output'],
  true,
  false,
  COALESCE((SELECT user_id FROM public.user_roles WHERE role = 'admin' LIMIT 1), (SELECT id FROM auth.users ORDER BY created_at LIMIT 1))
);


-- Template #158
INSERT INTO public.templates (name, description, category, nodes, edges, difficulty, estimated_setup_time, tags, is_active, is_featured, created_by)
VALUES (
  'Education: Notify stakeholders about help-center articles',
  'Starter workflow: Education: Notify stakeholders about help-center articles. Linear flow (webhook → google_sheets → ollama → log_output). Configure credentials and fields per node; extend in the canvas.',
  'Education',
  '[{"id":"n1","type":"custom","position":{"x":100,"y":200},"data":{"type":"webhook","label":"Webhook (1)"}},{"id":"n2","type":"custom","position":{"x":360,"y":200},"data":{"type":"google_sheets","label":"Google Sheets (2)"}},{"id":"n3","type":"custom","position":{"x":620,"y":200},"data":{"type":"ollama","label":"Ollama (3)"}},{"id":"n4","type":"custom","position":{"x":880,"y":200},"data":{"type":"log_output","label":"Log Output (4)"}}]'::jsonb,
  '[{"id":"e1","source":"n1","target":"n2","sourceHandle":"output","targetHandle":"input"},{"id":"e2","source":"n2","target":"n3","sourceHandle":"output","targetHandle":"input"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"output","targetHandle":"input"}]'::jsonb,
  'Intermediate',
  12,
  ARRAY['Education', 'webhook', 'google-sheets', 'ollama', 'log-output'],
  true,
  false,
  COALESCE((SELECT user_id FROM public.user_roles WHERE role = 'admin' LIMIT 1), (SELECT id FROM auth.users ORDER BY created_at LIMIT 1))
);


-- Template #159
INSERT INTO public.templates (name, description, category, nodes, edges, difficulty, estimated_setup_time, tags, is_active, is_featured, created_by)
VALUES (
  'Real Estate: Tag and classify board packets',
  'Starter workflow: Real Estate: Tag and classify board packets. Linear flow (form → email → csv → log_output). Configure credentials and fields per node; extend in the canvas.',
  'Real Estate',
  '[{"id":"n1","type":"custom","position":{"x":100,"y":200},"data":{"type":"form","label":"Form (1)"}},{"id":"n2","type":"custom","position":{"x":360,"y":200},"data":{"type":"email","label":"Email (2)"}},{"id":"n3","type":"custom","position":{"x":620,"y":200},"data":{"type":"csv","label":"Csv (3)"}},{"id":"n4","type":"custom","position":{"x":880,"y":200},"data":{"type":"log_output","label":"Log Output (4)"}}]'::jsonb,
  '[{"id":"e1","source":"n1","target":"n2","sourceHandle":"output","targetHandle":"input"},{"id":"e2","source":"n2","target":"n3","sourceHandle":"output","targetHandle":"input"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"output","targetHandle":"input"}]'::jsonb,
  'Advanced',
  13,
  ARRAY['Real Estate', 'form', 'email', 'csv', 'log-output'],
  true,
  false,
  COALESCE((SELECT user_id FROM public.user_roles WHERE role = 'admin' LIMIT 1), (SELECT id FROM auth.users ORDER BY created_at LIMIT 1))
);


-- Template #160
INSERT INTO public.templates (name, description, category, nodes, edges, difficulty, estimated_setup_time, tags, is_active, is_featured, created_by)
VALUES (
  'Legal Ops: Handshake vendor bills',
  'Starter workflow: Legal Ops: Handshake vendor bills. Linear flow (interval → filter → google_drive → log_output). Configure credentials and fields per node; extend in the canvas.',
  'Legal',
  '[{"id":"n1","type":"custom","position":{"x":100,"y":200},"data":{"type":"interval","label":"Interval (1)"}},{"id":"n2","type":"custom","position":{"x":360,"y":200},"data":{"type":"filter","label":"Filter (2)"}},{"id":"n3","type":"custom","position":{"x":620,"y":200},"data":{"type":"google_drive","label":"Google Drive (3)"}},{"id":"n4","type":"custom","position":{"x":880,"y":200},"data":{"type":"log_output","label":"Log Output (4)"}}]'::jsonb,
  '[{"id":"e1","source":"n1","target":"n2","sourceHandle":"output","targetHandle":"input"},{"id":"e2","source":"n2","target":"n3","sourceHandle":"output","targetHandle":"input"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"output","targetHandle":"input"}]'::jsonb,
  'Beginner',
  14,
  ARRAY['Legal', 'interval', 'filter', 'google-drive', 'log-output'],
  true,
  false,
  COALESCE((SELECT user_id FROM public.user_roles WHERE role = 'admin' LIMIT 1), (SELECT id FROM auth.users ORDER BY created_at LIMIT 1))
);


-- Template #161
INSERT INTO public.templates (name, description, category, nodes, edges, difficulty, estimated_setup_time, tags, is_active, is_featured, created_by)
VALUES (
  'Manufacturing: Enrich prescription refills',
  'Starter workflow: Manufacturing: Enrich prescription refills. Linear flow (manual_trigger → hubspot → clickup → log_output). Configure credentials and fields per node; extend in the canvas.',
  'Operations',
  '[{"id":"n1","type":"custom","position":{"x":100,"y":200},"data":{"type":"manual_trigger","label":"Manual Trigger (1)"}},{"id":"n2","type":"custom","position":{"x":360,"y":200},"data":{"type":"hubspot","label":"Hubspot (2)"}},{"id":"n3","type":"custom","position":{"x":620,"y":200},"data":{"type":"clickup","label":"Clickup (3)"}},{"id":"n4","type":"custom","position":{"x":880,"y":200},"data":{"type":"log_output","label":"Log Output (4)"}}]'::jsonb,
  '[{"id":"e1","source":"n1","target":"n2","sourceHandle":"output","targetHandle":"input"},{"id":"e2","source":"n2","target":"n3","sourceHandle":"output","targetHandle":"input"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"output","targetHandle":"input"}]'::jsonb,
  'Intermediate',
  15,
  ARRAY['Operations', 'manual-trigger', 'hubspot', 'clickup', 'log-output'],
  true,
  false,
  COALESCE((SELECT user_id FROM public.user_roles WHERE role = 'admin' LIMIT 1), (SELECT id FROM auth.users ORDER BY created_at LIMIT 1))
);


-- Template #162
INSERT INTO public.templates (name, description, category, nodes, edges, difficulty, estimated_setup_time, tags, is_active, is_featured, created_by)
VALUES (
  'Nonprofit: Redact inventory deltas',
  'Starter workflow: Nonprofit: Redact inventory deltas. Linear flow (schedule → set_variable → linkedin → log_output). Configure credentials and fields per node; extend in the canvas.',
  'Nonprofit',
  '[{"id":"n1","type":"custom","position":{"x":100,"y":200},"data":{"type":"schedule","label":"Schedule (1)"}},{"id":"n2","type":"custom","position":{"x":360,"y":200},"data":{"type":"set_variable","label":"Set Variable (2)"}},{"id":"n3","type":"custom","position":{"x":620,"y":200},"data":{"type":"linkedin","label":"Linkedin (3)"}},{"id":"n4","type":"custom","position":{"x":880,"y":200},"data":{"type":"log_output","label":"Log Output (4)"}}]'::jsonb,
  '[{"id":"e1","source":"n1","target":"n2","sourceHandle":"output","targetHandle":"input"},{"id":"e2","source":"n2","target":"n3","sourceHandle":"output","targetHandle":"input"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"output","targetHandle":"input"}]'::jsonb,
  'Advanced',
  16,
  ARRAY['Nonprofit', 'schedule', 'set-variable', 'linkedin', 'log-output'],
  true,
  true,
  COALESCE((SELECT user_id FROM public.user_roles WHERE role = 'admin' LIMIT 1), (SELECT id FROM auth.users ORDER BY created_at LIMIT 1))
);


-- Template #163
INSERT INTO public.templates (name, description, category, nodes, edges, difficulty, estimated_setup_time, tags, is_active, is_featured, created_by)
VALUES (
  'Media & Publishing: Extract metrics from warehouse scans',
  'Starter workflow: Media & Publishing: Extract metrics from warehouse scans. Linear flow (webhook → mysql → javascript → log_output). Configure credentials and fields per node; extend in the canvas.',
  'Media',
  '[{"id":"n1","type":"custom","position":{"x":100,"y":200},"data":{"type":"webhook","label":"Webhook (1)"}},{"id":"n2","type":"custom","position":{"x":360,"y":200},"data":{"type":"mysql","label":"Mysql (2)"}},{"id":"n3","type":"custom","position":{"x":620,"y":200},"data":{"type":"javascript","label":"Javascript (3)"}},{"id":"n4","type":"custom","position":{"x":880,"y":200},"data":{"type":"log_output","label":"Log Output (4)"}}]'::jsonb,
  '[{"id":"e1","source":"n1","target":"n2","sourceHandle":"output","targetHandle":"input"},{"id":"e2","source":"n2","target":"n3","sourceHandle":"output","targetHandle":"input"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"output","targetHandle":"input"}]'::jsonb,
  'Beginner',
  17,
  ARRAY['Media', 'webhook', 'mysql', 'javascript', 'log-output'],
  true,
  false,
  COALESCE((SELECT user_id FROM public.user_roles WHERE role = 'admin' LIMIT 1), (SELECT id FROM auth.users ORDER BY created_at LIMIT 1))
);


-- Template #164
INSERT INTO public.templates (name, description, category, nodes, edges, difficulty, estimated_setup_time, tags, is_active, is_featured, created_by)
VALUES (
  'Logistics: Triage NPS feedback',
  'Starter workflow: Logistics: Triage NPS feedback. Linear flow (form → ollama → google_sheets → log_output). Configure credentials and fields per node; extend in the canvas.',
  'Logistics',
  '[{"id":"n1","type":"custom","position":{"x":100,"y":200},"data":{"type":"form","label":"Form (1)"}},{"id":"n2","type":"custom","position":{"x":360,"y":200},"data":{"type":"ollama","label":"Ollama (2)"}},{"id":"n3","type":"custom","position":{"x":620,"y":200},"data":{"type":"google_sheets","label":"Google Sheets (3)"}},{"id":"n4","type":"custom","position":{"x":880,"y":200},"data":{"type":"log_output","label":"Log Output (4)"}}]'::jsonb,
  '[{"id":"e1","source":"n1","target":"n2","sourceHandle":"output","targetHandle":"input"},{"id":"e2","source":"n2","target":"n3","sourceHandle":"output","targetHandle":"input"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"output","targetHandle":"input"}]'::jsonb,
  'Intermediate',
  18,
  ARRAY['Logistics', 'form', 'ollama', 'google-sheets', 'log-output'],
  true,
  false,
  COALESCE((SELECT user_id FROM public.user_roles WHERE role = 'admin' LIMIT 1), (SELECT id FROM auth.users ORDER BY created_at LIMIT 1))
);


-- Template #165
INSERT INTO public.templates (name, description, category, nodes, edges, difficulty, estimated_setup_time, tags, is_active, is_featured, created_by)
VALUES (
  'Hospitality: Transform subscription renewals',
  'Starter workflow: Hospitality: Transform subscription renewals. Linear flow (interval → google_gmail → airtable → log_output). Configure credentials and fields per node; extend in the canvas.',
  'Hospitality',
  '[{"id":"n1","type":"custom","position":{"x":100,"y":200},"data":{"type":"interval","label":"Interval (1)"}},{"id":"n2","type":"custom","position":{"x":360,"y":200},"data":{"type":"google_gmail","label":"Google Gmail (2)"}},{"id":"n3","type":"custom","position":{"x":620,"y":200},"data":{"type":"airtable","label":"Airtable (3)"}},{"id":"n4","type":"custom","position":{"x":880,"y":200},"data":{"type":"log_output","label":"Log Output (4)"}}]'::jsonb,
  '[{"id":"e1","source":"n1","target":"n2","sourceHandle":"output","targetHandle":"input"},{"id":"e2","source":"n2","target":"n3","sourceHandle":"output","targetHandle":"input"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"output","targetHandle":"input"}]'::jsonb,
  'Advanced',
  19,
  ARRAY['Hospitality', 'interval', 'google-gmail', 'airtable', 'log-output'],
  true,
  false,
  COALESCE((SELECT user_id FROM public.user_roles WHERE role = 'admin' LIMIT 1), (SELECT id FROM auth.users ORDER BY created_at LIMIT 1))
);


-- Template #166
INSERT INTO public.templates (name, description, category, nodes, edges, difficulty, estimated_setup_time, tags, is_active, is_featured, created_by)
VALUES (
  'SaaS Product: Back up IoT heartbeats',
  'Starter workflow: SaaS Product: Back up IoT heartbeats. Linear flow (manual_trigger → outlook → twitter → log_output). Configure credentials and fields per node; extend in the canvas.',
  'Product',
  '[{"id":"n1","type":"custom","position":{"x":100,"y":200},"data":{"type":"manual_trigger","label":"Manual Trigger (1)"}},{"id":"n2","type":"custom","position":{"x":360,"y":200},"data":{"type":"outlook","label":"Outlook (2)"}},{"id":"n3","type":"custom","position":{"x":620,"y":200},"data":{"type":"twitter","label":"Twitter (3)"}},{"id":"n4","type":"custom","position":{"x":880,"y":200},"data":{"type":"log_output","label":"Log Output (4)"}}]'::jsonb,
  '[{"id":"e1","source":"n1","target":"n2","sourceHandle":"output","targetHandle":"input"},{"id":"e2","source":"n2","target":"n3","sourceHandle":"output","targetHandle":"input"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"output","targetHandle":"input"}]'::jsonb,
  'Beginner',
  20,
  ARRAY['Product', 'manual-trigger', 'outlook', 'twitter', 'log-output'],
  true,
  false,
  COALESCE((SELECT user_id FROM public.user_roles WHERE role = 'admin' LIMIT 1), (SELECT id FROM auth.users ORDER BY created_at LIMIT 1))
);


-- Template #167
INSERT INTO public.templates (name, description, category, nodes, edges, difficulty, estimated_setup_time, tags, is_active, is_featured, created_by)
VALUES (
  'IT Service Desk: Sync invoice lines',
  'Starter workflow: IT Service Desk: Sync invoice lines. Linear flow (schedule → text_formatter → ai_chat_model → log_output). Configure credentials and fields per node; extend in the canvas.',
  'IT',
  '[{"id":"n1","type":"custom","position":{"x":100,"y":200},"data":{"type":"schedule","label":"Schedule (1)"}},{"id":"n2","type":"custom","position":{"x":360,"y":200},"data":{"type":"text_formatter","label":"Text Formatter (2)"}},{"id":"n3","type":"custom","position":{"x":620,"y":200},"data":{"type":"ai_chat_model","label":"Ai Chat Model (3)"}},{"id":"n4","type":"custom","position":{"x":880,"y":200},"data":{"type":"log_output","label":"Log Output (4)"}}]'::jsonb,
  '[{"id":"e1","source":"n1","target":"n2","sourceHandle":"output","targetHandle":"input"},{"id":"e2","source":"n2","target":"n3","sourceHandle":"output","targetHandle":"input"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"output","targetHandle":"input"}]'::jsonb,
  'Intermediate',
  21,
  ARRAY['IT', 'schedule', 'text-formatter', 'ai-chat-model', 'log-output'],
  true,
  false,
  COALESCE((SELECT user_id FROM public.user_roles WHERE role = 'admin' LIMIT 1), (SELECT id FROM auth.users ORDER BY created_at LIMIT 1))
);


-- Template #168
INSERT INTO public.templates (name, description, category, nodes, edges, difficulty, estimated_setup_time, tags, is_active, is_featured, created_by)
VALUES (
  'Sales Ops: Score policy attestations',
  'Starter workflow: Sales Ops: Score policy attestations. Linear flow (webhook → clickup → function → log_output). Configure credentials and fields per node; extend in the canvas.',
  'CRM & Sales',
  '[{"id":"n1","type":"custom","position":{"x":100,"y":200},"data":{"type":"webhook","label":"Webhook (1)"}},{"id":"n2","type":"custom","position":{"x":360,"y":200},"data":{"type":"clickup","label":"Clickup (2)"}},{"id":"n3","type":"custom","position":{"x":620,"y":200},"data":{"type":"function","label":"Function (3)"}},{"id":"n4","type":"custom","position":{"x":880,"y":200},"data":{"type":"log_output","label":"Log Output (4)"}}]'::jsonb,
  '[{"id":"e1","source":"n1","target":"n2","sourceHandle":"output","targetHandle":"input"},{"id":"e2","source":"n2","target":"n3","sourceHandle":"output","targetHandle":"input"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"output","targetHandle":"input"}]'::jsonb,
  'Advanced',
  22,
  ARRAY['CRM & Sales', 'webhook', 'clickup', 'function', 'log-output'],
  true,
  false,
  COALESCE((SELECT user_id FROM public.user_roles WHERE role = 'admin' LIMIT 1), (SELECT id FROM auth.users ORDER BY created_at LIMIT 1))
);


-- Template #169
INSERT INTO public.templates (name, description, category, nodes, edges, difficulty, estimated_setup_time, tags, is_active, is_featured, created_by)
VALUES (
  'Data Analytics: Normalize new leads',
  'Starter workflow: Data Analytics: Normalize new leads. Linear flow (form → javascript → mysql → log_output). Configure credentials and fields per node; extend in the canvas.',
  'Data & BI',
  '[{"id":"n1","type":"custom","position":{"x":100,"y":200},"data":{"type":"form","label":"Form (1)"}},{"id":"n2","type":"custom","position":{"x":360,"y":200},"data":{"type":"javascript","label":"Javascript (2)"}},{"id":"n3","type":"custom","position":{"x":620,"y":200},"data":{"type":"mysql","label":"Mysql (3)"}},{"id":"n4","type":"custom","position":{"x":880,"y":200},"data":{"type":"log_output","label":"Log Output (4)"}}]'::jsonb,
  '[{"id":"e1","source":"n1","target":"n2","sourceHandle":"output","targetHandle":"input"},{"id":"e2","source":"n2","target":"n3","sourceHandle":"output","targetHandle":"input"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"output","targetHandle":"input"}]'::jsonb,
  'Beginner',
  23,
  ARRAY['Data & BI', 'form', 'javascript', 'mysql', 'log-output'],
  true,
  false,
  COALESCE((SELECT user_id FROM public.user_roles WHERE role = 'admin' LIMIT 1), (SELECT id FROM auth.users ORDER BY created_at LIMIT 1))
);


-- Template #170
INSERT INTO public.templates (name, description, category, nodes, edges, difficulty, estimated_setup_time, tags, is_active, is_featured, created_by)
VALUES (
  'Security & GRC: Route expense receipts',
  'Starter workflow: Security & GRC: Route expense receipts. Linear flow (interval → mongodb → telegram → log_output). Configure credentials and fields per node; extend in the canvas.',
  'Security',
  '[{"id":"n1","type":"custom","position":{"x":100,"y":200},"data":{"type":"interval","label":"Interval (1)"}},{"id":"n2","type":"custom","position":{"x":360,"y":200},"data":{"type":"mongodb","label":"Mongodb (2)"}},{"id":"n3","type":"custom","position":{"x":620,"y":200},"data":{"type":"telegram","label":"Telegram (3)"}},{"id":"n4","type":"custom","position":{"x":880,"y":200},"data":{"type":"log_output","label":"Log Output (4)"}}]'::jsonb,
  '[{"id":"e1","source":"n1","target":"n2","sourceHandle":"output","targetHandle":"input"},{"id":"e2","source":"n2","target":"n3","sourceHandle":"output","targetHandle":"input"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"output","targetHandle":"input"}]'::jsonb,
  'Intermediate',
  24,
  ARRAY['Security', 'interval', 'mongodb', 'telegram', 'log-output'],
  true,
  false,
  COALESCE((SELECT user_id FROM public.user_roles WHERE role = 'admin' LIMIT 1), (SELECT id FROM auth.users ORDER BY created_at LIMIT 1))
);


-- Template #171
INSERT INTO public.templates (name, description, category, nodes, edges, difficulty, estimated_setup_time, tags, is_active, is_featured, created_by)
VALUES (
  'Construction: Watermark API error bursts',
  'Starter workflow: Construction: Watermark API error bursts. Linear flow (manual_trigger → openai_gpt → ai_agent → log_output). Configure credentials and fields per node; extend in the canvas.',
  'Construction',
  '[{"id":"n1","type":"custom","position":{"x":100,"y":200},"data":{"type":"manual_trigger","label":"Manual Trigger (1)"}},{"id":"n2","type":"custom","position":{"x":360,"y":200},"data":{"type":"openai_gpt","label":"Openai Gpt (2)"}},{"id":"n3","type":"custom","position":{"x":620,"y":200},"data":{"type":"ai_agent","label":"Ai Agent (3)"}},{"id":"n4","type":"custom","position":{"x":880,"y":200},"data":{"type":"log_output","label":"Log Output (4)"}}]'::jsonb,
  '[{"id":"e1","source":"n1","target":"n2","sourceHandle":"output","targetHandle":"input"},{"id":"e2","source":"n2","target":"n3","sourceHandle":"output","targetHandle":"input"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"output","targetHandle":"input"}]'::jsonb,
  'Advanced',
  25,
  ARRAY['Construction', 'manual-trigger', 'openai-gpt', 'ai-agent', 'log-output'],
  true,
  false,
  COALESCE((SELECT user_id FROM public.user_roles WHERE role = 'admin' LIMIT 1), (SELECT id FROM auth.users ORDER BY created_at LIMIT 1))
);


-- Template #172
INSERT INTO public.templates (name, description, category, nodes, edges, difficulty, estimated_setup_time, tags, is_active, is_featured, created_by)
VALUES (
  'Agriculture: Schedule contract PDFs',
  'Starter workflow: Agriculture: Schedule contract PDFs. Linear flow (schedule → google_drive → filter → log_output). Configure credentials and fields per node; extend in the canvas.',
  'Agriculture',
  '[{"id":"n1","type":"custom","position":{"x":100,"y":200},"data":{"type":"schedule","label":"Schedule (1)"}},{"id":"n2","type":"custom","position":{"x":360,"y":200},"data":{"type":"google_drive","label":"Google Drive (2)"}},{"id":"n3","type":"custom","position":{"x":620,"y":200},"data":{"type":"filter","label":"Filter (3)"}},{"id":"n4","type":"custom","position":{"x":880,"y":200},"data":{"type":"log_output","label":"Log Output (4)"}}]'::jsonb,
  '[{"id":"e1","source":"n1","target":"n2","sourceHandle":"output","targetHandle":"input"},{"id":"e2","source":"n2","target":"n3","sourceHandle":"output","targetHandle":"input"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"output","targetHandle":"input"}]'::jsonb,
  'Beginner',
  26,
  ARRAY['Agriculture', 'schedule', 'google-drive', 'filter', 'log-output'],
  true,
  false,
  COALESCE((SELECT user_id FROM public.user_roles WHERE role = 'admin' LIMIT 1), (SELECT id FROM auth.users ORDER BY created_at LIMIT 1))
);


-- Template #173
INSERT INTO public.templates (name, description, category, nodes, edges, difficulty, estimated_setup_time, tags, is_active, is_featured, created_by)
VALUES (
  'Energy: Publish loan applications',
  'Starter workflow: Energy: Publish loan applications. Linear flow (webhook → twitter → google_calendar → log_output). Configure credentials and fields per node; extend in the canvas.',
  'Energy',
  '[{"id":"n1","type":"custom","position":{"x":100,"y":200},"data":{"type":"webhook","label":"Webhook (1)"}},{"id":"n2","type":"custom","position":{"x":360,"y":200},"data":{"type":"twitter","label":"Twitter (2)"}},{"id":"n3","type":"custom","position":{"x":620,"y":200},"data":{"type":"google_calendar","label":"Google Calendar (3)"}},{"id":"n4","type":"custom","position":{"x":880,"y":200},"data":{"type":"log_output","label":"Log Output (4)"}}]'::jsonb,
  '[{"id":"e1","source":"n1","target":"n2","sourceHandle":"output","targetHandle":"input"},{"id":"e2","source":"n2","target":"n3","sourceHandle":"output","targetHandle":"input"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"output","targetHandle":"input"}]'::jsonb,
  'Intermediate',
  27,
  ARRAY['Energy', 'webhook', 'twitter', 'google-calendar', 'log-output'],
  true,
  false,
  COALESCE((SELECT user_id FROM public.user_roles WHERE role = 'admin' LIMIT 1), (SELECT id FROM auth.users ORDER BY created_at LIMIT 1))
);


-- Template #174
INSERT INTO public.templates (name, description, category, nodes, edges, difficulty, estimated_setup_time, tags, is_active, is_featured, created_by)
VALUES (
  'Telecom: Archive ticket updates',
  'Starter workflow: Telecom: Archive ticket updates. Linear flow (form → function → clickup → log_output). Configure credentials and fields per node; extend in the canvas.',
  'Telecom',
  '[{"id":"n1","type":"custom","position":{"x":100,"y":200},"data":{"type":"form","label":"Form (1)"}},{"id":"n2","type":"custom","position":{"x":360,"y":200},"data":{"type":"function","label":"Function (2)"}},{"id":"n3","type":"custom","position":{"x":620,"y":200},"data":{"type":"clickup","label":"Clickup (3)"}},{"id":"n4","type":"custom","position":{"x":880,"y":200},"data":{"type":"log_output","label":"Log Output (4)"}}]'::jsonb,
  '[{"id":"e1","source":"n1","target":"n2","sourceHandle":"output","targetHandle":"input"},{"id":"e2","source":"n2","target":"n3","sourceHandle":"output","targetHandle":"input"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"output","targetHandle":"input"}]'::jsonb,
  'Advanced',
  28,
  ARRAY['Telecom', 'form', 'function', 'clickup', 'log-output'],
  true,
  false,
  COALESCE((SELECT user_id FROM public.user_roles WHERE role = 'admin' LIMIT 1), (SELECT id FROM auth.users ORDER BY created_at LIMIT 1))
);


-- Template #175
INSERT INTO public.templates (name, description, category, nodes, edges, difficulty, estimated_setup_time, tags, is_active, is_featured, created_by)
VALUES (
  'Gov & Public Sector: Summarize candidate applications',
  'Starter workflow: Gov & Public Sector: Summarize candidate applications. Linear flow (interval → slack_message → ai_service → log_output). Configure credentials and fields per node; extend in the canvas.',
  'Public Sector',
  '[{"id":"n1","type":"custom","position":{"x":100,"y":200},"data":{"type":"interval","label":"Interval (1)"}},{"id":"n2","type":"custom","position":{"x":360,"y":200},"data":{"type":"slack_message","label":"Slack Message (2)"}},{"id":"n3","type":"custom","position":{"x":620,"y":200},"data":{"type":"ai_service","label":"Ai Service (3)"}},{"id":"n4","type":"custom","position":{"x":880,"y":200},"data":{"type":"log_output","label":"Log Output (4)"}}]'::jsonb,
  '[{"id":"e1","source":"n1","target":"n2","sourceHandle":"output","targetHandle":"input"},{"id":"e2","source":"n2","target":"n3","sourceHandle":"output","targetHandle":"input"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"output","targetHandle":"input"}]'::jsonb,
  'Beginner',
  29,
  ARRAY['Public Sector', 'interval', 'slack-message', 'ai-service', 'log-output'],
  true,
  false,
  COALESCE((SELECT user_id FROM public.user_roles WHERE role = 'admin' LIMIT 1), (SELECT id FROM auth.users ORDER BY created_at LIMIT 1))
);


-- Template #176
INSERT INTO public.templates (name, description, category, nodes, edges, difficulty, estimated_setup_time, tags, is_active, is_featured, created_by)
VALUES (
  'E-commerce: Automate schema migrations',
  'Starter workflow: E-commerce: Automate schema migrations. Linear flow (manual_trigger → json_parser → csv → log_output). Configure credentials and fields per node; extend in the canvas.',
  'Commerce & Retail',
  '[{"id":"n1","type":"custom","position":{"x":100,"y":200},"data":{"type":"manual_trigger","label":"Manual Trigger (1)"}},{"id":"n2","type":"custom","position":{"x":360,"y":200},"data":{"type":"json_parser","label":"Json Parser (2)"}},{"id":"n3","type":"custom","position":{"x":620,"y":200},"data":{"type":"csv","label":"Csv (3)"}},{"id":"n4","type":"custom","position":{"x":880,"y":200},"data":{"type":"log_output","label":"Log Output (4)"}}]'::jsonb,
  '[{"id":"e1","source":"n1","target":"n2","sourceHandle":"output","targetHandle":"input"},{"id":"e2","source":"n2","target":"n3","sourceHandle":"output","targetHandle":"input"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"output","targetHandle":"input"}]'::jsonb,
  'Intermediate',
  5,
  ARRAY['Commerce & Retail', 'manual-trigger', 'json-parser', 'csv', 'log-output'],
  true,
  false,
  COALESCE((SELECT user_id FROM public.user_roles WHERE role = 'admin' LIMIT 1), (SELECT id FROM auth.users ORDER BY created_at LIMIT 1))
);


-- Template #177
INSERT INTO public.templates (name, description, category, nodes, edges, difficulty, estimated_setup_time, tags, is_active, is_featured, created_by)
VALUES (
  'Healthcare: Deduplicate survey results',
  'Starter workflow: Healthcare: Deduplicate survey results. Linear flow (schedule → airtable → google_gmail → log_output). Configure credentials and fields per node; extend in the canvas.',
  'Healthcare',
  '[{"id":"n1","type":"custom","position":{"x":100,"y":200},"data":{"type":"schedule","label":"Schedule (1)"}},{"id":"n2","type":"custom","position":{"x":360,"y":200},"data":{"type":"airtable","label":"Airtable (2)"}},{"id":"n3","type":"custom","position":{"x":620,"y":200},"data":{"type":"google_gmail","label":"Google Gmail (3)"}},{"id":"n4","type":"custom","position":{"x":880,"y":200},"data":{"type":"log_output","label":"Log Output (4)"}}]'::jsonb,
  '[{"id":"e1","source":"n1","target":"n2","sourceHandle":"output","targetHandle":"input"},{"id":"e2","source":"n2","target":"n3","sourceHandle":"output","targetHandle":"input"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"output","targetHandle":"input"}]'::jsonb,
  'Advanced',
  6,
  ARRAY['Healthcare', 'schedule', 'airtable', 'google-gmail', 'log-output'],
  true,
  false,
  COALESCE((SELECT user_id FROM public.user_roles WHERE role = 'admin' LIMIT 1), (SELECT id FROM auth.users ORDER BY created_at LIMIT 1))
);


-- Template #178
INSERT INTO public.templates (name, description, category, nodes, edges, difficulty, estimated_setup_time, tags, is_active, is_featured, created_by)
VALUES (
  'Finance & Accounting: Parse grant submissions',
  'Starter workflow: Finance & Accounting: Parse grant submissions. Linear flow (webhook → ai_agent → notion → log_output). Configure credentials and fields per node; extend in the canvas.',
  'Finance',
  '[{"id":"n1","type":"custom","position":{"x":100,"y":200},"data":{"type":"webhook","label":"Webhook (1)"}},{"id":"n2","type":"custom","position":{"x":360,"y":200},"data":{"type":"ai_agent","label":"Ai Agent (2)"}},{"id":"n3","type":"custom","position":{"x":620,"y":200},"data":{"type":"notion","label":"Notion (3)"}},{"id":"n4","type":"custom","position":{"x":880,"y":200},"data":{"type":"log_output","label":"Log Output (4)"}}]'::jsonb,
  '[{"id":"e1","source":"n1","target":"n2","sourceHandle":"output","targetHandle":"input"},{"id":"e2","source":"n2","target":"n3","sourceHandle":"output","targetHandle":"input"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"output","targetHandle":"input"}]'::jsonb,
  'Beginner',
  7,
  ARRAY['Finance', 'webhook', 'ai-agent', 'notion', 'log-output'],
  true,
  false,
  COALESCE((SELECT user_id FROM public.user_roles WHERE role = 'admin' LIMIT 1), (SELECT id FROM auth.users ORDER BY created_at LIMIT 1))
);


-- Template #179
INSERT INTO public.templates (name, description, category, nodes, edges, difficulty, estimated_setup_time, tags, is_active, is_featured, created_by)
VALUES (
  'HR & People: Monitor CSV uploads',
  'Starter workflow: HR & People: Monitor CSV uploads. Linear flow (form → google_calendar → twitter → log_output). Configure credentials and fields per node; extend in the canvas.',
  'HR',
  '[{"id":"n1","type":"custom","position":{"x":100,"y":200},"data":{"type":"form","label":"Form (1)"}},{"id":"n2","type":"custom","position":{"x":360,"y":200},"data":{"type":"google_calendar","label":"Google Calendar (2)"}},{"id":"n3","type":"custom","position":{"x":620,"y":200},"data":{"type":"twitter","label":"Twitter (3)"}},{"id":"n4","type":"custom","position":{"x":880,"y":200},"data":{"type":"log_output","label":"Log Output (4)"}}]'::jsonb,
  '[{"id":"e1","source":"n1","target":"n2","sourceHandle":"output","targetHandle":"input"},{"id":"e2","source":"n2","target":"n3","sourceHandle":"output","targetHandle":"input"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"output","targetHandle":"input"}]'::jsonb,
  'Intermediate',
  8,
  ARRAY['HR', 'form', 'google-calendar', 'twitter', 'log-output'],
  true,
  false,
  COALESCE((SELECT user_id FROM public.user_roles WHERE role = 'admin' LIMIT 1), (SELECT id FROM auth.users ORDER BY created_at LIMIT 1))
);


-- Template #180
INSERT INTO public.templates (name, description, category, nodes, edges, difficulty, estimated_setup_time, tags, is_active, is_featured, created_by)
VALUES (
  'DevOps & SRE: Aggregate patient intake forms',
  'Starter workflow: DevOps & SRE: Aggregate patient intake forms. Linear flow (interval → linkedin → set_variable → log_output). Configure credentials and fields per node; extend in the canvas.',
  'Developer Tools',
  '[{"id":"n1","type":"custom","position":{"x":100,"y":200},"data":{"type":"interval","label":"Interval (1)"}},{"id":"n2","type":"custom","position":{"x":360,"y":200},"data":{"type":"linkedin","label":"Linkedin (2)"}},{"id":"n3","type":"custom","position":{"x":620,"y":200},"data":{"type":"set_variable","label":"Set Variable (3)"}},{"id":"n4","type":"custom","position":{"x":880,"y":200},"data":{"type":"log_output","label":"Log Output (4)"}}]'::jsonb,
  '[{"id":"e1","source":"n1","target":"n2","sourceHandle":"output","targetHandle":"input"},{"id":"e2","source":"n2","target":"n3","sourceHandle":"output","targetHandle":"input"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"output","targetHandle":"input"}]'::jsonb,
  'Advanced',
  9,
  ARRAY['Developer Tools', 'interval', 'linkedin', 'set-variable', 'log-output'],
  true,
  false,
  COALESCE((SELECT user_id FROM public.user_roles WHERE role = 'admin' LIMIT 1), (SELECT id FROM auth.users ORDER BY created_at LIMIT 1))
);


-- Template #181
INSERT INTO public.templates (name, description, category, nodes, edges, difficulty, estimated_setup_time, tags, is_active, is_featured, created_by)
VALUES (
  'Marketing: Validate backup manifests',
  'Starter workflow: Marketing: Validate backup manifests. Linear flow (manual_trigger → http_request → google_sheets → log_output). Configure credentials and fields per node; extend in the canvas.',
  'Marketing & Growth',
  '[{"id":"n1","type":"custom","position":{"x":100,"y":200},"data":{"type":"manual_trigger","label":"Manual Trigger (1)"}},{"id":"n2","type":"custom","position":{"x":360,"y":200},"data":{"type":"http_request","label":"Http Request (2)"}},{"id":"n3","type":"custom","position":{"x":620,"y":200},"data":{"type":"google_sheets","label":"Google Sheets (3)"}},{"id":"n4","type":"custom","position":{"x":880,"y":200},"data":{"type":"log_output","label":"Log Output (4)"}}]'::jsonb,
  '[{"id":"e1","source":"n1","target":"n2","sourceHandle":"output","targetHandle":"input"},{"id":"e2","source":"n2","target":"n3","sourceHandle":"output","targetHandle":"input"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"output","targetHandle":"input"}]'::jsonb,
  'Beginner',
  10,
  ARRAY['Marketing & Growth', 'manual-trigger', 'http-request', 'google-sheets', 'log-output'],
  true,
  false,
  COALESCE((SELECT user_id FROM public.user_roles WHERE role = 'admin' LIMIT 1), (SELECT id FROM auth.users ORDER BY created_at LIMIT 1))
);


-- Template #182
INSERT INTO public.templates (name, description, category, nodes, edges, difficulty, estimated_setup_time, tags, is_active, is_featured, created_by)
VALUES (
  'Customer Support: Reconcile experiment logs',
  'Starter workflow: Customer Support: Reconcile experiment logs. Linear flow (schedule → telegram → mongodb → log_output). Configure credentials and fields per node; extend in the canvas.',
  'Support',
  '[{"id":"n1","type":"custom","position":{"x":100,"y":200},"data":{"type":"schedule","label":"Schedule (1)"}},{"id":"n2","type":"custom","position":{"x":360,"y":200},"data":{"type":"telegram","label":"Telegram (2)"}},{"id":"n3","type":"custom","position":{"x":620,"y":200},"data":{"type":"mongodb","label":"Mongodb (3)"}},{"id":"n4","type":"custom","position":{"x":880,"y":200},"data":{"type":"log_output","label":"Log Output (4)"}}]'::jsonb,
  '[{"id":"e1","source":"n1","target":"n2","sourceHandle":"output","targetHandle":"input"},{"id":"e2","source":"n2","target":"n3","sourceHandle":"output","targetHandle":"input"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"output","targetHandle":"input"}]'::jsonb,
  'Intermediate',
  11,
  ARRAY['Support', 'schedule', 'telegram', 'mongodb', 'log-output'],
  true,
  false,
  COALESCE((SELECT user_id FROM public.user_roles WHERE role = 'admin' LIMIT 1), (SELECT id FROM auth.users ORDER BY created_at LIMIT 1))
);


-- Template #183
INSERT INTO public.templates (name, description, category, nodes, edges, difficulty, estimated_setup_time, tags, is_active, is_featured, created_by)
VALUES (
  'Education: Notify stakeholders about court filings',
  'Starter workflow: Education: Notify stakeholders about court filings. Linear flow (webhook → csv → email → log_output). Configure credentials and fields per node; extend in the canvas.',
  'Education',
  '[{"id":"n1","type":"custom","position":{"x":100,"y":200},"data":{"type":"webhook","label":"Webhook (1)"}},{"id":"n2","type":"custom","position":{"x":360,"y":200},"data":{"type":"csv","label":"Csv (2)"}},{"id":"n3","type":"custom","position":{"x":620,"y":200},"data":{"type":"email","label":"Email (3)"}},{"id":"n4","type":"custom","position":{"x":880,"y":200},"data":{"type":"log_output","label":"Log Output (4)"}}]'::jsonb,
  '[{"id":"e1","source":"n1","target":"n2","sourceHandle":"output","targetHandle":"input"},{"id":"e2","source":"n2","target":"n3","sourceHandle":"output","targetHandle":"input"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"output","targetHandle":"input"}]'::jsonb,
  'Advanced',
  12,
  ARRAY['Education', 'webhook', 'csv', 'email', 'log-output'],
  true,
  false,
  COALESCE((SELECT user_id FROM public.user_roles WHERE role = 'admin' LIMIT 1), (SELECT id FROM auth.users ORDER BY created_at LIMIT 1))
);


-- Template #184
INSERT INTO public.templates (name, description, category, nodes, edges, difficulty, estimated_setup_time, tags, is_active, is_featured, created_by)
VALUES (
  'Real Estate: Tag and classify form responses',
  'Starter workflow: Real Estate: Tag and classify form responses. Linear flow (form → notion → ai_agent → log_output). Configure credentials and fields per node; extend in the canvas.',
  'Real Estate',
  '[{"id":"n1","type":"custom","position":{"x":100,"y":200},"data":{"type":"form","label":"Form (1)"}},{"id":"n2","type":"custom","position":{"x":360,"y":200},"data":{"type":"notion","label":"Notion (2)"}},{"id":"n3","type":"custom","position":{"x":620,"y":200},"data":{"type":"ai_agent","label":"Ai Agent (3)"}},{"id":"n4","type":"custom","position":{"x":880,"y":200},"data":{"type":"log_output","label":"Log Output (4)"}}]'::jsonb,
  '[{"id":"e1","source":"n1","target":"n2","sourceHandle":"output","targetHandle":"input"},{"id":"e2","source":"n2","target":"n3","sourceHandle":"output","targetHandle":"input"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"output","targetHandle":"input"}]'::jsonb,
  'Beginner',
  13,
  ARRAY['Real Estate', 'form', 'notion', 'ai-agent', 'log-output'],
  true,
  false,
  COALESCE((SELECT user_id FROM public.user_roles WHERE role = 'admin' LIMIT 1), (SELECT id FROM auth.users ORDER BY created_at LIMIT 1))
);


-- Template #185
INSERT INTO public.templates (name, description, category, nodes, edges, difficulty, estimated_setup_time, tags, is_active, is_featured, created_by)
VALUES (
  'Legal Ops: Handshake sensor readings',
  'Starter workflow: Legal Ops: Handshake sensor readings. Linear flow (interval → ai_chat_model → text_formatter → log_output). Configure credentials and fields per node; extend in the canvas.',
  'Legal',
  '[{"id":"n1","type":"custom","position":{"x":100,"y":200},"data":{"type":"interval","label":"Interval (1)"}},{"id":"n2","type":"custom","position":{"x":360,"y":200},"data":{"type":"ai_chat_model","label":"Ai Chat Model (2)"}},{"id":"n3","type":"custom","position":{"x":620,"y":200},"data":{"type":"text_formatter","label":"Text Formatter (3)"}},{"id":"n4","type":"custom","position":{"x":880,"y":200},"data":{"type":"log_output","label":"Log Output (4)"}}]'::jsonb,
  '[{"id":"e1","source":"n1","target":"n2","sourceHandle":"output","targetHandle":"input"},{"id":"e2","source":"n2","target":"n3","sourceHandle":"output","targetHandle":"input"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"output","targetHandle":"input"}]'::jsonb,
  'Intermediate',
  14,
  ARRAY['Legal', 'interval', 'ai-chat-model', 'text-formatter', 'log-output'],
  true,
  true,
  COALESCE((SELECT user_id FROM public.user_roles WHERE role = 'admin' LIMIT 1), (SELECT id FROM auth.users ORDER BY created_at LIMIT 1))
);


-- Template #186
INSERT INTO public.templates (name, description, category, nodes, edges, difficulty, estimated_setup_time, tags, is_active, is_featured, created_by)
VALUES (
  'Manufacturing: Enrich compliance exports',
  'Starter workflow: Manufacturing: Enrich compliance exports. Linear flow (manual_trigger → postgresql → mysql → log_output). Configure credentials and fields per node; extend in the canvas.',
  'Operations',
  '[{"id":"n1","type":"custom","position":{"x":100,"y":200},"data":{"type":"manual_trigger","label":"Manual Trigger (1)"}},{"id":"n2","type":"custom","position":{"x":360,"y":200},"data":{"type":"postgresql","label":"Postgresql (2)"}},{"id":"n3","type":"custom","position":{"x":620,"y":200},"data":{"type":"mysql","label":"Mysql (3)"}},{"id":"n4","type":"custom","position":{"x":880,"y":200},"data":{"type":"log_output","label":"Log Output (4)"}}]'::jsonb,
  '[{"id":"e1","source":"n1","target":"n2","sourceHandle":"output","targetHandle":"input"},{"id":"e2","source":"n2","target":"n3","sourceHandle":"output","targetHandle":"input"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"output","targetHandle":"input"}]'::jsonb,
  'Advanced',
  15,
  ARRAY['Operations', 'manual-trigger', 'postgresql', 'mysql', 'log-output'],
  true,
  false,
  COALESCE((SELECT user_id FROM public.user_roles WHERE role = 'admin' LIMIT 1), (SELECT id FROM auth.users ORDER BY created_at LIMIT 1))
);


-- Template #187
INSERT INTO public.templates (name, description, category, nodes, edges, difficulty, estimated_setup_time, tags, is_active, is_featured, created_by)
VALUES (
  'Nonprofit: Redact feature flags',
  'Starter workflow: Nonprofit: Redact feature flags. Linear flow (schedule → ai_service → slack_message → log_output). Configure credentials and fields per node; extend in the canvas.',
  'Nonprofit',
  '[{"id":"n1","type":"custom","position":{"x":100,"y":200},"data":{"type":"schedule","label":"Schedule (1)"}},{"id":"n2","type":"custom","position":{"x":360,"y":200},"data":{"type":"ai_service","label":"Ai Service (2)"}},{"id":"n3","type":"custom","position":{"x":620,"y":200},"data":{"type":"slack_message","label":"Slack Message (3)"}},{"id":"n4","type":"custom","position":{"x":880,"y":200},"data":{"type":"log_output","label":"Log Output (4)"}}]'::jsonb,
  '[{"id":"e1","source":"n1","target":"n2","sourceHandle":"output","targetHandle":"input"},{"id":"e2","source":"n2","target":"n3","sourceHandle":"output","targetHandle":"input"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"output","targetHandle":"input"}]'::jsonb,
  'Beginner',
  16,
  ARRAY['Nonprofit', 'schedule', 'ai-service', 'slack-message', 'log-output'],
  true,
  false,
  COALESCE((SELECT user_id FROM public.user_roles WHERE role = 'admin' LIMIT 1), (SELECT id FROM auth.users ORDER BY created_at LIMIT 1))
);


-- Template #188
INSERT INTO public.templates (name, description, category, nodes, edges, difficulty, estimated_setup_time, tags, is_active, is_featured, created_by)
VALUES (
  'Media & Publishing: Extract metrics from asset depreciations',
  'Starter workflow: Media & Publishing: Extract metrics from asset depreciations. Linear flow (webhook → google_sheets → ollama → log_output). Configure credentials and fields per node; extend in the canvas.',
  'Media',
  '[{"id":"n1","type":"custom","position":{"x":100,"y":200},"data":{"type":"webhook","label":"Webhook (1)"}},{"id":"n2","type":"custom","position":{"x":360,"y":200},"data":{"type":"google_sheets","label":"Google Sheets (2)"}},{"id":"n3","type":"custom","position":{"x":620,"y":200},"data":{"type":"ollama","label":"Ollama (3)"}},{"id":"n4","type":"custom","position":{"x":880,"y":200},"data":{"type":"log_output","label":"Log Output (4)"}}]'::jsonb,
  '[{"id":"e1","source":"n1","target":"n2","sourceHandle":"output","targetHandle":"input"},{"id":"e2","source":"n2","target":"n3","sourceHandle":"output","targetHandle":"input"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"output","targetHandle":"input"}]'::jsonb,
  'Intermediate',
  17,
  ARRAY['Media', 'webhook', 'google-sheets', 'ollama', 'log-output'],
  true,
  false,
  COALESCE((SELECT user_id FROM public.user_roles WHERE role = 'admin' LIMIT 1), (SELECT id FROM auth.users ORDER BY created_at LIMIT 1))
);


-- Template #189
INSERT INTO public.templates (name, description, category, nodes, edges, difficulty, estimated_setup_time, tags, is_active, is_featured, created_by)
VALUES (
  'Logistics: Triage webhook payloads',
  'Starter workflow: Logistics: Triage webhook payloads. Linear flow (form → email → csv → log_output). Configure credentials and fields per node; extend in the canvas.',
  'Logistics',
  '[{"id":"n1","type":"custom","position":{"x":100,"y":200},"data":{"type":"form","label":"Form (1)"}},{"id":"n2","type":"custom","position":{"x":360,"y":200},"data":{"type":"email","label":"Email (2)"}},{"id":"n3","type":"custom","position":{"x":620,"y":200},"data":{"type":"csv","label":"Csv (3)"}},{"id":"n4","type":"custom","position":{"x":880,"y":200},"data":{"type":"log_output","label":"Log Output (4)"}}]'::jsonb,
  '[{"id":"e1","source":"n1","target":"n2","sourceHandle":"output","targetHandle":"input"},{"id":"e2","source":"n2","target":"n3","sourceHandle":"output","targetHandle":"input"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"output","targetHandle":"input"}]'::jsonb,
  'Advanced',
  18,
  ARRAY['Logistics', 'form', 'email', 'csv', 'log-output'],
  true,
  false,
  COALESCE((SELECT user_id FROM public.user_roles WHERE role = 'admin' LIMIT 1), (SELECT id FROM auth.users ORDER BY created_at LIMIT 1))
);


-- Template #190
INSERT INTO public.templates (name, description, category, nodes, edges, difficulty, estimated_setup_time, tags, is_active, is_featured, created_by)
VALUES (
  'Hospitality: Transform shipment events',
  'Starter workflow: Hospitality: Transform shipment events. Linear flow (interval → filter → google_drive → log_output). Configure credentials and fields per node; extend in the canvas.',
  'Hospitality',
  '[{"id":"n1","type":"custom","position":{"x":100,"y":200},"data":{"type":"interval","label":"Interval (1)"}},{"id":"n2","type":"custom","position":{"x":360,"y":200},"data":{"type":"filter","label":"Filter (2)"}},{"id":"n3","type":"custom","position":{"x":620,"y":200},"data":{"type":"google_drive","label":"Google Drive (3)"}},{"id":"n4","type":"custom","position":{"x":880,"y":200},"data":{"type":"log_output","label":"Log Output (4)"}}]'::jsonb,
  '[{"id":"e1","source":"n1","target":"n2","sourceHandle":"output","targetHandle":"input"},{"id":"e2","source":"n2","target":"n3","sourceHandle":"output","targetHandle":"input"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"output","targetHandle":"input"}]'::jsonb,
  'Beginner',
  19,
  ARRAY['Hospitality', 'interval', 'filter', 'google-drive', 'log-output'],
  true,
  false,
  COALESCE((SELECT user_id FROM public.user_roles WHERE role = 'admin' LIMIT 1), (SELECT id FROM auth.users ORDER BY created_at LIMIT 1))
);


-- Template #191
INSERT INTO public.templates (name, description, category, nodes, edges, difficulty, estimated_setup_time, tags, is_active, is_featured, created_by)
VALUES (
  'SaaS Product: Back up security findings',
  'Starter workflow: SaaS Product: Back up security findings. Linear flow (manual_trigger → hubspot → clickup → log_output). Configure credentials and fields per node; extend in the canvas.',
  'Product',
  '[{"id":"n1","type":"custom","position":{"x":100,"y":200},"data":{"type":"manual_trigger","label":"Manual Trigger (1)"}},{"id":"n2","type":"custom","position":{"x":360,"y":200},"data":{"type":"hubspot","label":"Hubspot (2)"}},{"id":"n3","type":"custom","position":{"x":620,"y":200},"data":{"type":"clickup","label":"Clickup (3)"}},{"id":"n4","type":"custom","position":{"x":880,"y":200},"data":{"type":"log_output","label":"Log Output (4)"}}]'::jsonb,
  '[{"id":"e1","source":"n1","target":"n2","sourceHandle":"output","targetHandle":"input"},{"id":"e2","source":"n2","target":"n3","sourceHandle":"output","targetHandle":"input"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"output","targetHandle":"input"}]'::jsonb,
  'Intermediate',
  20,
  ARRAY['Product', 'manual-trigger', 'hubspot', 'clickup', 'log-output'],
  true,
  false,
  COALESCE((SELECT user_id FROM public.user_roles WHERE role = 'admin' LIMIT 1), (SELECT id FROM auth.users ORDER BY created_at LIMIT 1))
);


-- Template #192
INSERT INTO public.templates (name, description, category, nodes, edges, difficulty, estimated_setup_time, tags, is_active, is_featured, created_by)
VALUES (
  'IT Service Desk: Sync release notes',
  'Starter workflow: IT Service Desk: Sync release notes. Linear flow (schedule → set_variable → linkedin → log_output). Configure credentials and fields per node; extend in the canvas.',
  'IT',
  '[{"id":"n1","type":"custom","position":{"x":100,"y":200},"data":{"type":"schedule","label":"Schedule (1)"}},{"id":"n2","type":"custom","position":{"x":360,"y":200},"data":{"type":"set_variable","label":"Set Variable (2)"}},{"id":"n3","type":"custom","position":{"x":620,"y":200},"data":{"type":"linkedin","label":"Linkedin (3)"}},{"id":"n4","type":"custom","position":{"x":880,"y":200},"data":{"type":"log_output","label":"Log Output (4)"}}]'::jsonb,
  '[{"id":"e1","source":"n1","target":"n2","sourceHandle":"output","targetHandle":"input"},{"id":"e2","source":"n2","target":"n3","sourceHandle":"output","targetHandle":"input"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"output","targetHandle":"input"}]'::jsonb,
  'Advanced',
  21,
  ARRAY['IT', 'schedule', 'set-variable', 'linkedin', 'log-output'],
  true,
  false,
  COALESCE((SELECT user_id FROM public.user_roles WHERE role = 'admin' LIMIT 1), (SELECT id FROM auth.users ORDER BY created_at LIMIT 1))
);


-- Template #193
INSERT INTO public.templates (name, description, category, nodes, edges, difficulty, estimated_setup_time, tags, is_active, is_featured, created_by)
VALUES (
  'Sales Ops: Score course enrollments',
  'Starter workflow: Sales Ops: Score course enrollments. Linear flow (webhook → mysql → javascript → log_output). Configure credentials and fields per node; extend in the canvas.',
  'CRM & Sales',
  '[{"id":"n1","type":"custom","position":{"x":100,"y":200},"data":{"type":"webhook","label":"Webhook (1)"}},{"id":"n2","type":"custom","position":{"x":360,"y":200},"data":{"type":"mysql","label":"Mysql (2)"}},{"id":"n3","type":"custom","position":{"x":620,"y":200},"data":{"type":"javascript","label":"Javascript (3)"}},{"id":"n4","type":"custom","position":{"x":880,"y":200},"data":{"type":"log_output","label":"Log Output (4)"}}]'::jsonb,
  '[{"id":"e1","source":"n1","target":"n2","sourceHandle":"output","targetHandle":"input"},{"id":"e2","source":"n2","target":"n3","sourceHandle":"output","targetHandle":"input"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"output","targetHandle":"input"}]'::jsonb,
  'Beginner',
  22,
  ARRAY['CRM & Sales', 'webhook', 'mysql', 'javascript', 'log-output'],
  true,
  false,
  COALESCE((SELECT user_id FROM public.user_roles WHERE role = 'admin' LIMIT 1), (SELECT id FROM auth.users ORDER BY created_at LIMIT 1))
);


-- Template #194
INSERT INTO public.templates (name, description, category, nodes, edges, difficulty, estimated_setup_time, tags, is_active, is_featured, created_by)
VALUES (
  'Data Analytics: Normalize daily KPIs',
  'Starter workflow: Data Analytics: Normalize daily KPIs. Linear flow (form → ollama → google_sheets → log_output). Configure credentials and fields per node; extend in the canvas.',
  'Data & BI',
  '[{"id":"n1","type":"custom","position":{"x":100,"y":200},"data":{"type":"form","label":"Form (1)"}},{"id":"n2","type":"custom","position":{"x":360,"y":200},"data":{"type":"ollama","label":"Ollama (2)"}},{"id":"n3","type":"custom","position":{"x":620,"y":200},"data":{"type":"google_sheets","label":"Google Sheets (3)"}},{"id":"n4","type":"custom","position":{"x":880,"y":200},"data":{"type":"log_output","label":"Log Output (4)"}}]'::jsonb,
  '[{"id":"e1","source":"n1","target":"n2","sourceHandle":"output","targetHandle":"input"},{"id":"e2","source":"n2","target":"n3","sourceHandle":"output","targetHandle":"input"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"output","targetHandle":"input"}]'::jsonb,
  'Intermediate',
  23,
  ARRAY['Data & BI', 'form', 'ollama', 'google-sheets', 'log-output'],
  true,
  false,
  COALESCE((SELECT user_id FROM public.user_roles WHERE role = 'admin' LIMIT 1), (SELECT id FROM auth.users ORDER BY created_at LIMIT 1))
);


-- Template #195
INSERT INTO public.templates (name, description, category, nodes, edges, difficulty, estimated_setup_time, tags, is_active, is_featured, created_by)
VALUES (
  'Security & GRC: Route social mentions',
  'Starter workflow: Security & GRC: Route social mentions. Linear flow (interval → google_gmail → airtable → log_output). Configure credentials and fields per node; extend in the canvas.',
  'Security',
  '[{"id":"n1","type":"custom","position":{"x":100,"y":200},"data":{"type":"interval","label":"Interval (1)"}},{"id":"n2","type":"custom","position":{"x":360,"y":200},"data":{"type":"google_gmail","label":"Google Gmail (2)"}},{"id":"n3","type":"custom","position":{"x":620,"y":200},"data":{"type":"airtable","label":"Airtable (3)"}},{"id":"n4","type":"custom","position":{"x":880,"y":200},"data":{"type":"log_output","label":"Log Output (4)"}}]'::jsonb,
  '[{"id":"e1","source":"n1","target":"n2","sourceHandle":"output","targetHandle":"input"},{"id":"e2","source":"n2","target":"n3","sourceHandle":"output","targetHandle":"input"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"output","targetHandle":"input"}]'::jsonb,
  'Advanced',
  24,
  ARRAY['Security', 'interval', 'google-gmail', 'airtable', 'log-output'],
  true,
  false,
  COALESCE((SELECT user_id FROM public.user_roles WHERE role = 'admin' LIMIT 1), (SELECT id FROM auth.users ORDER BY created_at LIMIT 1))
);


-- Template #196
INSERT INTO public.templates (name, description, category, nodes, edges, difficulty, estimated_setup_time, tags, is_active, is_featured, created_by)
VALUES (
  'Construction: Watermark partner SLAs',
  'Starter workflow: Construction: Watermark partner SLAs. Linear flow (manual_trigger → outlook → twitter → log_output). Configure credentials and fields per node; extend in the canvas.',
  'Construction',
  '[{"id":"n1","type":"custom","position":{"x":100,"y":200},"data":{"type":"manual_trigger","label":"Manual Trigger (1)"}},{"id":"n2","type":"custom","position":{"x":360,"y":200},"data":{"type":"outlook","label":"Outlook (2)"}},{"id":"n3","type":"custom","position":{"x":620,"y":200},"data":{"type":"twitter","label":"Twitter (3)"}},{"id":"n4","type":"custom","position":{"x":880,"y":200},"data":{"type":"log_output","label":"Log Output (4)"}}]'::jsonb,
  '[{"id":"e1","source":"n1","target":"n2","sourceHandle":"output","targetHandle":"input"},{"id":"e2","source":"n2","target":"n3","sourceHandle":"output","targetHandle":"input"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"output","targetHandle":"input"}]'::jsonb,
  'Beginner',
  25,
  ARRAY['Construction', 'manual-trigger', 'outlook', 'twitter', 'log-output'],
  true,
  false,
  COALESCE((SELECT user_id FROM public.user_roles WHERE role = 'admin' LIMIT 1), (SELECT id FROM auth.users ORDER BY created_at LIMIT 1))
);


-- Template #197
INSERT INTO public.templates (name, description, category, nodes, edges, difficulty, estimated_setup_time, tags, is_active, is_featured, created_by)
VALUES (
  'Agriculture: Schedule on-call incidents',
  'Starter workflow: Agriculture: Schedule on-call incidents. Linear flow (schedule → text_formatter → ai_chat_model → log_output). Configure credentials and fields per node; extend in the canvas.',
  'Agriculture',
  '[{"id":"n1","type":"custom","position":{"x":100,"y":200},"data":{"type":"schedule","label":"Schedule (1)"}},{"id":"n2","type":"custom","position":{"x":360,"y":200},"data":{"type":"text_formatter","label":"Text Formatter (2)"}},{"id":"n3","type":"custom","position":{"x":620,"y":200},"data":{"type":"ai_chat_model","label":"Ai Chat Model (3)"}},{"id":"n4","type":"custom","position":{"x":880,"y":200},"data":{"type":"log_output","label":"Log Output (4)"}}]'::jsonb,
  '[{"id":"e1","source":"n1","target":"n2","sourceHandle":"output","targetHandle":"input"},{"id":"e2","source":"n2","target":"n3","sourceHandle":"output","targetHandle":"input"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"output","targetHandle":"input"}]'::jsonb,
  'Intermediate',
  26,
  ARRAY['Agriculture', 'schedule', 'text-formatter', 'ai-chat-model', 'log-output'],
  true,
  false,
  COALESCE((SELECT user_id FROM public.user_roles WHERE role = 'admin' LIMIT 1), (SELECT id FROM auth.users ORDER BY created_at LIMIT 1))
);


-- Template #198
INSERT INTO public.templates (name, description, category, nodes, edges, difficulty, estimated_setup_time, tags, is_active, is_featured, created_by)
VALUES (
  'Energy: Publish room bookings',
  'Starter workflow: Energy: Publish room bookings. Linear flow (webhook → clickup → function → log_output). Configure credentials and fields per node; extend in the canvas.',
  'Energy',
  '[{"id":"n1","type":"custom","position":{"x":100,"y":200},"data":{"type":"webhook","label":"Webhook (1)"}},{"id":"n2","type":"custom","position":{"x":360,"y":200},"data":{"type":"clickup","label":"Clickup (2)"}},{"id":"n3","type":"custom","position":{"x":620,"y":200},"data":{"type":"function","label":"Function (3)"}},{"id":"n4","type":"custom","position":{"x":880,"y":200},"data":{"type":"log_output","label":"Log Output (4)"}}]'::jsonb,
  '[{"id":"e1","source":"n1","target":"n2","sourceHandle":"output","targetHandle":"input"},{"id":"e2","source":"n2","target":"n3","sourceHandle":"output","targetHandle":"input"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"output","targetHandle":"input"}]'::jsonb,
  'Advanced',
  27,
  ARRAY['Energy', 'webhook', 'clickup', 'function', 'log-output'],
  true,
  false,
  COALESCE((SELECT user_id FROM public.user_roles WHERE role = 'admin' LIMIT 1), (SELECT id FROM auth.users ORDER BY created_at LIMIT 1))
);


-- Template #199
INSERT INTO public.templates (name, description, category, nodes, edges, difficulty, estimated_setup_time, tags, is_active, is_featured, created_by)
VALUES (
  'Telecom: Archive calendar holds',
  'Starter workflow: Telecom: Archive calendar holds. Linear flow (form → javascript → mysql → log_output). Configure credentials and fields per node; extend in the canvas.',
  'Telecom',
  '[{"id":"n1","type":"custom","position":{"x":100,"y":200},"data":{"type":"form","label":"Form (1)"}},{"id":"n2","type":"custom","position":{"x":360,"y":200},"data":{"type":"javascript","label":"Javascript (2)"}},{"id":"n3","type":"custom","position":{"x":620,"y":200},"data":{"type":"mysql","label":"Mysql (3)"}},{"id":"n4","type":"custom","position":{"x":880,"y":200},"data":{"type":"log_output","label":"Log Output (4)"}}]'::jsonb,
  '[{"id":"e1","source":"n1","target":"n2","sourceHandle":"output","targetHandle":"input"},{"id":"e2","source":"n2","target":"n3","sourceHandle":"output","targetHandle":"input"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"output","targetHandle":"input"}]'::jsonb,
  'Beginner',
  28,
  ARRAY['Telecom', 'form', 'javascript', 'mysql', 'log-output'],
  true,
  false,
  COALESCE((SELECT user_id FROM public.user_roles WHERE role = 'admin' LIMIT 1), (SELECT id FROM auth.users ORDER BY created_at LIMIT 1))
);


-- Template #200
INSERT INTO public.templates (name, description, category, nodes, edges, difficulty, estimated_setup_time, tags, is_active, is_featured, created_by)
VALUES (
  'Gov & Public Sector: Summarize help-center articles',
  'Starter workflow: Gov & Public Sector: Summarize help-center articles. Linear flow (interval → mongodb → telegram → log_output). Configure credentials and fields per node; extend in the canvas.',
  'Public Sector',
  '[{"id":"n1","type":"custom","position":{"x":100,"y":200},"data":{"type":"interval","label":"Interval (1)"}},{"id":"n2","type":"custom","position":{"x":360,"y":200},"data":{"type":"mongodb","label":"Mongodb (2)"}},{"id":"n3","type":"custom","position":{"x":620,"y":200},"data":{"type":"telegram","label":"Telegram (3)"}},{"id":"n4","type":"custom","position":{"x":880,"y":200},"data":{"type":"log_output","label":"Log Output (4)"}}]'::jsonb,
  '[{"id":"e1","source":"n1","target":"n2","sourceHandle":"output","targetHandle":"input"},{"id":"e2","source":"n2","target":"n3","sourceHandle":"output","targetHandle":"input"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"output","targetHandle":"input"}]'::jsonb,
  'Intermediate',
  29,
  ARRAY['Public Sector', 'interval', 'mongodb', 'telegram', 'log-output'],
  true,
  false,
  COALESCE((SELECT user_id FROM public.user_roles WHERE role = 'admin' LIMIT 1), (SELECT id FROM auth.users ORDER BY created_at LIMIT 1))
);


COMMIT;
