-- =============================================================================
-- Registry-aligned template seed batch 5 of 10
-- Templates 201–250 of 500
-- Generated by ctrl_checks/scripts/generate-workflow-templates-sql.ts
-- Run 00_delete_all_templates.sql first if replacing the full catalog.
-- =============================================================================

BEGIN;

-- Template #201
INSERT INTO public.templates (name, description, category, nodes, edges, difficulty, estimated_setup_time, tags, is_active, is_featured, created_by)
VALUES (
  'E-commerce: Automate board packets',
  'Starter workflow: E-commerce: Automate board packets. Linear flow (manual_trigger → openai_gpt → ai_agent → log_output). Configure credentials and fields per node; extend in the canvas.',
  'Commerce & Retail',
  '[{"id":"n1","type":"custom","position":{"x":100,"y":200},"data":{"type":"manual_trigger","label":"Manual Trigger (1)"}},{"id":"n2","type":"custom","position":{"x":360,"y":200},"data":{"type":"openai_gpt","label":"Openai Gpt (2)"}},{"id":"n3","type":"custom","position":{"x":620,"y":200},"data":{"type":"ai_agent","label":"Ai Agent (3)"}},{"id":"n4","type":"custom","position":{"x":880,"y":200},"data":{"type":"log_output","label":"Log Output (4)"}}]'::jsonb,
  '[{"id":"e1","source":"n1","target":"n2","sourceHandle":"output","targetHandle":"input"},{"id":"e2","source":"n2","target":"n3","sourceHandle":"output","targetHandle":"input"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"output","targetHandle":"input"}]'::jsonb,
  'Advanced',
  5,
  ARRAY['Commerce & Retail', 'manual-trigger', 'openai-gpt', 'ai-agent', 'log-output'],
  true,
  false,
  COALESCE((SELECT user_id FROM public.user_roles WHERE role = 'admin' LIMIT 1), (SELECT id FROM auth.users ORDER BY created_at LIMIT 1))
);


-- Template #202
INSERT INTO public.templates (name, description, category, nodes, edges, difficulty, estimated_setup_time, tags, is_active, is_featured, created_by)
VALUES (
  'Healthcare: Deduplicate vendor bills',
  'Starter workflow: Healthcare: Deduplicate vendor bills. Linear flow (schedule → google_drive → filter → log_output). Configure credentials and fields per node; extend in the canvas.',
  'Healthcare',
  '[{"id":"n1","type":"custom","position":{"x":100,"y":200},"data":{"type":"schedule","label":"Schedule (1)"}},{"id":"n2","type":"custom","position":{"x":360,"y":200},"data":{"type":"google_drive","label":"Google Drive (2)"}},{"id":"n3","type":"custom","position":{"x":620,"y":200},"data":{"type":"filter","label":"Filter (3)"}},{"id":"n4","type":"custom","position":{"x":880,"y":200},"data":{"type":"log_output","label":"Log Output (4)"}}]'::jsonb,
  '[{"id":"e1","source":"n1","target":"n2","sourceHandle":"output","targetHandle":"input"},{"id":"e2","source":"n2","target":"n3","sourceHandle":"output","targetHandle":"input"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"output","targetHandle":"input"}]'::jsonb,
  'Beginner',
  6,
  ARRAY['Healthcare', 'schedule', 'google-drive', 'filter', 'log-output'],
  true,
  false,
  COALESCE((SELECT user_id FROM public.user_roles WHERE role = 'admin' LIMIT 1), (SELECT id FROM auth.users ORDER BY created_at LIMIT 1))
);


-- Template #203
INSERT INTO public.templates (name, description, category, nodes, edges, difficulty, estimated_setup_time, tags, is_active, is_featured, created_by)
VALUES (
  'Finance & Accounting: Parse prescription refills',
  'Starter workflow: Finance & Accounting: Parse prescription refills. Linear flow (webhook → twitter → google_calendar → log_output). Configure credentials and fields per node; extend in the canvas.',
  'Finance',
  '[{"id":"n1","type":"custom","position":{"x":100,"y":200},"data":{"type":"webhook","label":"Webhook (1)"}},{"id":"n2","type":"custom","position":{"x":360,"y":200},"data":{"type":"twitter","label":"Twitter (2)"}},{"id":"n3","type":"custom","position":{"x":620,"y":200},"data":{"type":"google_calendar","label":"Google Calendar (3)"}},{"id":"n4","type":"custom","position":{"x":880,"y":200},"data":{"type":"log_output","label":"Log Output (4)"}}]'::jsonb,
  '[{"id":"e1","source":"n1","target":"n2","sourceHandle":"output","targetHandle":"input"},{"id":"e2","source":"n2","target":"n3","sourceHandle":"output","targetHandle":"input"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"output","targetHandle":"input"}]'::jsonb,
  'Intermediate',
  7,
  ARRAY['Finance', 'webhook', 'twitter', 'google-calendar', 'log-output'],
  true,
  false,
  COALESCE((SELECT user_id FROM public.user_roles WHERE role = 'admin' LIMIT 1), (SELECT id FROM auth.users ORDER BY created_at LIMIT 1))
);


-- Template #204
INSERT INTO public.templates (name, description, category, nodes, edges, difficulty, estimated_setup_time, tags, is_active, is_featured, created_by)
VALUES (
  'HR & People: Monitor inventory deltas',
  'Starter workflow: HR & People: Monitor inventory deltas. Linear flow (form → function → clickup → log_output). Configure credentials and fields per node; extend in the canvas.',
  'HR',
  '[{"id":"n1","type":"custom","position":{"x":100,"y":200},"data":{"type":"form","label":"Form (1)"}},{"id":"n2","type":"custom","position":{"x":360,"y":200},"data":{"type":"function","label":"Function (2)"}},{"id":"n3","type":"custom","position":{"x":620,"y":200},"data":{"type":"clickup","label":"Clickup (3)"}},{"id":"n4","type":"custom","position":{"x":880,"y":200},"data":{"type":"log_output","label":"Log Output (4)"}}]'::jsonb,
  '[{"id":"e1","source":"n1","target":"n2","sourceHandle":"output","targetHandle":"input"},{"id":"e2","source":"n2","target":"n3","sourceHandle":"output","targetHandle":"input"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"output","targetHandle":"input"}]'::jsonb,
  'Advanced',
  8,
  ARRAY['HR', 'form', 'function', 'clickup', 'log-output'],
  true,
  false,
  COALESCE((SELECT user_id FROM public.user_roles WHERE role = 'admin' LIMIT 1), (SELECT id FROM auth.users ORDER BY created_at LIMIT 1))
);


-- Template #205
INSERT INTO public.templates (name, description, category, nodes, edges, difficulty, estimated_setup_time, tags, is_active, is_featured, created_by)
VALUES (
  'DevOps & SRE: Aggregate warehouse scans',
  'Starter workflow: DevOps & SRE: Aggregate warehouse scans. Linear flow (interval → slack_message → ai_service → log_output). Configure credentials and fields per node; extend in the canvas.',
  'Developer Tools',
  '[{"id":"n1","type":"custom","position":{"x":100,"y":200},"data":{"type":"interval","label":"Interval (1)"}},{"id":"n2","type":"custom","position":{"x":360,"y":200},"data":{"type":"slack_message","label":"Slack Message (2)"}},{"id":"n3","type":"custom","position":{"x":620,"y":200},"data":{"type":"ai_service","label":"Ai Service (3)"}},{"id":"n4","type":"custom","position":{"x":880,"y":200},"data":{"type":"log_output","label":"Log Output (4)"}}]'::jsonb,
  '[{"id":"e1","source":"n1","target":"n2","sourceHandle":"output","targetHandle":"input"},{"id":"e2","source":"n2","target":"n3","sourceHandle":"output","targetHandle":"input"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"output","targetHandle":"input"}]'::jsonb,
  'Beginner',
  9,
  ARRAY['Developer Tools', 'interval', 'slack-message', 'ai-service', 'log-output'],
  true,
  false,
  COALESCE((SELECT user_id FROM public.user_roles WHERE role = 'admin' LIMIT 1), (SELECT id FROM auth.users ORDER BY created_at LIMIT 1))
);


-- Template #206
INSERT INTO public.templates (name, description, category, nodes, edges, difficulty, estimated_setup_time, tags, is_active, is_featured, created_by)
VALUES (
  'Marketing: Validate NPS feedback',
  'Starter workflow: Marketing: Validate NPS feedback. Linear flow (manual_trigger → json_parser → csv → log_output). Configure credentials and fields per node; extend in the canvas.',
  'Marketing & Growth',
  '[{"id":"n1","type":"custom","position":{"x":100,"y":200},"data":{"type":"manual_trigger","label":"Manual Trigger (1)"}},{"id":"n2","type":"custom","position":{"x":360,"y":200},"data":{"type":"json_parser","label":"Json Parser (2)"}},{"id":"n3","type":"custom","position":{"x":620,"y":200},"data":{"type":"csv","label":"Csv (3)"}},{"id":"n4","type":"custom","position":{"x":880,"y":200},"data":{"type":"log_output","label":"Log Output (4)"}}]'::jsonb,
  '[{"id":"e1","source":"n1","target":"n2","sourceHandle":"output","targetHandle":"input"},{"id":"e2","source":"n2","target":"n3","sourceHandle":"output","targetHandle":"input"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"output","targetHandle":"input"}]'::jsonb,
  'Intermediate',
  10,
  ARRAY['Marketing & Growth', 'manual-trigger', 'json-parser', 'csv', 'log-output'],
  true,
  false,
  COALESCE((SELECT user_id FROM public.user_roles WHERE role = 'admin' LIMIT 1), (SELECT id FROM auth.users ORDER BY created_at LIMIT 1))
);


-- Template #207
INSERT INTO public.templates (name, description, category, nodes, edges, difficulty, estimated_setup_time, tags, is_active, is_featured, created_by)
VALUES (
  'Customer Support: Reconcile subscription renewals',
  'Starter workflow: Customer Support: Reconcile subscription renewals. Linear flow (schedule → airtable → google_gmail → log_output). Configure credentials and fields per node; extend in the canvas.',
  'Support',
  '[{"id":"n1","type":"custom","position":{"x":100,"y":200},"data":{"type":"schedule","label":"Schedule (1)"}},{"id":"n2","type":"custom","position":{"x":360,"y":200},"data":{"type":"airtable","label":"Airtable (2)"}},{"id":"n3","type":"custom","position":{"x":620,"y":200},"data":{"type":"google_gmail","label":"Google Gmail (3)"}},{"id":"n4","type":"custom","position":{"x":880,"y":200},"data":{"type":"log_output","label":"Log Output (4)"}}]'::jsonb,
  '[{"id":"e1","source":"n1","target":"n2","sourceHandle":"output","targetHandle":"input"},{"id":"e2","source":"n2","target":"n3","sourceHandle":"output","targetHandle":"input"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"output","targetHandle":"input"}]'::jsonb,
  'Advanced',
  11,
  ARRAY['Support', 'schedule', 'airtable', 'google-gmail', 'log-output'],
  true,
  false,
  COALESCE((SELECT user_id FROM public.user_roles WHERE role = 'admin' LIMIT 1), (SELECT id FROM auth.users ORDER BY created_at LIMIT 1))
);


-- Template #208
INSERT INTO public.templates (name, description, category, nodes, edges, difficulty, estimated_setup_time, tags, is_active, is_featured, created_by)
VALUES (
  'Education: Notify stakeholders about IoT heartbeats',
  'Starter workflow: Education: Notify stakeholders about IoT heartbeats. Linear flow (webhook → ai_agent → notion → log_output). Configure credentials and fields per node; extend in the canvas.',
  'Education',
  '[{"id":"n1","type":"custom","position":{"x":100,"y":200},"data":{"type":"webhook","label":"Webhook (1)"}},{"id":"n2","type":"custom","position":{"x":360,"y":200},"data":{"type":"ai_agent","label":"Ai Agent (2)"}},{"id":"n3","type":"custom","position":{"x":620,"y":200},"data":{"type":"notion","label":"Notion (3)"}},{"id":"n4","type":"custom","position":{"x":880,"y":200},"data":{"type":"log_output","label":"Log Output (4)"}}]'::jsonb,
  '[{"id":"e1","source":"n1","target":"n2","sourceHandle":"output","targetHandle":"input"},{"id":"e2","source":"n2","target":"n3","sourceHandle":"output","targetHandle":"input"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"output","targetHandle":"input"}]'::jsonb,
  'Beginner',
  12,
  ARRAY['Education', 'webhook', 'ai-agent', 'notion', 'log-output'],
  true,
  true,
  COALESCE((SELECT user_id FROM public.user_roles WHERE role = 'admin' LIMIT 1), (SELECT id FROM auth.users ORDER BY created_at LIMIT 1))
);


-- Template #209
INSERT INTO public.templates (name, description, category, nodes, edges, difficulty, estimated_setup_time, tags, is_active, is_featured, created_by)
VALUES (
  'Real Estate: Tag and classify invoice lines',
  'Starter workflow: Real Estate: Tag and classify invoice lines. Linear flow (form → google_calendar → twitter → log_output). Configure credentials and fields per node; extend in the canvas.',
  'Real Estate',
  '[{"id":"n1","type":"custom","position":{"x":100,"y":200},"data":{"type":"form","label":"Form (1)"}},{"id":"n2","type":"custom","position":{"x":360,"y":200},"data":{"type":"google_calendar","label":"Google Calendar (2)"}},{"id":"n3","type":"custom","position":{"x":620,"y":200},"data":{"type":"twitter","label":"Twitter (3)"}},{"id":"n4","type":"custom","position":{"x":880,"y":200},"data":{"type":"log_output","label":"Log Output (4)"}}]'::jsonb,
  '[{"id":"e1","source":"n1","target":"n2","sourceHandle":"output","targetHandle":"input"},{"id":"e2","source":"n2","target":"n3","sourceHandle":"output","targetHandle":"input"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"output","targetHandle":"input"}]'::jsonb,
  'Intermediate',
  13,
  ARRAY['Real Estate', 'form', 'google-calendar', 'twitter', 'log-output'],
  true,
  false,
  COALESCE((SELECT user_id FROM public.user_roles WHERE role = 'admin' LIMIT 1), (SELECT id FROM auth.users ORDER BY created_at LIMIT 1))
);


-- Template #210
INSERT INTO public.templates (name, description, category, nodes, edges, difficulty, estimated_setup_time, tags, is_active, is_featured, created_by)
VALUES (
  'Legal Ops: Handshake policy attestations',
  'Starter workflow: Legal Ops: Handshake policy attestations. Linear flow (interval → linkedin → set_variable → log_output). Configure credentials and fields per node; extend in the canvas.',
  'Legal',
  '[{"id":"n1","type":"custom","position":{"x":100,"y":200},"data":{"type":"interval","label":"Interval (1)"}},{"id":"n2","type":"custom","position":{"x":360,"y":200},"data":{"type":"linkedin","label":"Linkedin (2)"}},{"id":"n3","type":"custom","position":{"x":620,"y":200},"data":{"type":"set_variable","label":"Set Variable (3)"}},{"id":"n4","type":"custom","position":{"x":880,"y":200},"data":{"type":"log_output","label":"Log Output (4)"}}]'::jsonb,
  '[{"id":"e1","source":"n1","target":"n2","sourceHandle":"output","targetHandle":"input"},{"id":"e2","source":"n2","target":"n3","sourceHandle":"output","targetHandle":"input"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"output","targetHandle":"input"}]'::jsonb,
  'Advanced',
  14,
  ARRAY['Legal', 'interval', 'linkedin', 'set-variable', 'log-output'],
  true,
  false,
  COALESCE((SELECT user_id FROM public.user_roles WHERE role = 'admin' LIMIT 1), (SELECT id FROM auth.users ORDER BY created_at LIMIT 1))
);


-- Template #211
INSERT INTO public.templates (name, description, category, nodes, edges, difficulty, estimated_setup_time, tags, is_active, is_featured, created_by)
VALUES (
  'Manufacturing: Enrich new leads',
  'Starter workflow: Manufacturing: Enrich new leads. Linear flow (manual_trigger → http_request → google_sheets → log_output). Configure credentials and fields per node; extend in the canvas.',
  'Operations',
  '[{"id":"n1","type":"custom","position":{"x":100,"y":200},"data":{"type":"manual_trigger","label":"Manual Trigger (1)"}},{"id":"n2","type":"custom","position":{"x":360,"y":200},"data":{"type":"http_request","label":"Http Request (2)"}},{"id":"n3","type":"custom","position":{"x":620,"y":200},"data":{"type":"google_sheets","label":"Google Sheets (3)"}},{"id":"n4","type":"custom","position":{"x":880,"y":200},"data":{"type":"log_output","label":"Log Output (4)"}}]'::jsonb,
  '[{"id":"e1","source":"n1","target":"n2","sourceHandle":"output","targetHandle":"input"},{"id":"e2","source":"n2","target":"n3","sourceHandle":"output","targetHandle":"input"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"output","targetHandle":"input"}]'::jsonb,
  'Beginner',
  15,
  ARRAY['Operations', 'manual-trigger', 'http-request', 'google-sheets', 'log-output'],
  true,
  false,
  COALESCE((SELECT user_id FROM public.user_roles WHERE role = 'admin' LIMIT 1), (SELECT id FROM auth.users ORDER BY created_at LIMIT 1))
);


-- Template #212
INSERT INTO public.templates (name, description, category, nodes, edges, difficulty, estimated_setup_time, tags, is_active, is_featured, created_by)
VALUES (
  'Nonprofit: Redact expense receipts',
  'Starter workflow: Nonprofit: Redact expense receipts. Linear flow (schedule → telegram → mongodb → log_output). Configure credentials and fields per node; extend in the canvas.',
  'Nonprofit',
  '[{"id":"n1","type":"custom","position":{"x":100,"y":200},"data":{"type":"schedule","label":"Schedule (1)"}},{"id":"n2","type":"custom","position":{"x":360,"y":200},"data":{"type":"telegram","label":"Telegram (2)"}},{"id":"n3","type":"custom","position":{"x":620,"y":200},"data":{"type":"mongodb","label":"Mongodb (3)"}},{"id":"n4","type":"custom","position":{"x":880,"y":200},"data":{"type":"log_output","label":"Log Output (4)"}}]'::jsonb,
  '[{"id":"e1","source":"n1","target":"n2","sourceHandle":"output","targetHandle":"input"},{"id":"e2","source":"n2","target":"n3","sourceHandle":"output","targetHandle":"input"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"output","targetHandle":"input"}]'::jsonb,
  'Intermediate',
  16,
  ARRAY['Nonprofit', 'schedule', 'telegram', 'mongodb', 'log-output'],
  true,
  false,
  COALESCE((SELECT user_id FROM public.user_roles WHERE role = 'admin' LIMIT 1), (SELECT id FROM auth.users ORDER BY created_at LIMIT 1))
);


-- Template #213
INSERT INTO public.templates (name, description, category, nodes, edges, difficulty, estimated_setup_time, tags, is_active, is_featured, created_by)
VALUES (
  'Media & Publishing: Extract metrics from API error bursts',
  'Starter workflow: Media & Publishing: Extract metrics from API error bursts. Linear flow (webhook → csv → email → log_output). Configure credentials and fields per node; extend in the canvas.',
  'Media',
  '[{"id":"n1","type":"custom","position":{"x":100,"y":200},"data":{"type":"webhook","label":"Webhook (1)"}},{"id":"n2","type":"custom","position":{"x":360,"y":200},"data":{"type":"csv","label":"Csv (2)"}},{"id":"n3","type":"custom","position":{"x":620,"y":200},"data":{"type":"email","label":"Email (3)"}},{"id":"n4","type":"custom","position":{"x":880,"y":200},"data":{"type":"log_output","label":"Log Output (4)"}}]'::jsonb,
  '[{"id":"e1","source":"n1","target":"n2","sourceHandle":"output","targetHandle":"input"},{"id":"e2","source":"n2","target":"n3","sourceHandle":"output","targetHandle":"input"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"output","targetHandle":"input"}]'::jsonb,
  'Advanced',
  17,
  ARRAY['Media', 'webhook', 'csv', 'email', 'log-output'],
  true,
  false,
  COALESCE((SELECT user_id FROM public.user_roles WHERE role = 'admin' LIMIT 1), (SELECT id FROM auth.users ORDER BY created_at LIMIT 1))
);


-- Template #214
INSERT INTO public.templates (name, description, category, nodes, edges, difficulty, estimated_setup_time, tags, is_active, is_featured, created_by)
VALUES (
  'Logistics: Triage contract PDFs',
  'Starter workflow: Logistics: Triage contract PDFs. Linear flow (form → notion → ai_agent → log_output). Configure credentials and fields per node; extend in the canvas.',
  'Logistics',
  '[{"id":"n1","type":"custom","position":{"x":100,"y":200},"data":{"type":"form","label":"Form (1)"}},{"id":"n2","type":"custom","position":{"x":360,"y":200},"data":{"type":"notion","label":"Notion (2)"}},{"id":"n3","type":"custom","position":{"x":620,"y":200},"data":{"type":"ai_agent","label":"Ai Agent (3)"}},{"id":"n4","type":"custom","position":{"x":880,"y":200},"data":{"type":"log_output","label":"Log Output (4)"}}]'::jsonb,
  '[{"id":"e1","source":"n1","target":"n2","sourceHandle":"output","targetHandle":"input"},{"id":"e2","source":"n2","target":"n3","sourceHandle":"output","targetHandle":"input"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"output","targetHandle":"input"}]'::jsonb,
  'Beginner',
  18,
  ARRAY['Logistics', 'form', 'notion', 'ai-agent', 'log-output'],
  true,
  false,
  COALESCE((SELECT user_id FROM public.user_roles WHERE role = 'admin' LIMIT 1), (SELECT id FROM auth.users ORDER BY created_at LIMIT 1))
);


-- Template #215
INSERT INTO public.templates (name, description, category, nodes, edges, difficulty, estimated_setup_time, tags, is_active, is_featured, created_by)
VALUES (
  'Hospitality: Transform loan applications',
  'Starter workflow: Hospitality: Transform loan applications. Linear flow (interval → ai_chat_model → text_formatter → log_output). Configure credentials and fields per node; extend in the canvas.',
  'Hospitality',
  '[{"id":"n1","type":"custom","position":{"x":100,"y":200},"data":{"type":"interval","label":"Interval (1)"}},{"id":"n2","type":"custom","position":{"x":360,"y":200},"data":{"type":"ai_chat_model","label":"Ai Chat Model (2)"}},{"id":"n3","type":"custom","position":{"x":620,"y":200},"data":{"type":"text_formatter","label":"Text Formatter (3)"}},{"id":"n4","type":"custom","position":{"x":880,"y":200},"data":{"type":"log_output","label":"Log Output (4)"}}]'::jsonb,
  '[{"id":"e1","source":"n1","target":"n2","sourceHandle":"output","targetHandle":"input"},{"id":"e2","source":"n2","target":"n3","sourceHandle":"output","targetHandle":"input"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"output","targetHandle":"input"}]'::jsonb,
  'Intermediate',
  19,
  ARRAY['Hospitality', 'interval', 'ai-chat-model', 'text-formatter', 'log-output'],
  true,
  false,
  COALESCE((SELECT user_id FROM public.user_roles WHERE role = 'admin' LIMIT 1), (SELECT id FROM auth.users ORDER BY created_at LIMIT 1))
);


-- Template #216
INSERT INTO public.templates (name, description, category, nodes, edges, difficulty, estimated_setup_time, tags, is_active, is_featured, created_by)
VALUES (
  'SaaS Product: Back up ticket updates',
  'Starter workflow: SaaS Product: Back up ticket updates. Linear flow (manual_trigger → postgresql → mysql → log_output). Configure credentials and fields per node; extend in the canvas.',
  'Product',
  '[{"id":"n1","type":"custom","position":{"x":100,"y":200},"data":{"type":"manual_trigger","label":"Manual Trigger (1)"}},{"id":"n2","type":"custom","position":{"x":360,"y":200},"data":{"type":"postgresql","label":"Postgresql (2)"}},{"id":"n3","type":"custom","position":{"x":620,"y":200},"data":{"type":"mysql","label":"Mysql (3)"}},{"id":"n4","type":"custom","position":{"x":880,"y":200},"data":{"type":"log_output","label":"Log Output (4)"}}]'::jsonb,
  '[{"id":"e1","source":"n1","target":"n2","sourceHandle":"output","targetHandle":"input"},{"id":"e2","source":"n2","target":"n3","sourceHandle":"output","targetHandle":"input"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"output","targetHandle":"input"}]'::jsonb,
  'Advanced',
  20,
  ARRAY['Product', 'manual-trigger', 'postgresql', 'mysql', 'log-output'],
  true,
  false,
  COALESCE((SELECT user_id FROM public.user_roles WHERE role = 'admin' LIMIT 1), (SELECT id FROM auth.users ORDER BY created_at LIMIT 1))
);


-- Template #217
INSERT INTO public.templates (name, description, category, nodes, edges, difficulty, estimated_setup_time, tags, is_active, is_featured, created_by)
VALUES (
  'IT Service Desk: Sync candidate applications',
  'Starter workflow: IT Service Desk: Sync candidate applications. Linear flow (schedule → ai_service → slack_message → log_output). Configure credentials and fields per node; extend in the canvas.',
  'IT',
  '[{"id":"n1","type":"custom","position":{"x":100,"y":200},"data":{"type":"schedule","label":"Schedule (1)"}},{"id":"n2","type":"custom","position":{"x":360,"y":200},"data":{"type":"ai_service","label":"Ai Service (2)"}},{"id":"n3","type":"custom","position":{"x":620,"y":200},"data":{"type":"slack_message","label":"Slack Message (3)"}},{"id":"n4","type":"custom","position":{"x":880,"y":200},"data":{"type":"log_output","label":"Log Output (4)"}}]'::jsonb,
  '[{"id":"e1","source":"n1","target":"n2","sourceHandle":"output","targetHandle":"input"},{"id":"e2","source":"n2","target":"n3","sourceHandle":"output","targetHandle":"input"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"output","targetHandle":"input"}]'::jsonb,
  'Beginner',
  21,
  ARRAY['IT', 'schedule', 'ai-service', 'slack-message', 'log-output'],
  true,
  false,
  COALESCE((SELECT user_id FROM public.user_roles WHERE role = 'admin' LIMIT 1), (SELECT id FROM auth.users ORDER BY created_at LIMIT 1))
);


-- Template #218
INSERT INTO public.templates (name, description, category, nodes, edges, difficulty, estimated_setup_time, tags, is_active, is_featured, created_by)
VALUES (
  'Sales Ops: Score schema migrations',
  'Starter workflow: Sales Ops: Score schema migrations. Linear flow (webhook → google_sheets → ollama → log_output). Configure credentials and fields per node; extend in the canvas.',
  'CRM & Sales',
  '[{"id":"n1","type":"custom","position":{"x":100,"y":200},"data":{"type":"webhook","label":"Webhook (1)"}},{"id":"n2","type":"custom","position":{"x":360,"y":200},"data":{"type":"google_sheets","label":"Google Sheets (2)"}},{"id":"n3","type":"custom","position":{"x":620,"y":200},"data":{"type":"ollama","label":"Ollama (3)"}},{"id":"n4","type":"custom","position":{"x":880,"y":200},"data":{"type":"log_output","label":"Log Output (4)"}}]'::jsonb,
  '[{"id":"e1","source":"n1","target":"n2","sourceHandle":"output","targetHandle":"input"},{"id":"e2","source":"n2","target":"n3","sourceHandle":"output","targetHandle":"input"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"output","targetHandle":"input"}]'::jsonb,
  'Intermediate',
  22,
  ARRAY['CRM & Sales', 'webhook', 'google-sheets', 'ollama', 'log-output'],
  true,
  false,
  COALESCE((SELECT user_id FROM public.user_roles WHERE role = 'admin' LIMIT 1), (SELECT id FROM auth.users ORDER BY created_at LIMIT 1))
);


-- Template #219
INSERT INTO public.templates (name, description, category, nodes, edges, difficulty, estimated_setup_time, tags, is_active, is_featured, created_by)
VALUES (
  'Data Analytics: Normalize survey results',
  'Starter workflow: Data Analytics: Normalize survey results. Linear flow (form → email → csv → log_output). Configure credentials and fields per node; extend in the canvas.',
  'Data & BI',
  '[{"id":"n1","type":"custom","position":{"x":100,"y":200},"data":{"type":"form","label":"Form (1)"}},{"id":"n2","type":"custom","position":{"x":360,"y":200},"data":{"type":"email","label":"Email (2)"}},{"id":"n3","type":"custom","position":{"x":620,"y":200},"data":{"type":"csv","label":"Csv (3)"}},{"id":"n4","type":"custom","position":{"x":880,"y":200},"data":{"type":"log_output","label":"Log Output (4)"}}]'::jsonb,
  '[{"id":"e1","source":"n1","target":"n2","sourceHandle":"output","targetHandle":"input"},{"id":"e2","source":"n2","target":"n3","sourceHandle":"output","targetHandle":"input"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"output","targetHandle":"input"}]'::jsonb,
  'Advanced',
  23,
  ARRAY['Data & BI', 'form', 'email', 'csv', 'log-output'],
  true,
  false,
  COALESCE((SELECT user_id FROM public.user_roles WHERE role = 'admin' LIMIT 1), (SELECT id FROM auth.users ORDER BY created_at LIMIT 1))
);


-- Template #220
INSERT INTO public.templates (name, description, category, nodes, edges, difficulty, estimated_setup_time, tags, is_active, is_featured, created_by)
VALUES (
  'Security & GRC: Route grant submissions',
  'Starter workflow: Security & GRC: Route grant submissions. Linear flow (interval → filter → google_drive → log_output). Configure credentials and fields per node; extend in the canvas.',
  'Security',
  '[{"id":"n1","type":"custom","position":{"x":100,"y":200},"data":{"type":"interval","label":"Interval (1)"}},{"id":"n2","type":"custom","position":{"x":360,"y":200},"data":{"type":"filter","label":"Filter (2)"}},{"id":"n3","type":"custom","position":{"x":620,"y":200},"data":{"type":"google_drive","label":"Google Drive (3)"}},{"id":"n4","type":"custom","position":{"x":880,"y":200},"data":{"type":"log_output","label":"Log Output (4)"}}]'::jsonb,
  '[{"id":"e1","source":"n1","target":"n2","sourceHandle":"output","targetHandle":"input"},{"id":"e2","source":"n2","target":"n3","sourceHandle":"output","targetHandle":"input"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"output","targetHandle":"input"}]'::jsonb,
  'Beginner',
  24,
  ARRAY['Security', 'interval', 'filter', 'google-drive', 'log-output'],
  true,
  false,
  COALESCE((SELECT user_id FROM public.user_roles WHERE role = 'admin' LIMIT 1), (SELECT id FROM auth.users ORDER BY created_at LIMIT 1))
);


-- Template #221
INSERT INTO public.templates (name, description, category, nodes, edges, difficulty, estimated_setup_time, tags, is_active, is_featured, created_by)
VALUES (
  'Construction: Watermark CSV uploads',
  'Starter workflow: Construction: Watermark CSV uploads. Linear flow (manual_trigger → hubspot → clickup → log_output). Configure credentials and fields per node; extend in the canvas.',
  'Construction',
  '[{"id":"n1","type":"custom","position":{"x":100,"y":200},"data":{"type":"manual_trigger","label":"Manual Trigger (1)"}},{"id":"n2","type":"custom","position":{"x":360,"y":200},"data":{"type":"hubspot","label":"Hubspot (2)"}},{"id":"n3","type":"custom","position":{"x":620,"y":200},"data":{"type":"clickup","label":"Clickup (3)"}},{"id":"n4","type":"custom","position":{"x":880,"y":200},"data":{"type":"log_output","label":"Log Output (4)"}}]'::jsonb,
  '[{"id":"e1","source":"n1","target":"n2","sourceHandle":"output","targetHandle":"input"},{"id":"e2","source":"n2","target":"n3","sourceHandle":"output","targetHandle":"input"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"output","targetHandle":"input"}]'::jsonb,
  'Intermediate',
  25,
  ARRAY['Construction', 'manual-trigger', 'hubspot', 'clickup', 'log-output'],
  true,
  false,
  COALESCE((SELECT user_id FROM public.user_roles WHERE role = 'admin' LIMIT 1), (SELECT id FROM auth.users ORDER BY created_at LIMIT 1))
);


-- Template #222
INSERT INTO public.templates (name, description, category, nodes, edges, difficulty, estimated_setup_time, tags, is_active, is_featured, created_by)
VALUES (
  'Agriculture: Schedule patient intake forms',
  'Starter workflow: Agriculture: Schedule patient intake forms. Linear flow (schedule → set_variable → linkedin → log_output). Configure credentials and fields per node; extend in the canvas.',
  'Agriculture',
  '[{"id":"n1","type":"custom","position":{"x":100,"y":200},"data":{"type":"schedule","label":"Schedule (1)"}},{"id":"n2","type":"custom","position":{"x":360,"y":200},"data":{"type":"set_variable","label":"Set Variable (2)"}},{"id":"n3","type":"custom","position":{"x":620,"y":200},"data":{"type":"linkedin","label":"Linkedin (3)"}},{"id":"n4","type":"custom","position":{"x":880,"y":200},"data":{"type":"log_output","label":"Log Output (4)"}}]'::jsonb,
  '[{"id":"e1","source":"n1","target":"n2","sourceHandle":"output","targetHandle":"input"},{"id":"e2","source":"n2","target":"n3","sourceHandle":"output","targetHandle":"input"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"output","targetHandle":"input"}]'::jsonb,
  'Advanced',
  26,
  ARRAY['Agriculture', 'schedule', 'set-variable', 'linkedin', 'log-output'],
  true,
  false,
  COALESCE((SELECT user_id FROM public.user_roles WHERE role = 'admin' LIMIT 1), (SELECT id FROM auth.users ORDER BY created_at LIMIT 1))
);


-- Template #223
INSERT INTO public.templates (name, description, category, nodes, edges, difficulty, estimated_setup_time, tags, is_active, is_featured, created_by)
VALUES (
  'Energy: Publish backup manifests',
  'Starter workflow: Energy: Publish backup manifests. Linear flow (webhook → mysql → javascript → log_output). Configure credentials and fields per node; extend in the canvas.',
  'Energy',
  '[{"id":"n1","type":"custom","position":{"x":100,"y":200},"data":{"type":"webhook","label":"Webhook (1)"}},{"id":"n2","type":"custom","position":{"x":360,"y":200},"data":{"type":"mysql","label":"Mysql (2)"}},{"id":"n3","type":"custom","position":{"x":620,"y":200},"data":{"type":"javascript","label":"Javascript (3)"}},{"id":"n4","type":"custom","position":{"x":880,"y":200},"data":{"type":"log_output","label":"Log Output (4)"}}]'::jsonb,
  '[{"id":"e1","source":"n1","target":"n2","sourceHandle":"output","targetHandle":"input"},{"id":"e2","source":"n2","target":"n3","sourceHandle":"output","targetHandle":"input"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"output","targetHandle":"input"}]'::jsonb,
  'Beginner',
  27,
  ARRAY['Energy', 'webhook', 'mysql', 'javascript', 'log-output'],
  true,
  false,
  COALESCE((SELECT user_id FROM public.user_roles WHERE role = 'admin' LIMIT 1), (SELECT id FROM auth.users ORDER BY created_at LIMIT 1))
);


-- Template #224
INSERT INTO public.templates (name, description, category, nodes, edges, difficulty, estimated_setup_time, tags, is_active, is_featured, created_by)
VALUES (
  'Telecom: Archive experiment logs',
  'Starter workflow: Telecom: Archive experiment logs. Linear flow (form → ollama → google_sheets → log_output). Configure credentials and fields per node; extend in the canvas.',
  'Telecom',
  '[{"id":"n1","type":"custom","position":{"x":100,"y":200},"data":{"type":"form","label":"Form (1)"}},{"id":"n2","type":"custom","position":{"x":360,"y":200},"data":{"type":"ollama","label":"Ollama (2)"}},{"id":"n3","type":"custom","position":{"x":620,"y":200},"data":{"type":"google_sheets","label":"Google Sheets (3)"}},{"id":"n4","type":"custom","position":{"x":880,"y":200},"data":{"type":"log_output","label":"Log Output (4)"}}]'::jsonb,
  '[{"id":"e1","source":"n1","target":"n2","sourceHandle":"output","targetHandle":"input"},{"id":"e2","source":"n2","target":"n3","sourceHandle":"output","targetHandle":"input"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"output","targetHandle":"input"}]'::jsonb,
  'Intermediate',
  28,
  ARRAY['Telecom', 'form', 'ollama', 'google-sheets', 'log-output'],
  true,
  false,
  COALESCE((SELECT user_id FROM public.user_roles WHERE role = 'admin' LIMIT 1), (SELECT id FROM auth.users ORDER BY created_at LIMIT 1))
);


-- Template #225
INSERT INTO public.templates (name, description, category, nodes, edges, difficulty, estimated_setup_time, tags, is_active, is_featured, created_by)
VALUES (
  'Gov & Public Sector: Summarize court filings',
  'Starter workflow: Gov & Public Sector: Summarize court filings. Linear flow (interval → google_gmail → airtable → log_output). Configure credentials and fields per node; extend in the canvas.',
  'Public Sector',
  '[{"id":"n1","type":"custom","position":{"x":100,"y":200},"data":{"type":"interval","label":"Interval (1)"}},{"id":"n2","type":"custom","position":{"x":360,"y":200},"data":{"type":"google_gmail","label":"Google Gmail (2)"}},{"id":"n3","type":"custom","position":{"x":620,"y":200},"data":{"type":"airtable","label":"Airtable (3)"}},{"id":"n4","type":"custom","position":{"x":880,"y":200},"data":{"type":"log_output","label":"Log Output (4)"}}]'::jsonb,
  '[{"id":"e1","source":"n1","target":"n2","sourceHandle":"output","targetHandle":"input"},{"id":"e2","source":"n2","target":"n3","sourceHandle":"output","targetHandle":"input"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"output","targetHandle":"input"}]'::jsonb,
  'Advanced',
  29,
  ARRAY['Public Sector', 'interval', 'google-gmail', 'airtable', 'log-output'],
  true,
  false,
  COALESCE((SELECT user_id FROM public.user_roles WHERE role = 'admin' LIMIT 1), (SELECT id FROM auth.users ORDER BY created_at LIMIT 1))
);


-- Template #226
INSERT INTO public.templates (name, description, category, nodes, edges, difficulty, estimated_setup_time, tags, is_active, is_featured, created_by)
VALUES (
  'E-commerce: Automate form responses',
  'Starter workflow: E-commerce: Automate form responses. Linear flow (manual_trigger → outlook → twitter → log_output). Configure credentials and fields per node; extend in the canvas.',
  'Commerce & Retail',
  '[{"id":"n1","type":"custom","position":{"x":100,"y":200},"data":{"type":"manual_trigger","label":"Manual Trigger (1)"}},{"id":"n2","type":"custom","position":{"x":360,"y":200},"data":{"type":"outlook","label":"Outlook (2)"}},{"id":"n3","type":"custom","position":{"x":620,"y":200},"data":{"type":"twitter","label":"Twitter (3)"}},{"id":"n4","type":"custom","position":{"x":880,"y":200},"data":{"type":"log_output","label":"Log Output (4)"}}]'::jsonb,
  '[{"id":"e1","source":"n1","target":"n2","sourceHandle":"output","targetHandle":"input"},{"id":"e2","source":"n2","target":"n3","sourceHandle":"output","targetHandle":"input"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"output","targetHandle":"input"}]'::jsonb,
  'Beginner',
  5,
  ARRAY['Commerce & Retail', 'manual-trigger', 'outlook', 'twitter', 'log-output'],
  true,
  false,
  COALESCE((SELECT user_id FROM public.user_roles WHERE role = 'admin' LIMIT 1), (SELECT id FROM auth.users ORDER BY created_at LIMIT 1))
);


-- Template #227
INSERT INTO public.templates (name, description, category, nodes, edges, difficulty, estimated_setup_time, tags, is_active, is_featured, created_by)
VALUES (
  'Healthcare: Deduplicate sensor readings',
  'Starter workflow: Healthcare: Deduplicate sensor readings. Linear flow (schedule → text_formatter → ai_chat_model → log_output). Configure credentials and fields per node; extend in the canvas.',
  'Healthcare',
  '[{"id":"n1","type":"custom","position":{"x":100,"y":200},"data":{"type":"schedule","label":"Schedule (1)"}},{"id":"n2","type":"custom","position":{"x":360,"y":200},"data":{"type":"text_formatter","label":"Text Formatter (2)"}},{"id":"n3","type":"custom","position":{"x":620,"y":200},"data":{"type":"ai_chat_model","label":"Ai Chat Model (3)"}},{"id":"n4","type":"custom","position":{"x":880,"y":200},"data":{"type":"log_output","label":"Log Output (4)"}}]'::jsonb,
  '[{"id":"e1","source":"n1","target":"n2","sourceHandle":"output","targetHandle":"input"},{"id":"e2","source":"n2","target":"n3","sourceHandle":"output","targetHandle":"input"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"output","targetHandle":"input"}]'::jsonb,
  'Intermediate',
  6,
  ARRAY['Healthcare', 'schedule', 'text-formatter', 'ai-chat-model', 'log-output'],
  true,
  false,
  COALESCE((SELECT user_id FROM public.user_roles WHERE role = 'admin' LIMIT 1), (SELECT id FROM auth.users ORDER BY created_at LIMIT 1))
);


-- Template #228
INSERT INTO public.templates (name, description, category, nodes, edges, difficulty, estimated_setup_time, tags, is_active, is_featured, created_by)
VALUES (
  'Finance & Accounting: Parse compliance exports',
  'Starter workflow: Finance & Accounting: Parse compliance exports. Linear flow (webhook → clickup → function → log_output). Configure credentials and fields per node; extend in the canvas.',
  'Finance',
  '[{"id":"n1","type":"custom","position":{"x":100,"y":200},"data":{"type":"webhook","label":"Webhook (1)"}},{"id":"n2","type":"custom","position":{"x":360,"y":200},"data":{"type":"clickup","label":"Clickup (2)"}},{"id":"n3","type":"custom","position":{"x":620,"y":200},"data":{"type":"function","label":"Function (3)"}},{"id":"n4","type":"custom","position":{"x":880,"y":200},"data":{"type":"log_output","label":"Log Output (4)"}}]'::jsonb,
  '[{"id":"e1","source":"n1","target":"n2","sourceHandle":"output","targetHandle":"input"},{"id":"e2","source":"n2","target":"n3","sourceHandle":"output","targetHandle":"input"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"output","targetHandle":"input"}]'::jsonb,
  'Advanced',
  7,
  ARRAY['Finance', 'webhook', 'clickup', 'function', 'log-output'],
  true,
  false,
  COALESCE((SELECT user_id FROM public.user_roles WHERE role = 'admin' LIMIT 1), (SELECT id FROM auth.users ORDER BY created_at LIMIT 1))
);


-- Template #229
INSERT INTO public.templates (name, description, category, nodes, edges, difficulty, estimated_setup_time, tags, is_active, is_featured, created_by)
VALUES (
  'HR & People: Monitor feature flags',
  'Starter workflow: HR & People: Monitor feature flags. Linear flow (form → javascript → mysql → log_output). Configure credentials and fields per node; extend in the canvas.',
  'HR',
  '[{"id":"n1","type":"custom","position":{"x":100,"y":200},"data":{"type":"form","label":"Form (1)"}},{"id":"n2","type":"custom","position":{"x":360,"y":200},"data":{"type":"javascript","label":"Javascript (2)"}},{"id":"n3","type":"custom","position":{"x":620,"y":200},"data":{"type":"mysql","label":"Mysql (3)"}},{"id":"n4","type":"custom","position":{"x":880,"y":200},"data":{"type":"log_output","label":"Log Output (4)"}}]'::jsonb,
  '[{"id":"e1","source":"n1","target":"n2","sourceHandle":"output","targetHandle":"input"},{"id":"e2","source":"n2","target":"n3","sourceHandle":"output","targetHandle":"input"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"output","targetHandle":"input"}]'::jsonb,
  'Beginner',
  8,
  ARRAY['HR', 'form', 'javascript', 'mysql', 'log-output'],
  true,
  false,
  COALESCE((SELECT user_id FROM public.user_roles WHERE role = 'admin' LIMIT 1), (SELECT id FROM auth.users ORDER BY created_at LIMIT 1))
);


-- Template #230
INSERT INTO public.templates (name, description, category, nodes, edges, difficulty, estimated_setup_time, tags, is_active, is_featured, created_by)
VALUES (
  'DevOps & SRE: Aggregate asset depreciations',
  'Starter workflow: DevOps & SRE: Aggregate asset depreciations. Linear flow (interval → mongodb → telegram → log_output). Configure credentials and fields per node; extend in the canvas.',
  'Developer Tools',
  '[{"id":"n1","type":"custom","position":{"x":100,"y":200},"data":{"type":"interval","label":"Interval (1)"}},{"id":"n2","type":"custom","position":{"x":360,"y":200},"data":{"type":"mongodb","label":"Mongodb (2)"}},{"id":"n3","type":"custom","position":{"x":620,"y":200},"data":{"type":"telegram","label":"Telegram (3)"}},{"id":"n4","type":"custom","position":{"x":880,"y":200},"data":{"type":"log_output","label":"Log Output (4)"}}]'::jsonb,
  '[{"id":"e1","source":"n1","target":"n2","sourceHandle":"output","targetHandle":"input"},{"id":"e2","source":"n2","target":"n3","sourceHandle":"output","targetHandle":"input"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"output","targetHandle":"input"}]'::jsonb,
  'Intermediate',
  9,
  ARRAY['Developer Tools', 'interval', 'mongodb', 'telegram', 'log-output'],
  true,
  false,
  COALESCE((SELECT user_id FROM public.user_roles WHERE role = 'admin' LIMIT 1), (SELECT id FROM auth.users ORDER BY created_at LIMIT 1))
);


-- Template #231
INSERT INTO public.templates (name, description, category, nodes, edges, difficulty, estimated_setup_time, tags, is_active, is_featured, created_by)
VALUES (
  'Marketing: Validate webhook payloads',
  'Starter workflow: Marketing: Validate webhook payloads. Linear flow (manual_trigger → openai_gpt → ai_agent → log_output). Configure credentials and fields per node; extend in the canvas.',
  'Marketing & Growth',
  '[{"id":"n1","type":"custom","position":{"x":100,"y":200},"data":{"type":"manual_trigger","label":"Manual Trigger (1)"}},{"id":"n2","type":"custom","position":{"x":360,"y":200},"data":{"type":"openai_gpt","label":"Openai Gpt (2)"}},{"id":"n3","type":"custom","position":{"x":620,"y":200},"data":{"type":"ai_agent","label":"Ai Agent (3)"}},{"id":"n4","type":"custom","position":{"x":880,"y":200},"data":{"type":"log_output","label":"Log Output (4)"}}]'::jsonb,
  '[{"id":"e1","source":"n1","target":"n2","sourceHandle":"output","targetHandle":"input"},{"id":"e2","source":"n2","target":"n3","sourceHandle":"output","targetHandle":"input"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"output","targetHandle":"input"}]'::jsonb,
  'Advanced',
  10,
  ARRAY['Marketing & Growth', 'manual-trigger', 'openai-gpt', 'ai-agent', 'log-output'],
  true,
  true,
  COALESCE((SELECT user_id FROM public.user_roles WHERE role = 'admin' LIMIT 1), (SELECT id FROM auth.users ORDER BY created_at LIMIT 1))
);


-- Template #232
INSERT INTO public.templates (name, description, category, nodes, edges, difficulty, estimated_setup_time, tags, is_active, is_featured, created_by)
VALUES (
  'Customer Support: Reconcile shipment events',
  'Starter workflow: Customer Support: Reconcile shipment events. Linear flow (schedule → google_drive → filter → log_output). Configure credentials and fields per node; extend in the canvas.',
  'Support',
  '[{"id":"n1","type":"custom","position":{"x":100,"y":200},"data":{"type":"schedule","label":"Schedule (1)"}},{"id":"n2","type":"custom","position":{"x":360,"y":200},"data":{"type":"google_drive","label":"Google Drive (2)"}},{"id":"n3","type":"custom","position":{"x":620,"y":200},"data":{"type":"filter","label":"Filter (3)"}},{"id":"n4","type":"custom","position":{"x":880,"y":200},"data":{"type":"log_output","label":"Log Output (4)"}}]'::jsonb,
  '[{"id":"e1","source":"n1","target":"n2","sourceHandle":"output","targetHandle":"input"},{"id":"e2","source":"n2","target":"n3","sourceHandle":"output","targetHandle":"input"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"output","targetHandle":"input"}]'::jsonb,
  'Beginner',
  11,
  ARRAY['Support', 'schedule', 'google-drive', 'filter', 'log-output'],
  true,
  false,
  COALESCE((SELECT user_id FROM public.user_roles WHERE role = 'admin' LIMIT 1), (SELECT id FROM auth.users ORDER BY created_at LIMIT 1))
);


-- Template #233
INSERT INTO public.templates (name, description, category, nodes, edges, difficulty, estimated_setup_time, tags, is_active, is_featured, created_by)
VALUES (
  'Education: Notify stakeholders about security findings',
  'Starter workflow: Education: Notify stakeholders about security findings. Linear flow (webhook → twitter → google_calendar → log_output). Configure credentials and fields per node; extend in the canvas.',
  'Education',
  '[{"id":"n1","type":"custom","position":{"x":100,"y":200},"data":{"type":"webhook","label":"Webhook (1)"}},{"id":"n2","type":"custom","position":{"x":360,"y":200},"data":{"type":"twitter","label":"Twitter (2)"}},{"id":"n3","type":"custom","position":{"x":620,"y":200},"data":{"type":"google_calendar","label":"Google Calendar (3)"}},{"id":"n4","type":"custom","position":{"x":880,"y":200},"data":{"type":"log_output","label":"Log Output (4)"}}]'::jsonb,
  '[{"id":"e1","source":"n1","target":"n2","sourceHandle":"output","targetHandle":"input"},{"id":"e2","source":"n2","target":"n3","sourceHandle":"output","targetHandle":"input"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"output","targetHandle":"input"}]'::jsonb,
  'Intermediate',
  12,
  ARRAY['Education', 'webhook', 'twitter', 'google-calendar', 'log-output'],
  true,
  false,
  COALESCE((SELECT user_id FROM public.user_roles WHERE role = 'admin' LIMIT 1), (SELECT id FROM auth.users ORDER BY created_at LIMIT 1))
);


-- Template #234
INSERT INTO public.templates (name, description, category, nodes, edges, difficulty, estimated_setup_time, tags, is_active, is_featured, created_by)
VALUES (
  'Real Estate: Tag and classify release notes',
  'Starter workflow: Real Estate: Tag and classify release notes. Linear flow (form → function → clickup → log_output). Configure credentials and fields per node; extend in the canvas.',
  'Real Estate',
  '[{"id":"n1","type":"custom","position":{"x":100,"y":200},"data":{"type":"form","label":"Form (1)"}},{"id":"n2","type":"custom","position":{"x":360,"y":200},"data":{"type":"function","label":"Function (2)"}},{"id":"n3","type":"custom","position":{"x":620,"y":200},"data":{"type":"clickup","label":"Clickup (3)"}},{"id":"n4","type":"custom","position":{"x":880,"y":200},"data":{"type":"log_output","label":"Log Output (4)"}}]'::jsonb,
  '[{"id":"e1","source":"n1","target":"n2","sourceHandle":"output","targetHandle":"input"},{"id":"e2","source":"n2","target":"n3","sourceHandle":"output","targetHandle":"input"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"output","targetHandle":"input"}]'::jsonb,
  'Advanced',
  13,
  ARRAY['Real Estate', 'form', 'function', 'clickup', 'log-output'],
  true,
  false,
  COALESCE((SELECT user_id FROM public.user_roles WHERE role = 'admin' LIMIT 1), (SELECT id FROM auth.users ORDER BY created_at LIMIT 1))
);


-- Template #235
INSERT INTO public.templates (name, description, category, nodes, edges, difficulty, estimated_setup_time, tags, is_active, is_featured, created_by)
VALUES (
  'Legal Ops: Handshake course enrollments',
  'Starter workflow: Legal Ops: Handshake course enrollments. Linear flow (interval → slack_message → ai_service → log_output). Configure credentials and fields per node; extend in the canvas.',
  'Legal',
  '[{"id":"n1","type":"custom","position":{"x":100,"y":200},"data":{"type":"interval","label":"Interval (1)"}},{"id":"n2","type":"custom","position":{"x":360,"y":200},"data":{"type":"slack_message","label":"Slack Message (2)"}},{"id":"n3","type":"custom","position":{"x":620,"y":200},"data":{"type":"ai_service","label":"Ai Service (3)"}},{"id":"n4","type":"custom","position":{"x":880,"y":200},"data":{"type":"log_output","label":"Log Output (4)"}}]'::jsonb,
  '[{"id":"e1","source":"n1","target":"n2","sourceHandle":"output","targetHandle":"input"},{"id":"e2","source":"n2","target":"n3","sourceHandle":"output","targetHandle":"input"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"output","targetHandle":"input"}]'::jsonb,
  'Beginner',
  14,
  ARRAY['Legal', 'interval', 'slack-message', 'ai-service', 'log-output'],
  true,
  false,
  COALESCE((SELECT user_id FROM public.user_roles WHERE role = 'admin' LIMIT 1), (SELECT id FROM auth.users ORDER BY created_at LIMIT 1))
);


-- Template #236
INSERT INTO public.templates (name, description, category, nodes, edges, difficulty, estimated_setup_time, tags, is_active, is_featured, created_by)
VALUES (
  'Manufacturing: Enrich daily KPIs',
  'Starter workflow: Manufacturing: Enrich daily KPIs. Linear flow (manual_trigger → json_parser → csv → log_output). Configure credentials and fields per node; extend in the canvas.',
  'Operations',
  '[{"id":"n1","type":"custom","position":{"x":100,"y":200},"data":{"type":"manual_trigger","label":"Manual Trigger (1)"}},{"id":"n2","type":"custom","position":{"x":360,"y":200},"data":{"type":"json_parser","label":"Json Parser (2)"}},{"id":"n3","type":"custom","position":{"x":620,"y":200},"data":{"type":"csv","label":"Csv (3)"}},{"id":"n4","type":"custom","position":{"x":880,"y":200},"data":{"type":"log_output","label":"Log Output (4)"}}]'::jsonb,
  '[{"id":"e1","source":"n1","target":"n2","sourceHandle":"output","targetHandle":"input"},{"id":"e2","source":"n2","target":"n3","sourceHandle":"output","targetHandle":"input"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"output","targetHandle":"input"}]'::jsonb,
  'Intermediate',
  15,
  ARRAY['Operations', 'manual-trigger', 'json-parser', 'csv', 'log-output'],
  true,
  false,
  COALESCE((SELECT user_id FROM public.user_roles WHERE role = 'admin' LIMIT 1), (SELECT id FROM auth.users ORDER BY created_at LIMIT 1))
);


-- Template #237
INSERT INTO public.templates (name, description, category, nodes, edges, difficulty, estimated_setup_time, tags, is_active, is_featured, created_by)
VALUES (
  'Nonprofit: Redact social mentions',
  'Starter workflow: Nonprofit: Redact social mentions. Linear flow (schedule → airtable → google_gmail → log_output). Configure credentials and fields per node; extend in the canvas.',
  'Nonprofit',
  '[{"id":"n1","type":"custom","position":{"x":100,"y":200},"data":{"type":"schedule","label":"Schedule (1)"}},{"id":"n2","type":"custom","position":{"x":360,"y":200},"data":{"type":"airtable","label":"Airtable (2)"}},{"id":"n3","type":"custom","position":{"x":620,"y":200},"data":{"type":"google_gmail","label":"Google Gmail (3)"}},{"id":"n4","type":"custom","position":{"x":880,"y":200},"data":{"type":"log_output","label":"Log Output (4)"}}]'::jsonb,
  '[{"id":"e1","source":"n1","target":"n2","sourceHandle":"output","targetHandle":"input"},{"id":"e2","source":"n2","target":"n3","sourceHandle":"output","targetHandle":"input"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"output","targetHandle":"input"}]'::jsonb,
  'Advanced',
  16,
  ARRAY['Nonprofit', 'schedule', 'airtable', 'google-gmail', 'log-output'],
  true,
  false,
  COALESCE((SELECT user_id FROM public.user_roles WHERE role = 'admin' LIMIT 1), (SELECT id FROM auth.users ORDER BY created_at LIMIT 1))
);


-- Template #238
INSERT INTO public.templates (name, description, category, nodes, edges, difficulty, estimated_setup_time, tags, is_active, is_featured, created_by)
VALUES (
  'Media & Publishing: Extract metrics from partner SLAs',
  'Starter workflow: Media & Publishing: Extract metrics from partner SLAs. Linear flow (webhook → ai_agent → notion → log_output). Configure credentials and fields per node; extend in the canvas.',
  'Media',
  '[{"id":"n1","type":"custom","position":{"x":100,"y":200},"data":{"type":"webhook","label":"Webhook (1)"}},{"id":"n2","type":"custom","position":{"x":360,"y":200},"data":{"type":"ai_agent","label":"Ai Agent (2)"}},{"id":"n3","type":"custom","position":{"x":620,"y":200},"data":{"type":"notion","label":"Notion (3)"}},{"id":"n4","type":"custom","position":{"x":880,"y":200},"data":{"type":"log_output","label":"Log Output (4)"}}]'::jsonb,
  '[{"id":"e1","source":"n1","target":"n2","sourceHandle":"output","targetHandle":"input"},{"id":"e2","source":"n2","target":"n3","sourceHandle":"output","targetHandle":"input"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"output","targetHandle":"input"}]'::jsonb,
  'Beginner',
  17,
  ARRAY['Media', 'webhook', 'ai-agent', 'notion', 'log-output'],
  true,
  false,
  COALESCE((SELECT user_id FROM public.user_roles WHERE role = 'admin' LIMIT 1), (SELECT id FROM auth.users ORDER BY created_at LIMIT 1))
);


-- Template #239
INSERT INTO public.templates (name, description, category, nodes, edges, difficulty, estimated_setup_time, tags, is_active, is_featured, created_by)
VALUES (
  'Logistics: Triage on-call incidents',
  'Starter workflow: Logistics: Triage on-call incidents. Linear flow (form → google_calendar → twitter → log_output). Configure credentials and fields per node; extend in the canvas.',
  'Logistics',
  '[{"id":"n1","type":"custom","position":{"x":100,"y":200},"data":{"type":"form","label":"Form (1)"}},{"id":"n2","type":"custom","position":{"x":360,"y":200},"data":{"type":"google_calendar","label":"Google Calendar (2)"}},{"id":"n3","type":"custom","position":{"x":620,"y":200},"data":{"type":"twitter","label":"Twitter (3)"}},{"id":"n4","type":"custom","position":{"x":880,"y":200},"data":{"type":"log_output","label":"Log Output (4)"}}]'::jsonb,
  '[{"id":"e1","source":"n1","target":"n2","sourceHandle":"output","targetHandle":"input"},{"id":"e2","source":"n2","target":"n3","sourceHandle":"output","targetHandle":"input"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"output","targetHandle":"input"}]'::jsonb,
  'Intermediate',
  18,
  ARRAY['Logistics', 'form', 'google-calendar', 'twitter', 'log-output'],
  true,
  false,
  COALESCE((SELECT user_id FROM public.user_roles WHERE role = 'admin' LIMIT 1), (SELECT id FROM auth.users ORDER BY created_at LIMIT 1))
);


-- Template #240
INSERT INTO public.templates (name, description, category, nodes, edges, difficulty, estimated_setup_time, tags, is_active, is_featured, created_by)
VALUES (
  'Hospitality: Transform room bookings',
  'Starter workflow: Hospitality: Transform room bookings. Linear flow (interval → linkedin → set_variable → log_output). Configure credentials and fields per node; extend in the canvas.',
  'Hospitality',
  '[{"id":"n1","type":"custom","position":{"x":100,"y":200},"data":{"type":"interval","label":"Interval (1)"}},{"id":"n2","type":"custom","position":{"x":360,"y":200},"data":{"type":"linkedin","label":"Linkedin (2)"}},{"id":"n3","type":"custom","position":{"x":620,"y":200},"data":{"type":"set_variable","label":"Set Variable (3)"}},{"id":"n4","type":"custom","position":{"x":880,"y":200},"data":{"type":"log_output","label":"Log Output (4)"}}]'::jsonb,
  '[{"id":"e1","source":"n1","target":"n2","sourceHandle":"output","targetHandle":"input"},{"id":"e2","source":"n2","target":"n3","sourceHandle":"output","targetHandle":"input"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"output","targetHandle":"input"}]'::jsonb,
  'Advanced',
  19,
  ARRAY['Hospitality', 'interval', 'linkedin', 'set-variable', 'log-output'],
  true,
  false,
  COALESCE((SELECT user_id FROM public.user_roles WHERE role = 'admin' LIMIT 1), (SELECT id FROM auth.users ORDER BY created_at LIMIT 1))
);


-- Template #241
INSERT INTO public.templates (name, description, category, nodes, edges, difficulty, estimated_setup_time, tags, is_active, is_featured, created_by)
VALUES (
  'SaaS Product: Back up calendar holds',
  'Starter workflow: SaaS Product: Back up calendar holds. Linear flow (manual_trigger → http_request → google_sheets → log_output). Configure credentials and fields per node; extend in the canvas.',
  'Product',
  '[{"id":"n1","type":"custom","position":{"x":100,"y":200},"data":{"type":"manual_trigger","label":"Manual Trigger (1)"}},{"id":"n2","type":"custom","position":{"x":360,"y":200},"data":{"type":"http_request","label":"Http Request (2)"}},{"id":"n3","type":"custom","position":{"x":620,"y":200},"data":{"type":"google_sheets","label":"Google Sheets (3)"}},{"id":"n4","type":"custom","position":{"x":880,"y":200},"data":{"type":"log_output","label":"Log Output (4)"}}]'::jsonb,
  '[{"id":"e1","source":"n1","target":"n2","sourceHandle":"output","targetHandle":"input"},{"id":"e2","source":"n2","target":"n3","sourceHandle":"output","targetHandle":"input"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"output","targetHandle":"input"}]'::jsonb,
  'Beginner',
  20,
  ARRAY['Product', 'manual-trigger', 'http-request', 'google-sheets', 'log-output'],
  true,
  false,
  COALESCE((SELECT user_id FROM public.user_roles WHERE role = 'admin' LIMIT 1), (SELECT id FROM auth.users ORDER BY created_at LIMIT 1))
);


-- Template #242
INSERT INTO public.templates (name, description, category, nodes, edges, difficulty, estimated_setup_time, tags, is_active, is_featured, created_by)
VALUES (
  'IT Service Desk: Sync help-center articles',
  'Starter workflow: IT Service Desk: Sync help-center articles. Linear flow (schedule → telegram → mongodb → log_output). Configure credentials and fields per node; extend in the canvas.',
  'IT',
  '[{"id":"n1","type":"custom","position":{"x":100,"y":200},"data":{"type":"schedule","label":"Schedule (1)"}},{"id":"n2","type":"custom","position":{"x":360,"y":200},"data":{"type":"telegram","label":"Telegram (2)"}},{"id":"n3","type":"custom","position":{"x":620,"y":200},"data":{"type":"mongodb","label":"Mongodb (3)"}},{"id":"n4","type":"custom","position":{"x":880,"y":200},"data":{"type":"log_output","label":"Log Output (4)"}}]'::jsonb,
  '[{"id":"e1","source":"n1","target":"n2","sourceHandle":"output","targetHandle":"input"},{"id":"e2","source":"n2","target":"n3","sourceHandle":"output","targetHandle":"input"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"output","targetHandle":"input"}]'::jsonb,
  'Intermediate',
  21,
  ARRAY['IT', 'schedule', 'telegram', 'mongodb', 'log-output'],
  true,
  false,
  COALESCE((SELECT user_id FROM public.user_roles WHERE role = 'admin' LIMIT 1), (SELECT id FROM auth.users ORDER BY created_at LIMIT 1))
);


-- Template #243
INSERT INTO public.templates (name, description, category, nodes, edges, difficulty, estimated_setup_time, tags, is_active, is_featured, created_by)
VALUES (
  'Sales Ops: Score board packets',
  'Starter workflow: Sales Ops: Score board packets. Linear flow (webhook → csv → email → log_output). Configure credentials and fields per node; extend in the canvas.',
  'CRM & Sales',
  '[{"id":"n1","type":"custom","position":{"x":100,"y":200},"data":{"type":"webhook","label":"Webhook (1)"}},{"id":"n2","type":"custom","position":{"x":360,"y":200},"data":{"type":"csv","label":"Csv (2)"}},{"id":"n3","type":"custom","position":{"x":620,"y":200},"data":{"type":"email","label":"Email (3)"}},{"id":"n4","type":"custom","position":{"x":880,"y":200},"data":{"type":"log_output","label":"Log Output (4)"}}]'::jsonb,
  '[{"id":"e1","source":"n1","target":"n2","sourceHandle":"output","targetHandle":"input"},{"id":"e2","source":"n2","target":"n3","sourceHandle":"output","targetHandle":"input"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"output","targetHandle":"input"}]'::jsonb,
  'Advanced',
  22,
  ARRAY['CRM & Sales', 'webhook', 'csv', 'email', 'log-output'],
  true,
  false,
  COALESCE((SELECT user_id FROM public.user_roles WHERE role = 'admin' LIMIT 1), (SELECT id FROM auth.users ORDER BY created_at LIMIT 1))
);


-- Template #244
INSERT INTO public.templates (name, description, category, nodes, edges, difficulty, estimated_setup_time, tags, is_active, is_featured, created_by)
VALUES (
  'Data Analytics: Normalize vendor bills',
  'Starter workflow: Data Analytics: Normalize vendor bills. Linear flow (form → notion → ai_agent → log_output). Configure credentials and fields per node; extend in the canvas.',
  'Data & BI',
  '[{"id":"n1","type":"custom","position":{"x":100,"y":200},"data":{"type":"form","label":"Form (1)"}},{"id":"n2","type":"custom","position":{"x":360,"y":200},"data":{"type":"notion","label":"Notion (2)"}},{"id":"n3","type":"custom","position":{"x":620,"y":200},"data":{"type":"ai_agent","label":"Ai Agent (3)"}},{"id":"n4","type":"custom","position":{"x":880,"y":200},"data":{"type":"log_output","label":"Log Output (4)"}}]'::jsonb,
  '[{"id":"e1","source":"n1","target":"n2","sourceHandle":"output","targetHandle":"input"},{"id":"e2","source":"n2","target":"n3","sourceHandle":"output","targetHandle":"input"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"output","targetHandle":"input"}]'::jsonb,
  'Beginner',
  23,
  ARRAY['Data & BI', 'form', 'notion', 'ai-agent', 'log-output'],
  true,
  false,
  COALESCE((SELECT user_id FROM public.user_roles WHERE role = 'admin' LIMIT 1), (SELECT id FROM auth.users ORDER BY created_at LIMIT 1))
);


-- Template #245
INSERT INTO public.templates (name, description, category, nodes, edges, difficulty, estimated_setup_time, tags, is_active, is_featured, created_by)
VALUES (
  'Security & GRC: Route prescription refills',
  'Starter workflow: Security & GRC: Route prescription refills. Linear flow (interval → ai_chat_model → text_formatter → log_output). Configure credentials and fields per node; extend in the canvas.',
  'Security',
  '[{"id":"n1","type":"custom","position":{"x":100,"y":200},"data":{"type":"interval","label":"Interval (1)"}},{"id":"n2","type":"custom","position":{"x":360,"y":200},"data":{"type":"ai_chat_model","label":"Ai Chat Model (2)"}},{"id":"n3","type":"custom","position":{"x":620,"y":200},"data":{"type":"text_formatter","label":"Text Formatter (3)"}},{"id":"n4","type":"custom","position":{"x":880,"y":200},"data":{"type":"log_output","label":"Log Output (4)"}}]'::jsonb,
  '[{"id":"e1","source":"n1","target":"n2","sourceHandle":"output","targetHandle":"input"},{"id":"e2","source":"n2","target":"n3","sourceHandle":"output","targetHandle":"input"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"output","targetHandle":"input"}]'::jsonb,
  'Intermediate',
  24,
  ARRAY['Security', 'interval', 'ai-chat-model', 'text-formatter', 'log-output'],
  true,
  false,
  COALESCE((SELECT user_id FROM public.user_roles WHERE role = 'admin' LIMIT 1), (SELECT id FROM auth.users ORDER BY created_at LIMIT 1))
);


-- Template #246
INSERT INTO public.templates (name, description, category, nodes, edges, difficulty, estimated_setup_time, tags, is_active, is_featured, created_by)
VALUES (
  'Construction: Watermark inventory deltas',
  'Starter workflow: Construction: Watermark inventory deltas. Linear flow (manual_trigger → postgresql → mysql → log_output). Configure credentials and fields per node; extend in the canvas.',
  'Construction',
  '[{"id":"n1","type":"custom","position":{"x":100,"y":200},"data":{"type":"manual_trigger","label":"Manual Trigger (1)"}},{"id":"n2","type":"custom","position":{"x":360,"y":200},"data":{"type":"postgresql","label":"Postgresql (2)"}},{"id":"n3","type":"custom","position":{"x":620,"y":200},"data":{"type":"mysql","label":"Mysql (3)"}},{"id":"n4","type":"custom","position":{"x":880,"y":200},"data":{"type":"log_output","label":"Log Output (4)"}}]'::jsonb,
  '[{"id":"e1","source":"n1","target":"n2","sourceHandle":"output","targetHandle":"input"},{"id":"e2","source":"n2","target":"n3","sourceHandle":"output","targetHandle":"input"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"output","targetHandle":"input"}]'::jsonb,
  'Advanced',
  25,
  ARRAY['Construction', 'manual-trigger', 'postgresql', 'mysql', 'log-output'],
  true,
  false,
  COALESCE((SELECT user_id FROM public.user_roles WHERE role = 'admin' LIMIT 1), (SELECT id FROM auth.users ORDER BY created_at LIMIT 1))
);


-- Template #247
INSERT INTO public.templates (name, description, category, nodes, edges, difficulty, estimated_setup_time, tags, is_active, is_featured, created_by)
VALUES (
  'Agriculture: Schedule warehouse scans',
  'Starter workflow: Agriculture: Schedule warehouse scans. Linear flow (schedule → ai_service → slack_message → log_output). Configure credentials and fields per node; extend in the canvas.',
  'Agriculture',
  '[{"id":"n1","type":"custom","position":{"x":100,"y":200},"data":{"type":"schedule","label":"Schedule (1)"}},{"id":"n2","type":"custom","position":{"x":360,"y":200},"data":{"type":"ai_service","label":"Ai Service (2)"}},{"id":"n3","type":"custom","position":{"x":620,"y":200},"data":{"type":"slack_message","label":"Slack Message (3)"}},{"id":"n4","type":"custom","position":{"x":880,"y":200},"data":{"type":"log_output","label":"Log Output (4)"}}]'::jsonb,
  '[{"id":"e1","source":"n1","target":"n2","sourceHandle":"output","targetHandle":"input"},{"id":"e2","source":"n2","target":"n3","sourceHandle":"output","targetHandle":"input"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"output","targetHandle":"input"}]'::jsonb,
  'Beginner',
  26,
  ARRAY['Agriculture', 'schedule', 'ai-service', 'slack-message', 'log-output'],
  true,
  false,
  COALESCE((SELECT user_id FROM public.user_roles WHERE role = 'admin' LIMIT 1), (SELECT id FROM auth.users ORDER BY created_at LIMIT 1))
);


-- Template #248
INSERT INTO public.templates (name, description, category, nodes, edges, difficulty, estimated_setup_time, tags, is_active, is_featured, created_by)
VALUES (
  'Energy: Publish NPS feedback',
  'Starter workflow: Energy: Publish NPS feedback. Linear flow (webhook → google_sheets → ollama → log_output). Configure credentials and fields per node; extend in the canvas.',
  'Energy',
  '[{"id":"n1","type":"custom","position":{"x":100,"y":200},"data":{"type":"webhook","label":"Webhook (1)"}},{"id":"n2","type":"custom","position":{"x":360,"y":200},"data":{"type":"google_sheets","label":"Google Sheets (2)"}},{"id":"n3","type":"custom","position":{"x":620,"y":200},"data":{"type":"ollama","label":"Ollama (3)"}},{"id":"n4","type":"custom","position":{"x":880,"y":200},"data":{"type":"log_output","label":"Log Output (4)"}}]'::jsonb,
  '[{"id":"e1","source":"n1","target":"n2","sourceHandle":"output","targetHandle":"input"},{"id":"e2","source":"n2","target":"n3","sourceHandle":"output","targetHandle":"input"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"output","targetHandle":"input"}]'::jsonb,
  'Intermediate',
  27,
  ARRAY['Energy', 'webhook', 'google-sheets', 'ollama', 'log-output'],
  true,
  false,
  COALESCE((SELECT user_id FROM public.user_roles WHERE role = 'admin' LIMIT 1), (SELECT id FROM auth.users ORDER BY created_at LIMIT 1))
);


-- Template #249
INSERT INTO public.templates (name, description, category, nodes, edges, difficulty, estimated_setup_time, tags, is_active, is_featured, created_by)
VALUES (
  'Telecom: Archive subscription renewals',
  'Starter workflow: Telecom: Archive subscription renewals. Linear flow (form → email → csv → log_output). Configure credentials and fields per node; extend in the canvas.',
  'Telecom',
  '[{"id":"n1","type":"custom","position":{"x":100,"y":200},"data":{"type":"form","label":"Form (1)"}},{"id":"n2","type":"custom","position":{"x":360,"y":200},"data":{"type":"email","label":"Email (2)"}},{"id":"n3","type":"custom","position":{"x":620,"y":200},"data":{"type":"csv","label":"Csv (3)"}},{"id":"n4","type":"custom","position":{"x":880,"y":200},"data":{"type":"log_output","label":"Log Output (4)"}}]'::jsonb,
  '[{"id":"e1","source":"n1","target":"n2","sourceHandle":"output","targetHandle":"input"},{"id":"e2","source":"n2","target":"n3","sourceHandle":"output","targetHandle":"input"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"output","targetHandle":"input"}]'::jsonb,
  'Advanced',
  28,
  ARRAY['Telecom', 'form', 'email', 'csv', 'log-output'],
  true,
  false,
  COALESCE((SELECT user_id FROM public.user_roles WHERE role = 'admin' LIMIT 1), (SELECT id FROM auth.users ORDER BY created_at LIMIT 1))
);


-- Template #250
INSERT INTO public.templates (name, description, category, nodes, edges, difficulty, estimated_setup_time, tags, is_active, is_featured, created_by)
VALUES (
  'Gov & Public Sector: Summarize IoT heartbeats',
  'Starter workflow: Gov & Public Sector: Summarize IoT heartbeats. Linear flow (interval → filter → google_drive → log_output). Configure credentials and fields per node; extend in the canvas.',
  'Public Sector',
  '[{"id":"n1","type":"custom","position":{"x":100,"y":200},"data":{"type":"interval","label":"Interval (1)"}},{"id":"n2","type":"custom","position":{"x":360,"y":200},"data":{"type":"filter","label":"Filter (2)"}},{"id":"n3","type":"custom","position":{"x":620,"y":200},"data":{"type":"google_drive","label":"Google Drive (3)"}},{"id":"n4","type":"custom","position":{"x":880,"y":200},"data":{"type":"log_output","label":"Log Output (4)"}}]'::jsonb,
  '[{"id":"e1","source":"n1","target":"n2","sourceHandle":"output","targetHandle":"input"},{"id":"e2","source":"n2","target":"n3","sourceHandle":"output","targetHandle":"input"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"output","targetHandle":"input"}]'::jsonb,
  'Beginner',
  29,
  ARRAY['Public Sector', 'interval', 'filter', 'google-drive', 'log-output'],
  true,
  false,
  COALESCE((SELECT user_id FROM public.user_roles WHERE role = 'admin' LIMIT 1), (SELECT id FROM auth.users ORDER BY created_at LIMIT 1))
);


COMMIT;
