-- =============================================================================
-- Registry-aligned template seed batch 8 of 10
-- Templates 351–400 of 500
-- Generated by ctrl_checks/scripts/generate-workflow-templates-sql.ts
-- Run 00_delete_all_templates.sql first if replacing the full catalog.
-- =============================================================================

BEGIN;

-- Template #351
INSERT INTO public.templates (name, description, category, nodes, edges, difficulty, estimated_setup_time, tags, is_active, is_featured, created_by)
VALUES (
  'E-commerce: Automate court filings',
  'Starter workflow: E-commerce: Automate court filings. Linear flow (manual_trigger → openai_gpt → ai_agent → log_output). Configure credentials and fields per node; extend in the canvas.',
  'Commerce & Retail',
  '[{"id":"n1","type":"custom","position":{"x":100,"y":200},"data":{"type":"manual_trigger","label":"Manual Trigger (1)"}},{"id":"n2","type":"custom","position":{"x":360,"y":200},"data":{"type":"openai_gpt","label":"Openai Gpt (2)"}},{"id":"n3","type":"custom","position":{"x":620,"y":200},"data":{"type":"ai_agent","label":"Ai Agent (3)"}},{"id":"n4","type":"custom","position":{"x":880,"y":200},"data":{"type":"log_output","label":"Log Output (4)"}}]'::jsonb,
  '[{"id":"e1","source":"n1","target":"n2","sourceHandle":"output","targetHandle":"input"},{"id":"e2","source":"n2","target":"n3","sourceHandle":"output","targetHandle":"input"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"output","targetHandle":"input"}]'::jsonb,
  'Advanced',
  5,
  ARRAY['Commerce & Retail', 'manual-trigger', 'openai-gpt', 'ai-agent', 'log-output'],
  true,
  false,
  COALESCE((SELECT user_id FROM public.user_roles WHERE role = 'admin' LIMIT 1), (SELECT id FROM auth.users ORDER BY created_at LIMIT 1))
);


-- Template #352
INSERT INTO public.templates (name, description, category, nodes, edges, difficulty, estimated_setup_time, tags, is_active, is_featured, created_by)
VALUES (
  'Healthcare: Deduplicate form responses',
  'Starter workflow: Healthcare: Deduplicate form responses. Linear flow (schedule → google_drive → filter → log_output). Configure credentials and fields per node; extend in the canvas.',
  'Healthcare',
  '[{"id":"n1","type":"custom","position":{"x":100,"y":200},"data":{"type":"schedule","label":"Schedule (1)"}},{"id":"n2","type":"custom","position":{"x":360,"y":200},"data":{"type":"google_drive","label":"Google Drive (2)"}},{"id":"n3","type":"custom","position":{"x":620,"y":200},"data":{"type":"filter","label":"Filter (3)"}},{"id":"n4","type":"custom","position":{"x":880,"y":200},"data":{"type":"log_output","label":"Log Output (4)"}}]'::jsonb,
  '[{"id":"e1","source":"n1","target":"n2","sourceHandle":"output","targetHandle":"input"},{"id":"e2","source":"n2","target":"n3","sourceHandle":"output","targetHandle":"input"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"output","targetHandle":"input"}]'::jsonb,
  'Beginner',
  6,
  ARRAY['Healthcare', 'schedule', 'google-drive', 'filter', 'log-output'],
  true,
  false,
  COALESCE((SELECT user_id FROM public.user_roles WHERE role = 'admin' LIMIT 1), (SELECT id FROM auth.users ORDER BY created_at LIMIT 1))
);


-- Template #353
INSERT INTO public.templates (name, description, category, nodes, edges, difficulty, estimated_setup_time, tags, is_active, is_featured, created_by)
VALUES (
  'Finance & Accounting: Parse sensor readings',
  'Starter workflow: Finance & Accounting: Parse sensor readings. Linear flow (webhook → twitter → google_calendar → log_output). Configure credentials and fields per node; extend in the canvas.',
  'Finance',
  '[{"id":"n1","type":"custom","position":{"x":100,"y":200},"data":{"type":"webhook","label":"Webhook (1)"}},{"id":"n2","type":"custom","position":{"x":360,"y":200},"data":{"type":"twitter","label":"Twitter (2)"}},{"id":"n3","type":"custom","position":{"x":620,"y":200},"data":{"type":"google_calendar","label":"Google Calendar (3)"}},{"id":"n4","type":"custom","position":{"x":880,"y":200},"data":{"type":"log_output","label":"Log Output (4)"}}]'::jsonb,
  '[{"id":"e1","source":"n1","target":"n2","sourceHandle":"output","targetHandle":"input"},{"id":"e2","source":"n2","target":"n3","sourceHandle":"output","targetHandle":"input"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"output","targetHandle":"input"}]'::jsonb,
  'Intermediate',
  7,
  ARRAY['Finance', 'webhook', 'twitter', 'google-calendar', 'log-output'],
  true,
  false,
  COALESCE((SELECT user_id FROM public.user_roles WHERE role = 'admin' LIMIT 1), (SELECT id FROM auth.users ORDER BY created_at LIMIT 1))
);


-- Template #354
INSERT INTO public.templates (name, description, category, nodes, edges, difficulty, estimated_setup_time, tags, is_active, is_featured, created_by)
VALUES (
  'HR & People: Monitor compliance exports',
  'Starter workflow: HR & People: Monitor compliance exports. Linear flow (form → function → clickup → log_output). Configure credentials and fields per node; extend in the canvas.',
  'HR',
  '[{"id":"n1","type":"custom","position":{"x":100,"y":200},"data":{"type":"form","label":"Form (1)"}},{"id":"n2","type":"custom","position":{"x":360,"y":200},"data":{"type":"function","label":"Function (2)"}},{"id":"n3","type":"custom","position":{"x":620,"y":200},"data":{"type":"clickup","label":"Clickup (3)"}},{"id":"n4","type":"custom","position":{"x":880,"y":200},"data":{"type":"log_output","label":"Log Output (4)"}}]'::jsonb,
  '[{"id":"e1","source":"n1","target":"n2","sourceHandle":"output","targetHandle":"input"},{"id":"e2","source":"n2","target":"n3","sourceHandle":"output","targetHandle":"input"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"output","targetHandle":"input"}]'::jsonb,
  'Advanced',
  8,
  ARRAY['HR', 'form', 'function', 'clickup', 'log-output'],
  true,
  false,
  COALESCE((SELECT user_id FROM public.user_roles WHERE role = 'admin' LIMIT 1), (SELECT id FROM auth.users ORDER BY created_at LIMIT 1))
);


-- Template #355
INSERT INTO public.templates (name, description, category, nodes, edges, difficulty, estimated_setup_time, tags, is_active, is_featured, created_by)
VALUES (
  'DevOps & SRE: Aggregate feature flags',
  'Starter workflow: DevOps & SRE: Aggregate feature flags. Linear flow (interval → slack_message → ai_service → log_output). Configure credentials and fields per node; extend in the canvas.',
  'Developer Tools',
  '[{"id":"n1","type":"custom","position":{"x":100,"y":200},"data":{"type":"interval","label":"Interval (1)"}},{"id":"n2","type":"custom","position":{"x":360,"y":200},"data":{"type":"slack_message","label":"Slack Message (2)"}},{"id":"n3","type":"custom","position":{"x":620,"y":200},"data":{"type":"ai_service","label":"Ai Service (3)"}},{"id":"n4","type":"custom","position":{"x":880,"y":200},"data":{"type":"log_output","label":"Log Output (4)"}}]'::jsonb,
  '[{"id":"e1","source":"n1","target":"n2","sourceHandle":"output","targetHandle":"input"},{"id":"e2","source":"n2","target":"n3","sourceHandle":"output","targetHandle":"input"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"output","targetHandle":"input"}]'::jsonb,
  'Beginner',
  9,
  ARRAY['Developer Tools', 'interval', 'slack-message', 'ai-service', 'log-output'],
  true,
  false,
  COALESCE((SELECT user_id FROM public.user_roles WHERE role = 'admin' LIMIT 1), (SELECT id FROM auth.users ORDER BY created_at LIMIT 1))
);


-- Template #356
INSERT INTO public.templates (name, description, category, nodes, edges, difficulty, estimated_setup_time, tags, is_active, is_featured, created_by)
VALUES (
  'Marketing: Validate asset depreciations',
  'Starter workflow: Marketing: Validate asset depreciations. Linear flow (manual_trigger → json_parser → csv → log_output). Configure credentials and fields per node; extend in the canvas.',
  'Marketing & Growth',
  '[{"id":"n1","type":"custom","position":{"x":100,"y":200},"data":{"type":"manual_trigger","label":"Manual Trigger (1)"}},{"id":"n2","type":"custom","position":{"x":360,"y":200},"data":{"type":"json_parser","label":"Json Parser (2)"}},{"id":"n3","type":"custom","position":{"x":620,"y":200},"data":{"type":"csv","label":"Csv (3)"}},{"id":"n4","type":"custom","position":{"x":880,"y":200},"data":{"type":"log_output","label":"Log Output (4)"}}]'::jsonb,
  '[{"id":"e1","source":"n1","target":"n2","sourceHandle":"output","targetHandle":"input"},{"id":"e2","source":"n2","target":"n3","sourceHandle":"output","targetHandle":"input"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"output","targetHandle":"input"}]'::jsonb,
  'Intermediate',
  10,
  ARRAY['Marketing & Growth', 'manual-trigger', 'json-parser', 'csv', 'log-output'],
  true,
  false,
  COALESCE((SELECT user_id FROM public.user_roles WHERE role = 'admin' LIMIT 1), (SELECT id FROM auth.users ORDER BY created_at LIMIT 1))
);


-- Template #357
INSERT INTO public.templates (name, description, category, nodes, edges, difficulty, estimated_setup_time, tags, is_active, is_featured, created_by)
VALUES (
  'Customer Support: Reconcile webhook payloads',
  'Starter workflow: Customer Support: Reconcile webhook payloads. Linear flow (schedule → airtable → google_gmail → log_output). Configure credentials and fields per node; extend in the canvas.',
  'Support',
  '[{"id":"n1","type":"custom","position":{"x":100,"y":200},"data":{"type":"schedule","label":"Schedule (1)"}},{"id":"n2","type":"custom","position":{"x":360,"y":200},"data":{"type":"airtable","label":"Airtable (2)"}},{"id":"n3","type":"custom","position":{"x":620,"y":200},"data":{"type":"google_gmail","label":"Google Gmail (3)"}},{"id":"n4","type":"custom","position":{"x":880,"y":200},"data":{"type":"log_output","label":"Log Output (4)"}}]'::jsonb,
  '[{"id":"e1","source":"n1","target":"n2","sourceHandle":"output","targetHandle":"input"},{"id":"e2","source":"n2","target":"n3","sourceHandle":"output","targetHandle":"input"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"output","targetHandle":"input"}]'::jsonb,
  'Advanced',
  11,
  ARRAY['Support', 'schedule', 'airtable', 'google-gmail', 'log-output'],
  true,
  false,
  COALESCE((SELECT user_id FROM public.user_roles WHERE role = 'admin' LIMIT 1), (SELECT id FROM auth.users ORDER BY created_at LIMIT 1))
);


-- Template #358
INSERT INTO public.templates (name, description, category, nodes, edges, difficulty, estimated_setup_time, tags, is_active, is_featured, created_by)
VALUES (
  'Education: Notify stakeholders about shipment events',
  'Starter workflow: Education: Notify stakeholders about shipment events. Linear flow (webhook → ai_agent → notion → log_output). Configure credentials and fields per node; extend in the canvas.',
  'Education',
  '[{"id":"n1","type":"custom","position":{"x":100,"y":200},"data":{"type":"webhook","label":"Webhook (1)"}},{"id":"n2","type":"custom","position":{"x":360,"y":200},"data":{"type":"ai_agent","label":"Ai Agent (2)"}},{"id":"n3","type":"custom","position":{"x":620,"y":200},"data":{"type":"notion","label":"Notion (3)"}},{"id":"n4","type":"custom","position":{"x":880,"y":200},"data":{"type":"log_output","label":"Log Output (4)"}}]'::jsonb,
  '[{"id":"e1","source":"n1","target":"n2","sourceHandle":"output","targetHandle":"input"},{"id":"e2","source":"n2","target":"n3","sourceHandle":"output","targetHandle":"input"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"output","targetHandle":"input"}]'::jsonb,
  'Beginner',
  12,
  ARRAY['Education', 'webhook', 'ai-agent', 'notion', 'log-output'],
  true,
  false,
  COALESCE((SELECT user_id FROM public.user_roles WHERE role = 'admin' LIMIT 1), (SELECT id FROM auth.users ORDER BY created_at LIMIT 1))
);


-- Template #359
INSERT INTO public.templates (name, description, category, nodes, edges, difficulty, estimated_setup_time, tags, is_active, is_featured, created_by)
VALUES (
  'Real Estate: Tag and classify security findings',
  'Starter workflow: Real Estate: Tag and classify security findings. Linear flow (form → google_calendar → twitter → log_output). Configure credentials and fields per node; extend in the canvas.',
  'Real Estate',
  '[{"id":"n1","type":"custom","position":{"x":100,"y":200},"data":{"type":"form","label":"Form (1)"}},{"id":"n2","type":"custom","position":{"x":360,"y":200},"data":{"type":"google_calendar","label":"Google Calendar (2)"}},{"id":"n3","type":"custom","position":{"x":620,"y":200},"data":{"type":"twitter","label":"Twitter (3)"}},{"id":"n4","type":"custom","position":{"x":880,"y":200},"data":{"type":"log_output","label":"Log Output (4)"}}]'::jsonb,
  '[{"id":"e1","source":"n1","target":"n2","sourceHandle":"output","targetHandle":"input"},{"id":"e2","source":"n2","target":"n3","sourceHandle":"output","targetHandle":"input"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"output","targetHandle":"input"}]'::jsonb,
  'Intermediate',
  13,
  ARRAY['Real Estate', 'form', 'google-calendar', 'twitter', 'log-output'],
  true,
  false,
  COALESCE((SELECT user_id FROM public.user_roles WHERE role = 'admin' LIMIT 1), (SELECT id FROM auth.users ORDER BY created_at LIMIT 1))
);


-- Template #360
INSERT INTO public.templates (name, description, category, nodes, edges, difficulty, estimated_setup_time, tags, is_active, is_featured, created_by)
VALUES (
  'Legal Ops: Handshake release notes',
  'Starter workflow: Legal Ops: Handshake release notes. Linear flow (interval → linkedin → set_variable → log_output). Configure credentials and fields per node; extend in the canvas.',
  'Legal',
  '[{"id":"n1","type":"custom","position":{"x":100,"y":200},"data":{"type":"interval","label":"Interval (1)"}},{"id":"n2","type":"custom","position":{"x":360,"y":200},"data":{"type":"linkedin","label":"Linkedin (2)"}},{"id":"n3","type":"custom","position":{"x":620,"y":200},"data":{"type":"set_variable","label":"Set Variable (3)"}},{"id":"n4","type":"custom","position":{"x":880,"y":200},"data":{"type":"log_output","label":"Log Output (4)"}}]'::jsonb,
  '[{"id":"e1","source":"n1","target":"n2","sourceHandle":"output","targetHandle":"input"},{"id":"e2","source":"n2","target":"n3","sourceHandle":"output","targetHandle":"input"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"output","targetHandle":"input"}]'::jsonb,
  'Advanced',
  14,
  ARRAY['Legal', 'interval', 'linkedin', 'set-variable', 'log-output'],
  true,
  false,
  COALESCE((SELECT user_id FROM public.user_roles WHERE role = 'admin' LIMIT 1), (SELECT id FROM auth.users ORDER BY created_at LIMIT 1))
);


-- Template #361
INSERT INTO public.templates (name, description, category, nodes, edges, difficulty, estimated_setup_time, tags, is_active, is_featured, created_by)
VALUES (
  'Manufacturing: Enrich course enrollments',
  'Starter workflow: Manufacturing: Enrich course enrollments. Linear flow (manual_trigger → http_request → google_sheets → log_output). Configure credentials and fields per node; extend in the canvas.',
  'Operations',
  '[{"id":"n1","type":"custom","position":{"x":100,"y":200},"data":{"type":"manual_trigger","label":"Manual Trigger (1)"}},{"id":"n2","type":"custom","position":{"x":360,"y":200},"data":{"type":"http_request","label":"Http Request (2)"}},{"id":"n3","type":"custom","position":{"x":620,"y":200},"data":{"type":"google_sheets","label":"Google Sheets (3)"}},{"id":"n4","type":"custom","position":{"x":880,"y":200},"data":{"type":"log_output","label":"Log Output (4)"}}]'::jsonb,
  '[{"id":"e1","source":"n1","target":"n2","sourceHandle":"output","targetHandle":"input"},{"id":"e2","source":"n2","target":"n3","sourceHandle":"output","targetHandle":"input"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"output","targetHandle":"input"}]'::jsonb,
  'Beginner',
  15,
  ARRAY['Operations', 'manual-trigger', 'http-request', 'google-sheets', 'log-output'],
  true,
  false,
  COALESCE((SELECT user_id FROM public.user_roles WHERE role = 'admin' LIMIT 1), (SELECT id FROM auth.users ORDER BY created_at LIMIT 1))
);


-- Template #362
INSERT INTO public.templates (name, description, category, nodes, edges, difficulty, estimated_setup_time, tags, is_active, is_featured, created_by)
VALUES (
  'Nonprofit: Redact daily KPIs',
  'Starter workflow: Nonprofit: Redact daily KPIs. Linear flow (schedule → telegram → mongodb → log_output). Configure credentials and fields per node; extend in the canvas.',
  'Nonprofit',
  '[{"id":"n1","type":"custom","position":{"x":100,"y":200},"data":{"type":"schedule","label":"Schedule (1)"}},{"id":"n2","type":"custom","position":{"x":360,"y":200},"data":{"type":"telegram","label":"Telegram (2)"}},{"id":"n3","type":"custom","position":{"x":620,"y":200},"data":{"type":"mongodb","label":"Mongodb (3)"}},{"id":"n4","type":"custom","position":{"x":880,"y":200},"data":{"type":"log_output","label":"Log Output (4)"}}]'::jsonb,
  '[{"id":"e1","source":"n1","target":"n2","sourceHandle":"output","targetHandle":"input"},{"id":"e2","source":"n2","target":"n3","sourceHandle":"output","targetHandle":"input"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"output","targetHandle":"input"}]'::jsonb,
  'Intermediate',
  16,
  ARRAY['Nonprofit', 'schedule', 'telegram', 'mongodb', 'log-output'],
  true,
  false,
  COALESCE((SELECT user_id FROM public.user_roles WHERE role = 'admin' LIMIT 1), (SELECT id FROM auth.users ORDER BY created_at LIMIT 1))
);


-- Template #363
INSERT INTO public.templates (name, description, category, nodes, edges, difficulty, estimated_setup_time, tags, is_active, is_featured, created_by)
VALUES (
  'Media & Publishing: Extract metrics from social mentions',
  'Starter workflow: Media & Publishing: Extract metrics from social mentions. Linear flow (webhook → csv → email → log_output). Configure credentials and fields per node; extend in the canvas.',
  'Media',
  '[{"id":"n1","type":"custom","position":{"x":100,"y":200},"data":{"type":"webhook","label":"Webhook (1)"}},{"id":"n2","type":"custom","position":{"x":360,"y":200},"data":{"type":"csv","label":"Csv (2)"}},{"id":"n3","type":"custom","position":{"x":620,"y":200},"data":{"type":"email","label":"Email (3)"}},{"id":"n4","type":"custom","position":{"x":880,"y":200},"data":{"type":"log_output","label":"Log Output (4)"}}]'::jsonb,
  '[{"id":"e1","source":"n1","target":"n2","sourceHandle":"output","targetHandle":"input"},{"id":"e2","source":"n2","target":"n3","sourceHandle":"output","targetHandle":"input"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"output","targetHandle":"input"}]'::jsonb,
  'Advanced',
  17,
  ARRAY['Media', 'webhook', 'csv', 'email', 'log-output'],
  true,
  false,
  COALESCE((SELECT user_id FROM public.user_roles WHERE role = 'admin' LIMIT 1), (SELECT id FROM auth.users ORDER BY created_at LIMIT 1))
);


-- Template #364
INSERT INTO public.templates (name, description, category, nodes, edges, difficulty, estimated_setup_time, tags, is_active, is_featured, created_by)
VALUES (
  'Logistics: Triage partner SLAs',
  'Starter workflow: Logistics: Triage partner SLAs. Linear flow (form → notion → ai_agent → log_output). Configure credentials and fields per node; extend in the canvas.',
  'Logistics',
  '[{"id":"n1","type":"custom","position":{"x":100,"y":200},"data":{"type":"form","label":"Form (1)"}},{"id":"n2","type":"custom","position":{"x":360,"y":200},"data":{"type":"notion","label":"Notion (2)"}},{"id":"n3","type":"custom","position":{"x":620,"y":200},"data":{"type":"ai_agent","label":"Ai Agent (3)"}},{"id":"n4","type":"custom","position":{"x":880,"y":200},"data":{"type":"log_output","label":"Log Output (4)"}}]'::jsonb,
  '[{"id":"e1","source":"n1","target":"n2","sourceHandle":"output","targetHandle":"input"},{"id":"e2","source":"n2","target":"n3","sourceHandle":"output","targetHandle":"input"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"output","targetHandle":"input"}]'::jsonb,
  'Beginner',
  18,
  ARRAY['Logistics', 'form', 'notion', 'ai-agent', 'log-output'],
  true,
  false,
  COALESCE((SELECT user_id FROM public.user_roles WHERE role = 'admin' LIMIT 1), (SELECT id FROM auth.users ORDER BY created_at LIMIT 1))
);


-- Template #365
INSERT INTO public.templates (name, description, category, nodes, edges, difficulty, estimated_setup_time, tags, is_active, is_featured, created_by)
VALUES (
  'Hospitality: Transform on-call incidents',
  'Starter workflow: Hospitality: Transform on-call incidents. Linear flow (interval → ai_chat_model → text_formatter → log_output). Configure credentials and fields per node; extend in the canvas.',
  'Hospitality',
  '[{"id":"n1","type":"custom","position":{"x":100,"y":200},"data":{"type":"interval","label":"Interval (1)"}},{"id":"n2","type":"custom","position":{"x":360,"y":200},"data":{"type":"ai_chat_model","label":"Ai Chat Model (2)"}},{"id":"n3","type":"custom","position":{"x":620,"y":200},"data":{"type":"text_formatter","label":"Text Formatter (3)"}},{"id":"n4","type":"custom","position":{"x":880,"y":200},"data":{"type":"log_output","label":"Log Output (4)"}}]'::jsonb,
  '[{"id":"e1","source":"n1","target":"n2","sourceHandle":"output","targetHandle":"input"},{"id":"e2","source":"n2","target":"n3","sourceHandle":"output","targetHandle":"input"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"output","targetHandle":"input"}]'::jsonb,
  'Intermediate',
  19,
  ARRAY['Hospitality', 'interval', 'ai-chat-model', 'text-formatter', 'log-output'],
  true,
  false,
  COALESCE((SELECT user_id FROM public.user_roles WHERE role = 'admin' LIMIT 1), (SELECT id FROM auth.users ORDER BY created_at LIMIT 1))
);


-- Template #366
INSERT INTO public.templates (name, description, category, nodes, edges, difficulty, estimated_setup_time, tags, is_active, is_featured, created_by)
VALUES (
  'SaaS Product: Back up room bookings',
  'Starter workflow: SaaS Product: Back up room bookings. Linear flow (manual_trigger → postgresql → mysql → log_output). Configure credentials and fields per node; extend in the canvas.',
  'Product',
  '[{"id":"n1","type":"custom","position":{"x":100,"y":200},"data":{"type":"manual_trigger","label":"Manual Trigger (1)"}},{"id":"n2","type":"custom","position":{"x":360,"y":200},"data":{"type":"postgresql","label":"Postgresql (2)"}},{"id":"n3","type":"custom","position":{"x":620,"y":200},"data":{"type":"mysql","label":"Mysql (3)"}},{"id":"n4","type":"custom","position":{"x":880,"y":200},"data":{"type":"log_output","label":"Log Output (4)"}}]'::jsonb,
  '[{"id":"e1","source":"n1","target":"n2","sourceHandle":"output","targetHandle":"input"},{"id":"e2","source":"n2","target":"n3","sourceHandle":"output","targetHandle":"input"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"output","targetHandle":"input"}]'::jsonb,
  'Advanced',
  20,
  ARRAY['Product', 'manual-trigger', 'postgresql', 'mysql', 'log-output'],
  true,
  false,
  COALESCE((SELECT user_id FROM public.user_roles WHERE role = 'admin' LIMIT 1), (SELECT id FROM auth.users ORDER BY created_at LIMIT 1))
);


-- Template #367
INSERT INTO public.templates (name, description, category, nodes, edges, difficulty, estimated_setup_time, tags, is_active, is_featured, created_by)
VALUES (
  'IT Service Desk: Sync calendar holds',
  'Starter workflow: IT Service Desk: Sync calendar holds. Linear flow (schedule → ai_service → slack_message → log_output). Configure credentials and fields per node; extend in the canvas.',
  'IT',
  '[{"id":"n1","type":"custom","position":{"x":100,"y":200},"data":{"type":"schedule","label":"Schedule (1)"}},{"id":"n2","type":"custom","position":{"x":360,"y":200},"data":{"type":"ai_service","label":"Ai Service (2)"}},{"id":"n3","type":"custom","position":{"x":620,"y":200},"data":{"type":"slack_message","label":"Slack Message (3)"}},{"id":"n4","type":"custom","position":{"x":880,"y":200},"data":{"type":"log_output","label":"Log Output (4)"}}]'::jsonb,
  '[{"id":"e1","source":"n1","target":"n2","sourceHandle":"output","targetHandle":"input"},{"id":"e2","source":"n2","target":"n3","sourceHandle":"output","targetHandle":"input"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"output","targetHandle":"input"}]'::jsonb,
  'Beginner',
  21,
  ARRAY['IT', 'schedule', 'ai-service', 'slack-message', 'log-output'],
  true,
  false,
  COALESCE((SELECT user_id FROM public.user_roles WHERE role = 'admin' LIMIT 1), (SELECT id FROM auth.users ORDER BY created_at LIMIT 1))
);


-- Template #368
INSERT INTO public.templates (name, description, category, nodes, edges, difficulty, estimated_setup_time, tags, is_active, is_featured, created_by)
VALUES (
  'Sales Ops: Score help-center articles',
  'Starter workflow: Sales Ops: Score help-center articles. Linear flow (webhook → google_sheets → ollama → log_output). Configure credentials and fields per node; extend in the canvas.',
  'CRM & Sales',
  '[{"id":"n1","type":"custom","position":{"x":100,"y":200},"data":{"type":"webhook","label":"Webhook (1)"}},{"id":"n2","type":"custom","position":{"x":360,"y":200},"data":{"type":"google_sheets","label":"Google Sheets (2)"}},{"id":"n3","type":"custom","position":{"x":620,"y":200},"data":{"type":"ollama","label":"Ollama (3)"}},{"id":"n4","type":"custom","position":{"x":880,"y":200},"data":{"type":"log_output","label":"Log Output (4)"}}]'::jsonb,
  '[{"id":"e1","source":"n1","target":"n2","sourceHandle":"output","targetHandle":"input"},{"id":"e2","source":"n2","target":"n3","sourceHandle":"output","targetHandle":"input"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"output","targetHandle":"input"}]'::jsonb,
  'Intermediate',
  22,
  ARRAY['CRM & Sales', 'webhook', 'google-sheets', 'ollama', 'log-output'],
  true,
  false,
  COALESCE((SELECT user_id FROM public.user_roles WHERE role = 'admin' LIMIT 1), (SELECT id FROM auth.users ORDER BY created_at LIMIT 1))
);


-- Template #369
INSERT INTO public.templates (name, description, category, nodes, edges, difficulty, estimated_setup_time, tags, is_active, is_featured, created_by)
VALUES (
  'Data Analytics: Normalize board packets',
  'Starter workflow: Data Analytics: Normalize board packets. Linear flow (form → email → csv → log_output). Configure credentials and fields per node; extend in the canvas.',
  'Data & BI',
  '[{"id":"n1","type":"custom","position":{"x":100,"y":200},"data":{"type":"form","label":"Form (1)"}},{"id":"n2","type":"custom","position":{"x":360,"y":200},"data":{"type":"email","label":"Email (2)"}},{"id":"n3","type":"custom","position":{"x":620,"y":200},"data":{"type":"csv","label":"Csv (3)"}},{"id":"n4","type":"custom","position":{"x":880,"y":200},"data":{"type":"log_output","label":"Log Output (4)"}}]'::jsonb,
  '[{"id":"e1","source":"n1","target":"n2","sourceHandle":"output","targetHandle":"input"},{"id":"e2","source":"n2","target":"n3","sourceHandle":"output","targetHandle":"input"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"output","targetHandle":"input"}]'::jsonb,
  'Advanced',
  23,
  ARRAY['Data & BI', 'form', 'email', 'csv', 'log-output'],
  true,
  true,
  COALESCE((SELECT user_id FROM public.user_roles WHERE role = 'admin' LIMIT 1), (SELECT id FROM auth.users ORDER BY created_at LIMIT 1))
);


-- Template #370
INSERT INTO public.templates (name, description, category, nodes, edges, difficulty, estimated_setup_time, tags, is_active, is_featured, created_by)
VALUES (
  'Security & GRC: Route vendor bills',
  'Starter workflow: Security & GRC: Route vendor bills. Linear flow (interval → filter → google_drive → log_output). Configure credentials and fields per node; extend in the canvas.',
  'Security',
  '[{"id":"n1","type":"custom","position":{"x":100,"y":200},"data":{"type":"interval","label":"Interval (1)"}},{"id":"n2","type":"custom","position":{"x":360,"y":200},"data":{"type":"filter","label":"Filter (2)"}},{"id":"n3","type":"custom","position":{"x":620,"y":200},"data":{"type":"google_drive","label":"Google Drive (3)"}},{"id":"n4","type":"custom","position":{"x":880,"y":200},"data":{"type":"log_output","label":"Log Output (4)"}}]'::jsonb,
  '[{"id":"e1","source":"n1","target":"n2","sourceHandle":"output","targetHandle":"input"},{"id":"e2","source":"n2","target":"n3","sourceHandle":"output","targetHandle":"input"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"output","targetHandle":"input"}]'::jsonb,
  'Beginner',
  24,
  ARRAY['Security', 'interval', 'filter', 'google-drive', 'log-output'],
  true,
  false,
  COALESCE((SELECT user_id FROM public.user_roles WHERE role = 'admin' LIMIT 1), (SELECT id FROM auth.users ORDER BY created_at LIMIT 1))
);


-- Template #371
INSERT INTO public.templates (name, description, category, nodes, edges, difficulty, estimated_setup_time, tags, is_active, is_featured, created_by)
VALUES (
  'Construction: Watermark prescription refills',
  'Starter workflow: Construction: Watermark prescription refills. Linear flow (manual_trigger → hubspot → clickup → log_output). Configure credentials and fields per node; extend in the canvas.',
  'Construction',
  '[{"id":"n1","type":"custom","position":{"x":100,"y":200},"data":{"type":"manual_trigger","label":"Manual Trigger (1)"}},{"id":"n2","type":"custom","position":{"x":360,"y":200},"data":{"type":"hubspot","label":"Hubspot (2)"}},{"id":"n3","type":"custom","position":{"x":620,"y":200},"data":{"type":"clickup","label":"Clickup (3)"}},{"id":"n4","type":"custom","position":{"x":880,"y":200},"data":{"type":"log_output","label":"Log Output (4)"}}]'::jsonb,
  '[{"id":"e1","source":"n1","target":"n2","sourceHandle":"output","targetHandle":"input"},{"id":"e2","source":"n2","target":"n3","sourceHandle":"output","targetHandle":"input"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"output","targetHandle":"input"}]'::jsonb,
  'Intermediate',
  25,
  ARRAY['Construction', 'manual-trigger', 'hubspot', 'clickup', 'log-output'],
  true,
  false,
  COALESCE((SELECT user_id FROM public.user_roles WHERE role = 'admin' LIMIT 1), (SELECT id FROM auth.users ORDER BY created_at LIMIT 1))
);


-- Template #372
INSERT INTO public.templates (name, description, category, nodes, edges, difficulty, estimated_setup_time, tags, is_active, is_featured, created_by)
VALUES (
  'Agriculture: Schedule inventory deltas',
  'Starter workflow: Agriculture: Schedule inventory deltas. Linear flow (schedule → set_variable → linkedin → log_output). Configure credentials and fields per node; extend in the canvas.',
  'Agriculture',
  '[{"id":"n1","type":"custom","position":{"x":100,"y":200},"data":{"type":"schedule","label":"Schedule (1)"}},{"id":"n2","type":"custom","position":{"x":360,"y":200},"data":{"type":"set_variable","label":"Set Variable (2)"}},{"id":"n3","type":"custom","position":{"x":620,"y":200},"data":{"type":"linkedin","label":"Linkedin (3)"}},{"id":"n4","type":"custom","position":{"x":880,"y":200},"data":{"type":"log_output","label":"Log Output (4)"}}]'::jsonb,
  '[{"id":"e1","source":"n1","target":"n2","sourceHandle":"output","targetHandle":"input"},{"id":"e2","source":"n2","target":"n3","sourceHandle":"output","targetHandle":"input"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"output","targetHandle":"input"}]'::jsonb,
  'Advanced',
  26,
  ARRAY['Agriculture', 'schedule', 'set-variable', 'linkedin', 'log-output'],
  true,
  false,
  COALESCE((SELECT user_id FROM public.user_roles WHERE role = 'admin' LIMIT 1), (SELECT id FROM auth.users ORDER BY created_at LIMIT 1))
);


-- Template #373
INSERT INTO public.templates (name, description, category, nodes, edges, difficulty, estimated_setup_time, tags, is_active, is_featured, created_by)
VALUES (
  'Energy: Publish warehouse scans',
  'Starter workflow: Energy: Publish warehouse scans. Linear flow (webhook → mysql → javascript → log_output). Configure credentials and fields per node; extend in the canvas.',
  'Energy',
  '[{"id":"n1","type":"custom","position":{"x":100,"y":200},"data":{"type":"webhook","label":"Webhook (1)"}},{"id":"n2","type":"custom","position":{"x":360,"y":200},"data":{"type":"mysql","label":"Mysql (2)"}},{"id":"n3","type":"custom","position":{"x":620,"y":200},"data":{"type":"javascript","label":"Javascript (3)"}},{"id":"n4","type":"custom","position":{"x":880,"y":200},"data":{"type":"log_output","label":"Log Output (4)"}}]'::jsonb,
  '[{"id":"e1","source":"n1","target":"n2","sourceHandle":"output","targetHandle":"input"},{"id":"e2","source":"n2","target":"n3","sourceHandle":"output","targetHandle":"input"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"output","targetHandle":"input"}]'::jsonb,
  'Beginner',
  27,
  ARRAY['Energy', 'webhook', 'mysql', 'javascript', 'log-output'],
  true,
  false,
  COALESCE((SELECT user_id FROM public.user_roles WHERE role = 'admin' LIMIT 1), (SELECT id FROM auth.users ORDER BY created_at LIMIT 1))
);


-- Template #374
INSERT INTO public.templates (name, description, category, nodes, edges, difficulty, estimated_setup_time, tags, is_active, is_featured, created_by)
VALUES (
  'Telecom: Archive NPS feedback',
  'Starter workflow: Telecom: Archive NPS feedback. Linear flow (form → ollama → google_sheets → log_output). Configure credentials and fields per node; extend in the canvas.',
  'Telecom',
  '[{"id":"n1","type":"custom","position":{"x":100,"y":200},"data":{"type":"form","label":"Form (1)"}},{"id":"n2","type":"custom","position":{"x":360,"y":200},"data":{"type":"ollama","label":"Ollama (2)"}},{"id":"n3","type":"custom","position":{"x":620,"y":200},"data":{"type":"google_sheets","label":"Google Sheets (3)"}},{"id":"n4","type":"custom","position":{"x":880,"y":200},"data":{"type":"log_output","label":"Log Output (4)"}}]'::jsonb,
  '[{"id":"e1","source":"n1","target":"n2","sourceHandle":"output","targetHandle":"input"},{"id":"e2","source":"n2","target":"n3","sourceHandle":"output","targetHandle":"input"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"output","targetHandle":"input"}]'::jsonb,
  'Intermediate',
  28,
  ARRAY['Telecom', 'form', 'ollama', 'google-sheets', 'log-output'],
  true,
  false,
  COALESCE((SELECT user_id FROM public.user_roles WHERE role = 'admin' LIMIT 1), (SELECT id FROM auth.users ORDER BY created_at LIMIT 1))
);


-- Template #375
INSERT INTO public.templates (name, description, category, nodes, edges, difficulty, estimated_setup_time, tags, is_active, is_featured, created_by)
VALUES (
  'Gov & Public Sector: Summarize subscription renewals',
  'Starter workflow: Gov & Public Sector: Summarize subscription renewals. Linear flow (interval → google_gmail → airtable → log_output). Configure credentials and fields per node; extend in the canvas.',
  'Public Sector',
  '[{"id":"n1","type":"custom","position":{"x":100,"y":200},"data":{"type":"interval","label":"Interval (1)"}},{"id":"n2","type":"custom","position":{"x":360,"y":200},"data":{"type":"google_gmail","label":"Google Gmail (2)"}},{"id":"n3","type":"custom","position":{"x":620,"y":200},"data":{"type":"airtable","label":"Airtable (3)"}},{"id":"n4","type":"custom","position":{"x":880,"y":200},"data":{"type":"log_output","label":"Log Output (4)"}}]'::jsonb,
  '[{"id":"e1","source":"n1","target":"n2","sourceHandle":"output","targetHandle":"input"},{"id":"e2","source":"n2","target":"n3","sourceHandle":"output","targetHandle":"input"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"output","targetHandle":"input"}]'::jsonb,
  'Advanced',
  29,
  ARRAY['Public Sector', 'interval', 'google-gmail', 'airtable', 'log-output'],
  true,
  false,
  COALESCE((SELECT user_id FROM public.user_roles WHERE role = 'admin' LIMIT 1), (SELECT id FROM auth.users ORDER BY created_at LIMIT 1))
);


-- Template #376
INSERT INTO public.templates (name, description, category, nodes, edges, difficulty, estimated_setup_time, tags, is_active, is_featured, created_by)
VALUES (
  'E-commerce: Automate IoT heartbeats',
  'Starter workflow: E-commerce: Automate IoT heartbeats. Linear flow (manual_trigger → outlook → twitter → log_output). Configure credentials and fields per node; extend in the canvas.',
  'Commerce & Retail',
  '[{"id":"n1","type":"custom","position":{"x":100,"y":200},"data":{"type":"manual_trigger","label":"Manual Trigger (1)"}},{"id":"n2","type":"custom","position":{"x":360,"y":200},"data":{"type":"outlook","label":"Outlook (2)"}},{"id":"n3","type":"custom","position":{"x":620,"y":200},"data":{"type":"twitter","label":"Twitter (3)"}},{"id":"n4","type":"custom","position":{"x":880,"y":200},"data":{"type":"log_output","label":"Log Output (4)"}}]'::jsonb,
  '[{"id":"e1","source":"n1","target":"n2","sourceHandle":"output","targetHandle":"input"},{"id":"e2","source":"n2","target":"n3","sourceHandle":"output","targetHandle":"input"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"output","targetHandle":"input"}]'::jsonb,
  'Beginner',
  5,
  ARRAY['Commerce & Retail', 'manual-trigger', 'outlook', 'twitter', 'log-output'],
  true,
  false,
  COALESCE((SELECT user_id FROM public.user_roles WHERE role = 'admin' LIMIT 1), (SELECT id FROM auth.users ORDER BY created_at LIMIT 1))
);


-- Template #377
INSERT INTO public.templates (name, description, category, nodes, edges, difficulty, estimated_setup_time, tags, is_active, is_featured, created_by)
VALUES (
  'Healthcare: Deduplicate invoice lines',
  'Starter workflow: Healthcare: Deduplicate invoice lines. Linear flow (schedule → text_formatter → ai_chat_model → log_output). Configure credentials and fields per node; extend in the canvas.',
  'Healthcare',
  '[{"id":"n1","type":"custom","position":{"x":100,"y":200},"data":{"type":"schedule","label":"Schedule (1)"}},{"id":"n2","type":"custom","position":{"x":360,"y":200},"data":{"type":"text_formatter","label":"Text Formatter (2)"}},{"id":"n3","type":"custom","position":{"x":620,"y":200},"data":{"type":"ai_chat_model","label":"Ai Chat Model (3)"}},{"id":"n4","type":"custom","position":{"x":880,"y":200},"data":{"type":"log_output","label":"Log Output (4)"}}]'::jsonb,
  '[{"id":"e1","source":"n1","target":"n2","sourceHandle":"output","targetHandle":"input"},{"id":"e2","source":"n2","target":"n3","sourceHandle":"output","targetHandle":"input"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"output","targetHandle":"input"}]'::jsonb,
  'Intermediate',
  6,
  ARRAY['Healthcare', 'schedule', 'text-formatter', 'ai-chat-model', 'log-output'],
  true,
  false,
  COALESCE((SELECT user_id FROM public.user_roles WHERE role = 'admin' LIMIT 1), (SELECT id FROM auth.users ORDER BY created_at LIMIT 1))
);


-- Template #378
INSERT INTO public.templates (name, description, category, nodes, edges, difficulty, estimated_setup_time, tags, is_active, is_featured, created_by)
VALUES (
  'Finance & Accounting: Parse policy attestations',
  'Starter workflow: Finance & Accounting: Parse policy attestations. Linear flow (webhook → clickup → function → log_output). Configure credentials and fields per node; extend in the canvas.',
  'Finance',
  '[{"id":"n1","type":"custom","position":{"x":100,"y":200},"data":{"type":"webhook","label":"Webhook (1)"}},{"id":"n2","type":"custom","position":{"x":360,"y":200},"data":{"type":"clickup","label":"Clickup (2)"}},{"id":"n3","type":"custom","position":{"x":620,"y":200},"data":{"type":"function","label":"Function (3)"}},{"id":"n4","type":"custom","position":{"x":880,"y":200},"data":{"type":"log_output","label":"Log Output (4)"}}]'::jsonb,
  '[{"id":"e1","source":"n1","target":"n2","sourceHandle":"output","targetHandle":"input"},{"id":"e2","source":"n2","target":"n3","sourceHandle":"output","targetHandle":"input"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"output","targetHandle":"input"}]'::jsonb,
  'Advanced',
  7,
  ARRAY['Finance', 'webhook', 'clickup', 'function', 'log-output'],
  true,
  false,
  COALESCE((SELECT user_id FROM public.user_roles WHERE role = 'admin' LIMIT 1), (SELECT id FROM auth.users ORDER BY created_at LIMIT 1))
);


-- Template #379
INSERT INTO public.templates (name, description, category, nodes, edges, difficulty, estimated_setup_time, tags, is_active, is_featured, created_by)
VALUES (
  'HR & People: Monitor new leads',
  'Starter workflow: HR & People: Monitor new leads. Linear flow (form → javascript → mysql → log_output). Configure credentials and fields per node; extend in the canvas.',
  'HR',
  '[{"id":"n1","type":"custom","position":{"x":100,"y":200},"data":{"type":"form","label":"Form (1)"}},{"id":"n2","type":"custom","position":{"x":360,"y":200},"data":{"type":"javascript","label":"Javascript (2)"}},{"id":"n3","type":"custom","position":{"x":620,"y":200},"data":{"type":"mysql","label":"Mysql (3)"}},{"id":"n4","type":"custom","position":{"x":880,"y":200},"data":{"type":"log_output","label":"Log Output (4)"}}]'::jsonb,
  '[{"id":"e1","source":"n1","target":"n2","sourceHandle":"output","targetHandle":"input"},{"id":"e2","source":"n2","target":"n3","sourceHandle":"output","targetHandle":"input"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"output","targetHandle":"input"}]'::jsonb,
  'Beginner',
  8,
  ARRAY['HR', 'form', 'javascript', 'mysql', 'log-output'],
  true,
  false,
  COALESCE((SELECT user_id FROM public.user_roles WHERE role = 'admin' LIMIT 1), (SELECT id FROM auth.users ORDER BY created_at LIMIT 1))
);


-- Template #380
INSERT INTO public.templates (name, description, category, nodes, edges, difficulty, estimated_setup_time, tags, is_active, is_featured, created_by)
VALUES (
  'DevOps & SRE: Aggregate expense receipts',
  'Starter workflow: DevOps & SRE: Aggregate expense receipts. Linear flow (interval → mongodb → telegram → log_output). Configure credentials and fields per node; extend in the canvas.',
  'Developer Tools',
  '[{"id":"n1","type":"custom","position":{"x":100,"y":200},"data":{"type":"interval","label":"Interval (1)"}},{"id":"n2","type":"custom","position":{"x":360,"y":200},"data":{"type":"mongodb","label":"Mongodb (2)"}},{"id":"n3","type":"custom","position":{"x":620,"y":200},"data":{"type":"telegram","label":"Telegram (3)"}},{"id":"n4","type":"custom","position":{"x":880,"y":200},"data":{"type":"log_output","label":"Log Output (4)"}}]'::jsonb,
  '[{"id":"e1","source":"n1","target":"n2","sourceHandle":"output","targetHandle":"input"},{"id":"e2","source":"n2","target":"n3","sourceHandle":"output","targetHandle":"input"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"output","targetHandle":"input"}]'::jsonb,
  'Intermediate',
  9,
  ARRAY['Developer Tools', 'interval', 'mongodb', 'telegram', 'log-output'],
  true,
  false,
  COALESCE((SELECT user_id FROM public.user_roles WHERE role = 'admin' LIMIT 1), (SELECT id FROM auth.users ORDER BY created_at LIMIT 1))
);


-- Template #381
INSERT INTO public.templates (name, description, category, nodes, edges, difficulty, estimated_setup_time, tags, is_active, is_featured, created_by)
VALUES (
  'Marketing: Validate API error bursts',
  'Starter workflow: Marketing: Validate API error bursts. Linear flow (manual_trigger → openai_gpt → ai_agent → log_output). Configure credentials and fields per node; extend in the canvas.',
  'Marketing & Growth',
  '[{"id":"n1","type":"custom","position":{"x":100,"y":200},"data":{"type":"manual_trigger","label":"Manual Trigger (1)"}},{"id":"n2","type":"custom","position":{"x":360,"y":200},"data":{"type":"openai_gpt","label":"Openai Gpt (2)"}},{"id":"n3","type":"custom","position":{"x":620,"y":200},"data":{"type":"ai_agent","label":"Ai Agent (3)"}},{"id":"n4","type":"custom","position":{"x":880,"y":200},"data":{"type":"log_output","label":"Log Output (4)"}}]'::jsonb,
  '[{"id":"e1","source":"n1","target":"n2","sourceHandle":"output","targetHandle":"input"},{"id":"e2","source":"n2","target":"n3","sourceHandle":"output","targetHandle":"input"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"output","targetHandle":"input"}]'::jsonb,
  'Advanced',
  10,
  ARRAY['Marketing & Growth', 'manual-trigger', 'openai-gpt', 'ai-agent', 'log-output'],
  true,
  false,
  COALESCE((SELECT user_id FROM public.user_roles WHERE role = 'admin' LIMIT 1), (SELECT id FROM auth.users ORDER BY created_at LIMIT 1))
);


-- Template #382
INSERT INTO public.templates (name, description, category, nodes, edges, difficulty, estimated_setup_time, tags, is_active, is_featured, created_by)
VALUES (
  'Customer Support: Reconcile contract PDFs',
  'Starter workflow: Customer Support: Reconcile contract PDFs. Linear flow (schedule → google_drive → filter → log_output). Configure credentials and fields per node; extend in the canvas.',
  'Support',
  '[{"id":"n1","type":"custom","position":{"x":100,"y":200},"data":{"type":"schedule","label":"Schedule (1)"}},{"id":"n2","type":"custom","position":{"x":360,"y":200},"data":{"type":"google_drive","label":"Google Drive (2)"}},{"id":"n3","type":"custom","position":{"x":620,"y":200},"data":{"type":"filter","label":"Filter (3)"}},{"id":"n4","type":"custom","position":{"x":880,"y":200},"data":{"type":"log_output","label":"Log Output (4)"}}]'::jsonb,
  '[{"id":"e1","source":"n1","target":"n2","sourceHandle":"output","targetHandle":"input"},{"id":"e2","source":"n2","target":"n3","sourceHandle":"output","targetHandle":"input"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"output","targetHandle":"input"}]'::jsonb,
  'Beginner',
  11,
  ARRAY['Support', 'schedule', 'google-drive', 'filter', 'log-output'],
  true,
  false,
  COALESCE((SELECT user_id FROM public.user_roles WHERE role = 'admin' LIMIT 1), (SELECT id FROM auth.users ORDER BY created_at LIMIT 1))
);


-- Template #383
INSERT INTO public.templates (name, description, category, nodes, edges, difficulty, estimated_setup_time, tags, is_active, is_featured, created_by)
VALUES (
  'Education: Notify stakeholders about loan applications',
  'Starter workflow: Education: Notify stakeholders about loan applications. Linear flow (webhook → twitter → google_calendar → log_output). Configure credentials and fields per node; extend in the canvas.',
  'Education',
  '[{"id":"n1","type":"custom","position":{"x":100,"y":200},"data":{"type":"webhook","label":"Webhook (1)"}},{"id":"n2","type":"custom","position":{"x":360,"y":200},"data":{"type":"twitter","label":"Twitter (2)"}},{"id":"n3","type":"custom","position":{"x":620,"y":200},"data":{"type":"google_calendar","label":"Google Calendar (3)"}},{"id":"n4","type":"custom","position":{"x":880,"y":200},"data":{"type":"log_output","label":"Log Output (4)"}}]'::jsonb,
  '[{"id":"e1","source":"n1","target":"n2","sourceHandle":"output","targetHandle":"input"},{"id":"e2","source":"n2","target":"n3","sourceHandle":"output","targetHandle":"input"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"output","targetHandle":"input"}]'::jsonb,
  'Intermediate',
  12,
  ARRAY['Education', 'webhook', 'twitter', 'google-calendar', 'log-output'],
  true,
  false,
  COALESCE((SELECT user_id FROM public.user_roles WHERE role = 'admin' LIMIT 1), (SELECT id FROM auth.users ORDER BY created_at LIMIT 1))
);


-- Template #384
INSERT INTO public.templates (name, description, category, nodes, edges, difficulty, estimated_setup_time, tags, is_active, is_featured, created_by)
VALUES (
  'Real Estate: Tag and classify ticket updates',
  'Starter workflow: Real Estate: Tag and classify ticket updates. Linear flow (form → function → clickup → log_output). Configure credentials and fields per node; extend in the canvas.',
  'Real Estate',
  '[{"id":"n1","type":"custom","position":{"x":100,"y":200},"data":{"type":"form","label":"Form (1)"}},{"id":"n2","type":"custom","position":{"x":360,"y":200},"data":{"type":"function","label":"Function (2)"}},{"id":"n3","type":"custom","position":{"x":620,"y":200},"data":{"type":"clickup","label":"Clickup (3)"}},{"id":"n4","type":"custom","position":{"x":880,"y":200},"data":{"type":"log_output","label":"Log Output (4)"}}]'::jsonb,
  '[{"id":"e1","source":"n1","target":"n2","sourceHandle":"output","targetHandle":"input"},{"id":"e2","source":"n2","target":"n3","sourceHandle":"output","targetHandle":"input"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"output","targetHandle":"input"}]'::jsonb,
  'Advanced',
  13,
  ARRAY['Real Estate', 'form', 'function', 'clickup', 'log-output'],
  true,
  false,
  COALESCE((SELECT user_id FROM public.user_roles WHERE role = 'admin' LIMIT 1), (SELECT id FROM auth.users ORDER BY created_at LIMIT 1))
);


-- Template #385
INSERT INTO public.templates (name, description, category, nodes, edges, difficulty, estimated_setup_time, tags, is_active, is_featured, created_by)
VALUES (
  'Legal Ops: Handshake candidate applications',
  'Starter workflow: Legal Ops: Handshake candidate applications. Linear flow (interval → slack_message → ai_service → log_output). Configure credentials and fields per node; extend in the canvas.',
  'Legal',
  '[{"id":"n1","type":"custom","position":{"x":100,"y":200},"data":{"type":"interval","label":"Interval (1)"}},{"id":"n2","type":"custom","position":{"x":360,"y":200},"data":{"type":"slack_message","label":"Slack Message (2)"}},{"id":"n3","type":"custom","position":{"x":620,"y":200},"data":{"type":"ai_service","label":"Ai Service (3)"}},{"id":"n4","type":"custom","position":{"x":880,"y":200},"data":{"type":"log_output","label":"Log Output (4)"}}]'::jsonb,
  '[{"id":"e1","source":"n1","target":"n2","sourceHandle":"output","targetHandle":"input"},{"id":"e2","source":"n2","target":"n3","sourceHandle":"output","targetHandle":"input"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"output","targetHandle":"input"}]'::jsonb,
  'Beginner',
  14,
  ARRAY['Legal', 'interval', 'slack-message', 'ai-service', 'log-output'],
  true,
  false,
  COALESCE((SELECT user_id FROM public.user_roles WHERE role = 'admin' LIMIT 1), (SELECT id FROM auth.users ORDER BY created_at LIMIT 1))
);


-- Template #386
INSERT INTO public.templates (name, description, category, nodes, edges, difficulty, estimated_setup_time, tags, is_active, is_featured, created_by)
VALUES (
  'Manufacturing: Enrich schema migrations',
  'Starter workflow: Manufacturing: Enrich schema migrations. Linear flow (manual_trigger → json_parser → csv → log_output). Configure credentials and fields per node; extend in the canvas.',
  'Operations',
  '[{"id":"n1","type":"custom","position":{"x":100,"y":200},"data":{"type":"manual_trigger","label":"Manual Trigger (1)"}},{"id":"n2","type":"custom","position":{"x":360,"y":200},"data":{"type":"json_parser","label":"Json Parser (2)"}},{"id":"n3","type":"custom","position":{"x":620,"y":200},"data":{"type":"csv","label":"Csv (3)"}},{"id":"n4","type":"custom","position":{"x":880,"y":200},"data":{"type":"log_output","label":"Log Output (4)"}}]'::jsonb,
  '[{"id":"e1","source":"n1","target":"n2","sourceHandle":"output","targetHandle":"input"},{"id":"e2","source":"n2","target":"n3","sourceHandle":"output","targetHandle":"input"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"output","targetHandle":"input"}]'::jsonb,
  'Intermediate',
  15,
  ARRAY['Operations', 'manual-trigger', 'json-parser', 'csv', 'log-output'],
  true,
  false,
  COALESCE((SELECT user_id FROM public.user_roles WHERE role = 'admin' LIMIT 1), (SELECT id FROM auth.users ORDER BY created_at LIMIT 1))
);


-- Template #387
INSERT INTO public.templates (name, description, category, nodes, edges, difficulty, estimated_setup_time, tags, is_active, is_featured, created_by)
VALUES (
  'Nonprofit: Redact survey results',
  'Starter workflow: Nonprofit: Redact survey results. Linear flow (schedule → airtable → google_gmail → log_output). Configure credentials and fields per node; extend in the canvas.',
  'Nonprofit',
  '[{"id":"n1","type":"custom","position":{"x":100,"y":200},"data":{"type":"schedule","label":"Schedule (1)"}},{"id":"n2","type":"custom","position":{"x":360,"y":200},"data":{"type":"airtable","label":"Airtable (2)"}},{"id":"n3","type":"custom","position":{"x":620,"y":200},"data":{"type":"google_gmail","label":"Google Gmail (3)"}},{"id":"n4","type":"custom","position":{"x":880,"y":200},"data":{"type":"log_output","label":"Log Output (4)"}}]'::jsonb,
  '[{"id":"e1","source":"n1","target":"n2","sourceHandle":"output","targetHandle":"input"},{"id":"e2","source":"n2","target":"n3","sourceHandle":"output","targetHandle":"input"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"output","targetHandle":"input"}]'::jsonb,
  'Advanced',
  16,
  ARRAY['Nonprofit', 'schedule', 'airtable', 'google-gmail', 'log-output'],
  true,
  false,
  COALESCE((SELECT user_id FROM public.user_roles WHERE role = 'admin' LIMIT 1), (SELECT id FROM auth.users ORDER BY created_at LIMIT 1))
);


-- Template #388
INSERT INTO public.templates (name, description, category, nodes, edges, difficulty, estimated_setup_time, tags, is_active, is_featured, created_by)
VALUES (
  'Media & Publishing: Extract metrics from grant submissions',
  'Starter workflow: Media & Publishing: Extract metrics from grant submissions. Linear flow (webhook → ai_agent → notion → log_output). Configure credentials and fields per node; extend in the canvas.',
  'Media',
  '[{"id":"n1","type":"custom","position":{"x":100,"y":200},"data":{"type":"webhook","label":"Webhook (1)"}},{"id":"n2","type":"custom","position":{"x":360,"y":200},"data":{"type":"ai_agent","label":"Ai Agent (2)"}},{"id":"n3","type":"custom","position":{"x":620,"y":200},"data":{"type":"notion","label":"Notion (3)"}},{"id":"n4","type":"custom","position":{"x":880,"y":200},"data":{"type":"log_output","label":"Log Output (4)"}}]'::jsonb,
  '[{"id":"e1","source":"n1","target":"n2","sourceHandle":"output","targetHandle":"input"},{"id":"e2","source":"n2","target":"n3","sourceHandle":"output","targetHandle":"input"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"output","targetHandle":"input"}]'::jsonb,
  'Beginner',
  17,
  ARRAY['Media', 'webhook', 'ai-agent', 'notion', 'log-output'],
  true,
  false,
  COALESCE((SELECT user_id FROM public.user_roles WHERE role = 'admin' LIMIT 1), (SELECT id FROM auth.users ORDER BY created_at LIMIT 1))
);


-- Template #389
INSERT INTO public.templates (name, description, category, nodes, edges, difficulty, estimated_setup_time, tags, is_active, is_featured, created_by)
VALUES (
  'Logistics: Triage CSV uploads',
  'Starter workflow: Logistics: Triage CSV uploads. Linear flow (form → google_calendar → twitter → log_output). Configure credentials and fields per node; extend in the canvas.',
  'Logistics',
  '[{"id":"n1","type":"custom","position":{"x":100,"y":200},"data":{"type":"form","label":"Form (1)"}},{"id":"n2","type":"custom","position":{"x":360,"y":200},"data":{"type":"google_calendar","label":"Google Calendar (2)"}},{"id":"n3","type":"custom","position":{"x":620,"y":200},"data":{"type":"twitter","label":"Twitter (3)"}},{"id":"n4","type":"custom","position":{"x":880,"y":200},"data":{"type":"log_output","label":"Log Output (4)"}}]'::jsonb,
  '[{"id":"e1","source":"n1","target":"n2","sourceHandle":"output","targetHandle":"input"},{"id":"e2","source":"n2","target":"n3","sourceHandle":"output","targetHandle":"input"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"output","targetHandle":"input"}]'::jsonb,
  'Intermediate',
  18,
  ARRAY['Logistics', 'form', 'google-calendar', 'twitter', 'log-output'],
  true,
  false,
  COALESCE((SELECT user_id FROM public.user_roles WHERE role = 'admin' LIMIT 1), (SELECT id FROM auth.users ORDER BY created_at LIMIT 1))
);


-- Template #390
INSERT INTO public.templates (name, description, category, nodes, edges, difficulty, estimated_setup_time, tags, is_active, is_featured, created_by)
VALUES (
  'Hospitality: Transform patient intake forms',
  'Starter workflow: Hospitality: Transform patient intake forms. Linear flow (interval → linkedin → set_variable → log_output). Configure credentials and fields per node; extend in the canvas.',
  'Hospitality',
  '[{"id":"n1","type":"custom","position":{"x":100,"y":200},"data":{"type":"interval","label":"Interval (1)"}},{"id":"n2","type":"custom","position":{"x":360,"y":200},"data":{"type":"linkedin","label":"Linkedin (2)"}},{"id":"n3","type":"custom","position":{"x":620,"y":200},"data":{"type":"set_variable","label":"Set Variable (3)"}},{"id":"n4","type":"custom","position":{"x":880,"y":200},"data":{"type":"log_output","label":"Log Output (4)"}}]'::jsonb,
  '[{"id":"e1","source":"n1","target":"n2","sourceHandle":"output","targetHandle":"input"},{"id":"e2","source":"n2","target":"n3","sourceHandle":"output","targetHandle":"input"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"output","targetHandle":"input"}]'::jsonb,
  'Advanced',
  19,
  ARRAY['Hospitality', 'interval', 'linkedin', 'set-variable', 'log-output'],
  true,
  false,
  COALESCE((SELECT user_id FROM public.user_roles WHERE role = 'admin' LIMIT 1), (SELECT id FROM auth.users ORDER BY created_at LIMIT 1))
);


-- Template #391
INSERT INTO public.templates (name, description, category, nodes, edges, difficulty, estimated_setup_time, tags, is_active, is_featured, created_by)
VALUES (
  'SaaS Product: Back up backup manifests',
  'Starter workflow: SaaS Product: Back up backup manifests. Linear flow (manual_trigger → http_request → google_sheets → log_output). Configure credentials and fields per node; extend in the canvas.',
  'Product',
  '[{"id":"n1","type":"custom","position":{"x":100,"y":200},"data":{"type":"manual_trigger","label":"Manual Trigger (1)"}},{"id":"n2","type":"custom","position":{"x":360,"y":200},"data":{"type":"http_request","label":"Http Request (2)"}},{"id":"n3","type":"custom","position":{"x":620,"y":200},"data":{"type":"google_sheets","label":"Google Sheets (3)"}},{"id":"n4","type":"custom","position":{"x":880,"y":200},"data":{"type":"log_output","label":"Log Output (4)"}}]'::jsonb,
  '[{"id":"e1","source":"n1","target":"n2","sourceHandle":"output","targetHandle":"input"},{"id":"e2","source":"n2","target":"n3","sourceHandle":"output","targetHandle":"input"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"output","targetHandle":"input"}]'::jsonb,
  'Beginner',
  20,
  ARRAY['Product', 'manual-trigger', 'http-request', 'google-sheets', 'log-output'],
  true,
  false,
  COALESCE((SELECT user_id FROM public.user_roles WHERE role = 'admin' LIMIT 1), (SELECT id FROM auth.users ORDER BY created_at LIMIT 1))
);


-- Template #392
INSERT INTO public.templates (name, description, category, nodes, edges, difficulty, estimated_setup_time, tags, is_active, is_featured, created_by)
VALUES (
  'IT Service Desk: Sync experiment logs',
  'Starter workflow: IT Service Desk: Sync experiment logs. Linear flow (schedule → telegram → mongodb → log_output). Configure credentials and fields per node; extend in the canvas.',
  'IT',
  '[{"id":"n1","type":"custom","position":{"x":100,"y":200},"data":{"type":"schedule","label":"Schedule (1)"}},{"id":"n2","type":"custom","position":{"x":360,"y":200},"data":{"type":"telegram","label":"Telegram (2)"}},{"id":"n3","type":"custom","position":{"x":620,"y":200},"data":{"type":"mongodb","label":"Mongodb (3)"}},{"id":"n4","type":"custom","position":{"x":880,"y":200},"data":{"type":"log_output","label":"Log Output (4)"}}]'::jsonb,
  '[{"id":"e1","source":"n1","target":"n2","sourceHandle":"output","targetHandle":"input"},{"id":"e2","source":"n2","target":"n3","sourceHandle":"output","targetHandle":"input"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"output","targetHandle":"input"}]'::jsonb,
  'Intermediate',
  21,
  ARRAY['IT', 'schedule', 'telegram', 'mongodb', 'log-output'],
  true,
  true,
  COALESCE((SELECT user_id FROM public.user_roles WHERE role = 'admin' LIMIT 1), (SELECT id FROM auth.users ORDER BY created_at LIMIT 1))
);


-- Template #393
INSERT INTO public.templates (name, description, category, nodes, edges, difficulty, estimated_setup_time, tags, is_active, is_featured, created_by)
VALUES (
  'Sales Ops: Score court filings',
  'Starter workflow: Sales Ops: Score court filings. Linear flow (webhook → csv → email → log_output). Configure credentials and fields per node; extend in the canvas.',
  'CRM & Sales',
  '[{"id":"n1","type":"custom","position":{"x":100,"y":200},"data":{"type":"webhook","label":"Webhook (1)"}},{"id":"n2","type":"custom","position":{"x":360,"y":200},"data":{"type":"csv","label":"Csv (2)"}},{"id":"n3","type":"custom","position":{"x":620,"y":200},"data":{"type":"email","label":"Email (3)"}},{"id":"n4","type":"custom","position":{"x":880,"y":200},"data":{"type":"log_output","label":"Log Output (4)"}}]'::jsonb,
  '[{"id":"e1","source":"n1","target":"n2","sourceHandle":"output","targetHandle":"input"},{"id":"e2","source":"n2","target":"n3","sourceHandle":"output","targetHandle":"input"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"output","targetHandle":"input"}]'::jsonb,
  'Advanced',
  22,
  ARRAY['CRM & Sales', 'webhook', 'csv', 'email', 'log-output'],
  true,
  false,
  COALESCE((SELECT user_id FROM public.user_roles WHERE role = 'admin' LIMIT 1), (SELECT id FROM auth.users ORDER BY created_at LIMIT 1))
);


-- Template #394
INSERT INTO public.templates (name, description, category, nodes, edges, difficulty, estimated_setup_time, tags, is_active, is_featured, created_by)
VALUES (
  'Data Analytics: Normalize form responses',
  'Starter workflow: Data Analytics: Normalize form responses. Linear flow (form → notion → ai_agent → log_output). Configure credentials and fields per node; extend in the canvas.',
  'Data & BI',
  '[{"id":"n1","type":"custom","position":{"x":100,"y":200},"data":{"type":"form","label":"Form (1)"}},{"id":"n2","type":"custom","position":{"x":360,"y":200},"data":{"type":"notion","label":"Notion (2)"}},{"id":"n3","type":"custom","position":{"x":620,"y":200},"data":{"type":"ai_agent","label":"Ai Agent (3)"}},{"id":"n4","type":"custom","position":{"x":880,"y":200},"data":{"type":"log_output","label":"Log Output (4)"}}]'::jsonb,
  '[{"id":"e1","source":"n1","target":"n2","sourceHandle":"output","targetHandle":"input"},{"id":"e2","source":"n2","target":"n3","sourceHandle":"output","targetHandle":"input"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"output","targetHandle":"input"}]'::jsonb,
  'Beginner',
  23,
  ARRAY['Data & BI', 'form', 'notion', 'ai-agent', 'log-output'],
  true,
  false,
  COALESCE((SELECT user_id FROM public.user_roles WHERE role = 'admin' LIMIT 1), (SELECT id FROM auth.users ORDER BY created_at LIMIT 1))
);


-- Template #395
INSERT INTO public.templates (name, description, category, nodes, edges, difficulty, estimated_setup_time, tags, is_active, is_featured, created_by)
VALUES (
  'Security & GRC: Route sensor readings',
  'Starter workflow: Security & GRC: Route sensor readings. Linear flow (interval → ai_chat_model → text_formatter → log_output). Configure credentials and fields per node; extend in the canvas.',
  'Security',
  '[{"id":"n1","type":"custom","position":{"x":100,"y":200},"data":{"type":"interval","label":"Interval (1)"}},{"id":"n2","type":"custom","position":{"x":360,"y":200},"data":{"type":"ai_chat_model","label":"Ai Chat Model (2)"}},{"id":"n3","type":"custom","position":{"x":620,"y":200},"data":{"type":"text_formatter","label":"Text Formatter (3)"}},{"id":"n4","type":"custom","position":{"x":880,"y":200},"data":{"type":"log_output","label":"Log Output (4)"}}]'::jsonb,
  '[{"id":"e1","source":"n1","target":"n2","sourceHandle":"output","targetHandle":"input"},{"id":"e2","source":"n2","target":"n3","sourceHandle":"output","targetHandle":"input"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"output","targetHandle":"input"}]'::jsonb,
  'Intermediate',
  24,
  ARRAY['Security', 'interval', 'ai-chat-model', 'text-formatter', 'log-output'],
  true,
  false,
  COALESCE((SELECT user_id FROM public.user_roles WHERE role = 'admin' LIMIT 1), (SELECT id FROM auth.users ORDER BY created_at LIMIT 1))
);


-- Template #396
INSERT INTO public.templates (name, description, category, nodes, edges, difficulty, estimated_setup_time, tags, is_active, is_featured, created_by)
VALUES (
  'Construction: Watermark compliance exports',
  'Starter workflow: Construction: Watermark compliance exports. Linear flow (manual_trigger → postgresql → mysql → log_output). Configure credentials and fields per node; extend in the canvas.',
  'Construction',
  '[{"id":"n1","type":"custom","position":{"x":100,"y":200},"data":{"type":"manual_trigger","label":"Manual Trigger (1)"}},{"id":"n2","type":"custom","position":{"x":360,"y":200},"data":{"type":"postgresql","label":"Postgresql (2)"}},{"id":"n3","type":"custom","position":{"x":620,"y":200},"data":{"type":"mysql","label":"Mysql (3)"}},{"id":"n4","type":"custom","position":{"x":880,"y":200},"data":{"type":"log_output","label":"Log Output (4)"}}]'::jsonb,
  '[{"id":"e1","source":"n1","target":"n2","sourceHandle":"output","targetHandle":"input"},{"id":"e2","source":"n2","target":"n3","sourceHandle":"output","targetHandle":"input"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"output","targetHandle":"input"}]'::jsonb,
  'Advanced',
  25,
  ARRAY['Construction', 'manual-trigger', 'postgresql', 'mysql', 'log-output'],
  true,
  false,
  COALESCE((SELECT user_id FROM public.user_roles WHERE role = 'admin' LIMIT 1), (SELECT id FROM auth.users ORDER BY created_at LIMIT 1))
);


-- Template #397
INSERT INTO public.templates (name, description, category, nodes, edges, difficulty, estimated_setup_time, tags, is_active, is_featured, created_by)
VALUES (
  'Agriculture: Schedule feature flags',
  'Starter workflow: Agriculture: Schedule feature flags. Linear flow (schedule → ai_service → slack_message → log_output). Configure credentials and fields per node; extend in the canvas.',
  'Agriculture',
  '[{"id":"n1","type":"custom","position":{"x":100,"y":200},"data":{"type":"schedule","label":"Schedule (1)"}},{"id":"n2","type":"custom","position":{"x":360,"y":200},"data":{"type":"ai_service","label":"Ai Service (2)"}},{"id":"n3","type":"custom","position":{"x":620,"y":200},"data":{"type":"slack_message","label":"Slack Message (3)"}},{"id":"n4","type":"custom","position":{"x":880,"y":200},"data":{"type":"log_output","label":"Log Output (4)"}}]'::jsonb,
  '[{"id":"e1","source":"n1","target":"n2","sourceHandle":"output","targetHandle":"input"},{"id":"e2","source":"n2","target":"n3","sourceHandle":"output","targetHandle":"input"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"output","targetHandle":"input"}]'::jsonb,
  'Beginner',
  26,
  ARRAY['Agriculture', 'schedule', 'ai-service', 'slack-message', 'log-output'],
  true,
  false,
  COALESCE((SELECT user_id FROM public.user_roles WHERE role = 'admin' LIMIT 1), (SELECT id FROM auth.users ORDER BY created_at LIMIT 1))
);


-- Template #398
INSERT INTO public.templates (name, description, category, nodes, edges, difficulty, estimated_setup_time, tags, is_active, is_featured, created_by)
VALUES (
  'Energy: Publish asset depreciations',
  'Starter workflow: Energy: Publish asset depreciations. Linear flow (webhook → google_sheets → ollama → log_output). Configure credentials and fields per node; extend in the canvas.',
  'Energy',
  '[{"id":"n1","type":"custom","position":{"x":100,"y":200},"data":{"type":"webhook","label":"Webhook (1)"}},{"id":"n2","type":"custom","position":{"x":360,"y":200},"data":{"type":"google_sheets","label":"Google Sheets (2)"}},{"id":"n3","type":"custom","position":{"x":620,"y":200},"data":{"type":"ollama","label":"Ollama (3)"}},{"id":"n4","type":"custom","position":{"x":880,"y":200},"data":{"type":"log_output","label":"Log Output (4)"}}]'::jsonb,
  '[{"id":"e1","source":"n1","target":"n2","sourceHandle":"output","targetHandle":"input"},{"id":"e2","source":"n2","target":"n3","sourceHandle":"output","targetHandle":"input"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"output","targetHandle":"input"}]'::jsonb,
  'Intermediate',
  27,
  ARRAY['Energy', 'webhook', 'google-sheets', 'ollama', 'log-output'],
  true,
  false,
  COALESCE((SELECT user_id FROM public.user_roles WHERE role = 'admin' LIMIT 1), (SELECT id FROM auth.users ORDER BY created_at LIMIT 1))
);


-- Template #399
INSERT INTO public.templates (name, description, category, nodes, edges, difficulty, estimated_setup_time, tags, is_active, is_featured, created_by)
VALUES (
  'Telecom: Archive webhook payloads',
  'Starter workflow: Telecom: Archive webhook payloads. Linear flow (form → email → csv → log_output). Configure credentials and fields per node; extend in the canvas.',
  'Telecom',
  '[{"id":"n1","type":"custom","position":{"x":100,"y":200},"data":{"type":"form","label":"Form (1)"}},{"id":"n2","type":"custom","position":{"x":360,"y":200},"data":{"type":"email","label":"Email (2)"}},{"id":"n3","type":"custom","position":{"x":620,"y":200},"data":{"type":"csv","label":"Csv (3)"}},{"id":"n4","type":"custom","position":{"x":880,"y":200},"data":{"type":"log_output","label":"Log Output (4)"}}]'::jsonb,
  '[{"id":"e1","source":"n1","target":"n2","sourceHandle":"output","targetHandle":"input"},{"id":"e2","source":"n2","target":"n3","sourceHandle":"output","targetHandle":"input"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"output","targetHandle":"input"}]'::jsonb,
  'Advanced',
  28,
  ARRAY['Telecom', 'form', 'email', 'csv', 'log-output'],
  true,
  false,
  COALESCE((SELECT user_id FROM public.user_roles WHERE role = 'admin' LIMIT 1), (SELECT id FROM auth.users ORDER BY created_at LIMIT 1))
);


-- Template #400
INSERT INTO public.templates (name, description, category, nodes, edges, difficulty, estimated_setup_time, tags, is_active, is_featured, created_by)
VALUES (
  'Gov & Public Sector: Summarize shipment events',
  'Starter workflow: Gov & Public Sector: Summarize shipment events. Linear flow (interval → filter → google_drive → log_output). Configure credentials and fields per node; extend in the canvas.',
  'Public Sector',
  '[{"id":"n1","type":"custom","position":{"x":100,"y":200},"data":{"type":"interval","label":"Interval (1)"}},{"id":"n2","type":"custom","position":{"x":360,"y":200},"data":{"type":"filter","label":"Filter (2)"}},{"id":"n3","type":"custom","position":{"x":620,"y":200},"data":{"type":"google_drive","label":"Google Drive (3)"}},{"id":"n4","type":"custom","position":{"x":880,"y":200},"data":{"type":"log_output","label":"Log Output (4)"}}]'::jsonb,
  '[{"id":"e1","source":"n1","target":"n2","sourceHandle":"output","targetHandle":"input"},{"id":"e2","source":"n2","target":"n3","sourceHandle":"output","targetHandle":"input"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"output","targetHandle":"input"}]'::jsonb,
  'Beginner',
  29,
  ARRAY['Public Sector', 'interval', 'filter', 'google-drive', 'log-output'],
  true,
  false,
  COALESCE((SELECT user_id FROM public.user_roles WHERE role = 'admin' LIMIT 1), (SELECT id FROM auth.users ORDER BY created_at LIMIT 1))
);


COMMIT;
