-- =============================================================================
-- Registry-aligned template seed batch 10 of 10
-- Templates 451–500 of 500
-- Generated by ctrl_checks/scripts/generate-workflow-templates-sql.ts
-- Run 00_delete_all_templates.sql first if replacing the full catalog.
-- =============================================================================

BEGIN;

-- Template #451
INSERT INTO public.templates (name, description, category, nodes, edges, difficulty, estimated_setup_time, tags, is_active, is_featured, created_by)
VALUES (
  'E-commerce: Automate calendar holds',
  'Starter workflow: E-commerce: Automate calendar holds. Linear flow (manual_trigger → http_request → google_sheets → log_output). Configure credentials and fields per node; extend in the canvas.',
  'Commerce & Retail',
  '[{"id":"n1","type":"custom","position":{"x":100,"y":200},"data":{"type":"manual_trigger","label":"Manual Trigger (1)"}},{"id":"n2","type":"custom","position":{"x":360,"y":200},"data":{"type":"http_request","label":"Http Request (2)"}},{"id":"n3","type":"custom","position":{"x":620,"y":200},"data":{"type":"google_sheets","label":"Google Sheets (3)"}},{"id":"n4","type":"custom","position":{"x":880,"y":200},"data":{"type":"log_output","label":"Log Output (4)"}}]'::jsonb,
  '[{"id":"e1","source":"n1","target":"n2","sourceHandle":"output","targetHandle":"input"},{"id":"e2","source":"n2","target":"n3","sourceHandle":"output","targetHandle":"input"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"output","targetHandle":"input"}]'::jsonb,
  'Beginner',
  5,
  ARRAY['Commerce & Retail', 'manual-trigger', 'http-request', 'google-sheets', 'log-output'],
  true,
  false,
  COALESCE((SELECT user_id FROM public.user_roles WHERE role = 'admin' LIMIT 1), (SELECT id FROM auth.users ORDER BY created_at LIMIT 1))
);


-- Template #452
INSERT INTO public.templates (name, description, category, nodes, edges, difficulty, estimated_setup_time, tags, is_active, is_featured, created_by)
VALUES (
  'Healthcare: Deduplicate help-center articles',
  'Starter workflow: Healthcare: Deduplicate help-center articles. Linear flow (schedule → telegram → mongodb → log_output). Configure credentials and fields per node; extend in the canvas.',
  'Healthcare',
  '[{"id":"n1","type":"custom","position":{"x":100,"y":200},"data":{"type":"schedule","label":"Schedule (1)"}},{"id":"n2","type":"custom","position":{"x":360,"y":200},"data":{"type":"telegram","label":"Telegram (2)"}},{"id":"n3","type":"custom","position":{"x":620,"y":200},"data":{"type":"mongodb","label":"Mongodb (3)"}},{"id":"n4","type":"custom","position":{"x":880,"y":200},"data":{"type":"log_output","label":"Log Output (4)"}}]'::jsonb,
  '[{"id":"e1","source":"n1","target":"n2","sourceHandle":"output","targetHandle":"input"},{"id":"e2","source":"n2","target":"n3","sourceHandle":"output","targetHandle":"input"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"output","targetHandle":"input"}]'::jsonb,
  'Intermediate',
  6,
  ARRAY['Healthcare', 'schedule', 'telegram', 'mongodb', 'log-output'],
  true,
  false,
  COALESCE((SELECT user_id FROM public.user_roles WHERE role = 'admin' LIMIT 1), (SELECT id FROM auth.users ORDER BY created_at LIMIT 1))
);


-- Template #453
INSERT INTO public.templates (name, description, category, nodes, edges, difficulty, estimated_setup_time, tags, is_active, is_featured, created_by)
VALUES (
  'Finance & Accounting: Parse board packets',
  'Starter workflow: Finance & Accounting: Parse board packets. Linear flow (webhook → csv → email → log_output). Configure credentials and fields per node; extend in the canvas.',
  'Finance',
  '[{"id":"n1","type":"custom","position":{"x":100,"y":200},"data":{"type":"webhook","label":"Webhook (1)"}},{"id":"n2","type":"custom","position":{"x":360,"y":200},"data":{"type":"csv","label":"Csv (2)"}},{"id":"n3","type":"custom","position":{"x":620,"y":200},"data":{"type":"email","label":"Email (3)"}},{"id":"n4","type":"custom","position":{"x":880,"y":200},"data":{"type":"log_output","label":"Log Output (4)"}}]'::jsonb,
  '[{"id":"e1","source":"n1","target":"n2","sourceHandle":"output","targetHandle":"input"},{"id":"e2","source":"n2","target":"n3","sourceHandle":"output","targetHandle":"input"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"output","targetHandle":"input"}]'::jsonb,
  'Advanced',
  7,
  ARRAY['Finance', 'webhook', 'csv', 'email', 'log-output'],
  true,
  false,
  COALESCE((SELECT user_id FROM public.user_roles WHERE role = 'admin' LIMIT 1), (SELECT id FROM auth.users ORDER BY created_at LIMIT 1))
);


-- Template #454
INSERT INTO public.templates (name, description, category, nodes, edges, difficulty, estimated_setup_time, tags, is_active, is_featured, created_by)
VALUES (
  'HR & People: Monitor vendor bills',
  'Starter workflow: HR & People: Monitor vendor bills. Linear flow (form → notion → ai_agent → log_output). Configure credentials and fields per node; extend in the canvas.',
  'HR',
  '[{"id":"n1","type":"custom","position":{"x":100,"y":200},"data":{"type":"form","label":"Form (1)"}},{"id":"n2","type":"custom","position":{"x":360,"y":200},"data":{"type":"notion","label":"Notion (2)"}},{"id":"n3","type":"custom","position":{"x":620,"y":200},"data":{"type":"ai_agent","label":"Ai Agent (3)"}},{"id":"n4","type":"custom","position":{"x":880,"y":200},"data":{"type":"log_output","label":"Log Output (4)"}}]'::jsonb,
  '[{"id":"e1","source":"n1","target":"n2","sourceHandle":"output","targetHandle":"input"},{"id":"e2","source":"n2","target":"n3","sourceHandle":"output","targetHandle":"input"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"output","targetHandle":"input"}]'::jsonb,
  'Beginner',
  8,
  ARRAY['HR', 'form', 'notion', 'ai-agent', 'log-output'],
  true,
  false,
  COALESCE((SELECT user_id FROM public.user_roles WHERE role = 'admin' LIMIT 1), (SELECT id FROM auth.users ORDER BY created_at LIMIT 1))
);


-- Template #455
INSERT INTO public.templates (name, description, category, nodes, edges, difficulty, estimated_setup_time, tags, is_active, is_featured, created_by)
VALUES (
  'DevOps & SRE: Aggregate prescription refills',
  'Starter workflow: DevOps & SRE: Aggregate prescription refills. Linear flow (interval → ai_chat_model → text_formatter → log_output). Configure credentials and fields per node; extend in the canvas.',
  'Developer Tools',
  '[{"id":"n1","type":"custom","position":{"x":100,"y":200},"data":{"type":"interval","label":"Interval (1)"}},{"id":"n2","type":"custom","position":{"x":360,"y":200},"data":{"type":"ai_chat_model","label":"Ai Chat Model (2)"}},{"id":"n3","type":"custom","position":{"x":620,"y":200},"data":{"type":"text_formatter","label":"Text Formatter (3)"}},{"id":"n4","type":"custom","position":{"x":880,"y":200},"data":{"type":"log_output","label":"Log Output (4)"}}]'::jsonb,
  '[{"id":"e1","source":"n1","target":"n2","sourceHandle":"output","targetHandle":"input"},{"id":"e2","source":"n2","target":"n3","sourceHandle":"output","targetHandle":"input"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"output","targetHandle":"input"}]'::jsonb,
  'Intermediate',
  9,
  ARRAY['Developer Tools', 'interval', 'ai-chat-model', 'text-formatter', 'log-output'],
  true,
  false,
  COALESCE((SELECT user_id FROM public.user_roles WHERE role = 'admin' LIMIT 1), (SELECT id FROM auth.users ORDER BY created_at LIMIT 1))
);


-- Template #456
INSERT INTO public.templates (name, description, category, nodes, edges, difficulty, estimated_setup_time, tags, is_active, is_featured, created_by)
VALUES (
  'Marketing: Validate inventory deltas',
  'Starter workflow: Marketing: Validate inventory deltas. Linear flow (manual_trigger → postgresql → mysql → log_output). Configure credentials and fields per node; extend in the canvas.',
  'Marketing & Growth',
  '[{"id":"n1","type":"custom","position":{"x":100,"y":200},"data":{"type":"manual_trigger","label":"Manual Trigger (1)"}},{"id":"n2","type":"custom","position":{"x":360,"y":200},"data":{"type":"postgresql","label":"Postgresql (2)"}},{"id":"n3","type":"custom","position":{"x":620,"y":200},"data":{"type":"mysql","label":"Mysql (3)"}},{"id":"n4","type":"custom","position":{"x":880,"y":200},"data":{"type":"log_output","label":"Log Output (4)"}}]'::jsonb,
  '[{"id":"e1","source":"n1","target":"n2","sourceHandle":"output","targetHandle":"input"},{"id":"e2","source":"n2","target":"n3","sourceHandle":"output","targetHandle":"input"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"output","targetHandle":"input"}]'::jsonb,
  'Advanced',
  10,
  ARRAY['Marketing & Growth', 'manual-trigger', 'postgresql', 'mysql', 'log-output'],
  true,
  false,
  COALESCE((SELECT user_id FROM public.user_roles WHERE role = 'admin' LIMIT 1), (SELECT id FROM auth.users ORDER BY created_at LIMIT 1))
);


-- Template #457
INSERT INTO public.templates (name, description, category, nodes, edges, difficulty, estimated_setup_time, tags, is_active, is_featured, created_by)
VALUES (
  'Customer Support: Reconcile warehouse scans',
  'Starter workflow: Customer Support: Reconcile warehouse scans. Linear flow (schedule → ai_service → slack_message → log_output). Configure credentials and fields per node; extend in the canvas.',
  'Support',
  '[{"id":"n1","type":"custom","position":{"x":100,"y":200},"data":{"type":"schedule","label":"Schedule (1)"}},{"id":"n2","type":"custom","position":{"x":360,"y":200},"data":{"type":"ai_service","label":"Ai Service (2)"}},{"id":"n3","type":"custom","position":{"x":620,"y":200},"data":{"type":"slack_message","label":"Slack Message (3)"}},{"id":"n4","type":"custom","position":{"x":880,"y":200},"data":{"type":"log_output","label":"Log Output (4)"}}]'::jsonb,
  '[{"id":"e1","source":"n1","target":"n2","sourceHandle":"output","targetHandle":"input"},{"id":"e2","source":"n2","target":"n3","sourceHandle":"output","targetHandle":"input"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"output","targetHandle":"input"}]'::jsonb,
  'Beginner',
  11,
  ARRAY['Support', 'schedule', 'ai-service', 'slack-message', 'log-output'],
  true,
  false,
  COALESCE((SELECT user_id FROM public.user_roles WHERE role = 'admin' LIMIT 1), (SELECT id FROM auth.users ORDER BY created_at LIMIT 1))
);


-- Template #458
INSERT INTO public.templates (name, description, category, nodes, edges, difficulty, estimated_setup_time, tags, is_active, is_featured, created_by)
VALUES (
  'Education: Notify stakeholders about NPS feedback',
  'Starter workflow: Education: Notify stakeholders about NPS feedback. Linear flow (webhook → google_sheets → ollama → log_output). Configure credentials and fields per node; extend in the canvas.',
  'Education',
  '[{"id":"n1","type":"custom","position":{"x":100,"y":200},"data":{"type":"webhook","label":"Webhook (1)"}},{"id":"n2","type":"custom","position":{"x":360,"y":200},"data":{"type":"google_sheets","label":"Google Sheets (2)"}},{"id":"n3","type":"custom","position":{"x":620,"y":200},"data":{"type":"ollama","label":"Ollama (3)"}},{"id":"n4","type":"custom","position":{"x":880,"y":200},"data":{"type":"log_output","label":"Log Output (4)"}}]'::jsonb,
  '[{"id":"e1","source":"n1","target":"n2","sourceHandle":"output","targetHandle":"input"},{"id":"e2","source":"n2","target":"n3","sourceHandle":"output","targetHandle":"input"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"output","targetHandle":"input"}]'::jsonb,
  'Intermediate',
  12,
  ARRAY['Education', 'webhook', 'google-sheets', 'ollama', 'log-output'],
  true,
  false,
  COALESCE((SELECT user_id FROM public.user_roles WHERE role = 'admin' LIMIT 1), (SELECT id FROM auth.users ORDER BY created_at LIMIT 1))
);


-- Template #459
INSERT INTO public.templates (name, description, category, nodes, edges, difficulty, estimated_setup_time, tags, is_active, is_featured, created_by)
VALUES (
  'Real Estate: Tag and classify subscription renewals',
  'Starter workflow: Real Estate: Tag and classify subscription renewals. Linear flow (form → email → csv → log_output). Configure credentials and fields per node; extend in the canvas.',
  'Real Estate',
  '[{"id":"n1","type":"custom","position":{"x":100,"y":200},"data":{"type":"form","label":"Form (1)"}},{"id":"n2","type":"custom","position":{"x":360,"y":200},"data":{"type":"email","label":"Email (2)"}},{"id":"n3","type":"custom","position":{"x":620,"y":200},"data":{"type":"csv","label":"Csv (3)"}},{"id":"n4","type":"custom","position":{"x":880,"y":200},"data":{"type":"log_output","label":"Log Output (4)"}}]'::jsonb,
  '[{"id":"e1","source":"n1","target":"n2","sourceHandle":"output","targetHandle":"input"},{"id":"e2","source":"n2","target":"n3","sourceHandle":"output","targetHandle":"input"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"output","targetHandle":"input"}]'::jsonb,
  'Advanced',
  13,
  ARRAY['Real Estate', 'form', 'email', 'csv', 'log-output'],
  true,
  false,
  COALESCE((SELECT user_id FROM public.user_roles WHERE role = 'admin' LIMIT 1), (SELECT id FROM auth.users ORDER BY created_at LIMIT 1))
);


-- Template #460
INSERT INTO public.templates (name, description, category, nodes, edges, difficulty, estimated_setup_time, tags, is_active, is_featured, created_by)
VALUES (
  'Legal Ops: Handshake IoT heartbeats',
  'Starter workflow: Legal Ops: Handshake IoT heartbeats. Linear flow (interval → filter → google_drive → log_output). Configure credentials and fields per node; extend in the canvas.',
  'Legal',
  '[{"id":"n1","type":"custom","position":{"x":100,"y":200},"data":{"type":"interval","label":"Interval (1)"}},{"id":"n2","type":"custom","position":{"x":360,"y":200},"data":{"type":"filter","label":"Filter (2)"}},{"id":"n3","type":"custom","position":{"x":620,"y":200},"data":{"type":"google_drive","label":"Google Drive (3)"}},{"id":"n4","type":"custom","position":{"x":880,"y":200},"data":{"type":"log_output","label":"Log Output (4)"}}]'::jsonb,
  '[{"id":"e1","source":"n1","target":"n2","sourceHandle":"output","targetHandle":"input"},{"id":"e2","source":"n2","target":"n3","sourceHandle":"output","targetHandle":"input"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"output","targetHandle":"input"}]'::jsonb,
  'Beginner',
  14,
  ARRAY['Legal', 'interval', 'filter', 'google-drive', 'log-output'],
  true,
  false,
  COALESCE((SELECT user_id FROM public.user_roles WHERE role = 'admin' LIMIT 1), (SELECT id FROM auth.users ORDER BY created_at LIMIT 1))
);


-- Template #461
INSERT INTO public.templates (name, description, category, nodes, edges, difficulty, estimated_setup_time, tags, is_active, is_featured, created_by)
VALUES (
  'Manufacturing: Enrich invoice lines',
  'Starter workflow: Manufacturing: Enrich invoice lines. Linear flow (manual_trigger → hubspot → clickup → log_output). Configure credentials and fields per node; extend in the canvas.',
  'Operations',
  '[{"id":"n1","type":"custom","position":{"x":100,"y":200},"data":{"type":"manual_trigger","label":"Manual Trigger (1)"}},{"id":"n2","type":"custom","position":{"x":360,"y":200},"data":{"type":"hubspot","label":"Hubspot (2)"}},{"id":"n3","type":"custom","position":{"x":620,"y":200},"data":{"type":"clickup","label":"Clickup (3)"}},{"id":"n4","type":"custom","position":{"x":880,"y":200},"data":{"type":"log_output","label":"Log Output (4)"}}]'::jsonb,
  '[{"id":"e1","source":"n1","target":"n2","sourceHandle":"output","targetHandle":"input"},{"id":"e2","source":"n2","target":"n3","sourceHandle":"output","targetHandle":"input"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"output","targetHandle":"input"}]'::jsonb,
  'Intermediate',
  15,
  ARRAY['Operations', 'manual-trigger', 'hubspot', 'clickup', 'log-output'],
  true,
  true,
  COALESCE((SELECT user_id FROM public.user_roles WHERE role = 'admin' LIMIT 1), (SELECT id FROM auth.users ORDER BY created_at LIMIT 1))
);


-- Template #462
INSERT INTO public.templates (name, description, category, nodes, edges, difficulty, estimated_setup_time, tags, is_active, is_featured, created_by)
VALUES (
  'Nonprofit: Redact policy attestations',
  'Starter workflow: Nonprofit: Redact policy attestations. Linear flow (schedule → set_variable → linkedin → log_output). Configure credentials and fields per node; extend in the canvas.',
  'Nonprofit',
  '[{"id":"n1","type":"custom","position":{"x":100,"y":200},"data":{"type":"schedule","label":"Schedule (1)"}},{"id":"n2","type":"custom","position":{"x":360,"y":200},"data":{"type":"set_variable","label":"Set Variable (2)"}},{"id":"n3","type":"custom","position":{"x":620,"y":200},"data":{"type":"linkedin","label":"Linkedin (3)"}},{"id":"n4","type":"custom","position":{"x":880,"y":200},"data":{"type":"log_output","label":"Log Output (4)"}}]'::jsonb,
  '[{"id":"e1","source":"n1","target":"n2","sourceHandle":"output","targetHandle":"input"},{"id":"e2","source":"n2","target":"n3","sourceHandle":"output","targetHandle":"input"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"output","targetHandle":"input"}]'::jsonb,
  'Advanced',
  16,
  ARRAY['Nonprofit', 'schedule', 'set-variable', 'linkedin', 'log-output'],
  true,
  false,
  COALESCE((SELECT user_id FROM public.user_roles WHERE role = 'admin' LIMIT 1), (SELECT id FROM auth.users ORDER BY created_at LIMIT 1))
);


-- Template #463
INSERT INTO public.templates (name, description, category, nodes, edges, difficulty, estimated_setup_time, tags, is_active, is_featured, created_by)
VALUES (
  'Media & Publishing: Extract metrics from new leads',
  'Starter workflow: Media & Publishing: Extract metrics from new leads. Linear flow (webhook → mysql → javascript → log_output). Configure credentials and fields per node; extend in the canvas.',
  'Media',
  '[{"id":"n1","type":"custom","position":{"x":100,"y":200},"data":{"type":"webhook","label":"Webhook (1)"}},{"id":"n2","type":"custom","position":{"x":360,"y":200},"data":{"type":"mysql","label":"Mysql (2)"}},{"id":"n3","type":"custom","position":{"x":620,"y":200},"data":{"type":"javascript","label":"Javascript (3)"}},{"id":"n4","type":"custom","position":{"x":880,"y":200},"data":{"type":"log_output","label":"Log Output (4)"}}]'::jsonb,
  '[{"id":"e1","source":"n1","target":"n2","sourceHandle":"output","targetHandle":"input"},{"id":"e2","source":"n2","target":"n3","sourceHandle":"output","targetHandle":"input"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"output","targetHandle":"input"}]'::jsonb,
  'Beginner',
  17,
  ARRAY['Media', 'webhook', 'mysql', 'javascript', 'log-output'],
  true,
  false,
  COALESCE((SELECT user_id FROM public.user_roles WHERE role = 'admin' LIMIT 1), (SELECT id FROM auth.users ORDER BY created_at LIMIT 1))
);


-- Template #464
INSERT INTO public.templates (name, description, category, nodes, edges, difficulty, estimated_setup_time, tags, is_active, is_featured, created_by)
VALUES (
  'Logistics: Triage expense receipts',
  'Starter workflow: Logistics: Triage expense receipts. Linear flow (form → ollama → google_sheets → log_output). Configure credentials and fields per node; extend in the canvas.',
  'Logistics',
  '[{"id":"n1","type":"custom","position":{"x":100,"y":200},"data":{"type":"form","label":"Form (1)"}},{"id":"n2","type":"custom","position":{"x":360,"y":200},"data":{"type":"ollama","label":"Ollama (2)"}},{"id":"n3","type":"custom","position":{"x":620,"y":200},"data":{"type":"google_sheets","label":"Google Sheets (3)"}},{"id":"n4","type":"custom","position":{"x":880,"y":200},"data":{"type":"log_output","label":"Log Output (4)"}}]'::jsonb,
  '[{"id":"e1","source":"n1","target":"n2","sourceHandle":"output","targetHandle":"input"},{"id":"e2","source":"n2","target":"n3","sourceHandle":"output","targetHandle":"input"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"output","targetHandle":"input"}]'::jsonb,
  'Intermediate',
  18,
  ARRAY['Logistics', 'form', 'ollama', 'google-sheets', 'log-output'],
  true,
  false,
  COALESCE((SELECT user_id FROM public.user_roles WHERE role = 'admin' LIMIT 1), (SELECT id FROM auth.users ORDER BY created_at LIMIT 1))
);


-- Template #465
INSERT INTO public.templates (name, description, category, nodes, edges, difficulty, estimated_setup_time, tags, is_active, is_featured, created_by)
VALUES (
  'Hospitality: Transform API error bursts',
  'Starter workflow: Hospitality: Transform API error bursts. Linear flow (interval → google_gmail → airtable → log_output). Configure credentials and fields per node; extend in the canvas.',
  'Hospitality',
  '[{"id":"n1","type":"custom","position":{"x":100,"y":200},"data":{"type":"interval","label":"Interval (1)"}},{"id":"n2","type":"custom","position":{"x":360,"y":200},"data":{"type":"google_gmail","label":"Google Gmail (2)"}},{"id":"n3","type":"custom","position":{"x":620,"y":200},"data":{"type":"airtable","label":"Airtable (3)"}},{"id":"n4","type":"custom","position":{"x":880,"y":200},"data":{"type":"log_output","label":"Log Output (4)"}}]'::jsonb,
  '[{"id":"e1","source":"n1","target":"n2","sourceHandle":"output","targetHandle":"input"},{"id":"e2","source":"n2","target":"n3","sourceHandle":"output","targetHandle":"input"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"output","targetHandle":"input"}]'::jsonb,
  'Advanced',
  19,
  ARRAY['Hospitality', 'interval', 'google-gmail', 'airtable', 'log-output'],
  true,
  false,
  COALESCE((SELECT user_id FROM public.user_roles WHERE role = 'admin' LIMIT 1), (SELECT id FROM auth.users ORDER BY created_at LIMIT 1))
);


-- Template #466
INSERT INTO public.templates (name, description, category, nodes, edges, difficulty, estimated_setup_time, tags, is_active, is_featured, created_by)
VALUES (
  'SaaS Product: Back up contract PDFs',
  'Starter workflow: SaaS Product: Back up contract PDFs. Linear flow (manual_trigger → outlook → twitter → log_output). Configure credentials and fields per node; extend in the canvas.',
  'Product',
  '[{"id":"n1","type":"custom","position":{"x":100,"y":200},"data":{"type":"manual_trigger","label":"Manual Trigger (1)"}},{"id":"n2","type":"custom","position":{"x":360,"y":200},"data":{"type":"outlook","label":"Outlook (2)"}},{"id":"n3","type":"custom","position":{"x":620,"y":200},"data":{"type":"twitter","label":"Twitter (3)"}},{"id":"n4","type":"custom","position":{"x":880,"y":200},"data":{"type":"log_output","label":"Log Output (4)"}}]'::jsonb,
  '[{"id":"e1","source":"n1","target":"n2","sourceHandle":"output","targetHandle":"input"},{"id":"e2","source":"n2","target":"n3","sourceHandle":"output","targetHandle":"input"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"output","targetHandle":"input"}]'::jsonb,
  'Beginner',
  20,
  ARRAY['Product', 'manual-trigger', 'outlook', 'twitter', 'log-output'],
  true,
  false,
  COALESCE((SELECT user_id FROM public.user_roles WHERE role = 'admin' LIMIT 1), (SELECT id FROM auth.users ORDER BY created_at LIMIT 1))
);


-- Template #467
INSERT INTO public.templates (name, description, category, nodes, edges, difficulty, estimated_setup_time, tags, is_active, is_featured, created_by)
VALUES (
  'IT Service Desk: Sync loan applications',
  'Starter workflow: IT Service Desk: Sync loan applications. Linear flow (schedule → text_formatter → ai_chat_model → log_output). Configure credentials and fields per node; extend in the canvas.',
  'IT',
  '[{"id":"n1","type":"custom","position":{"x":100,"y":200},"data":{"type":"schedule","label":"Schedule (1)"}},{"id":"n2","type":"custom","position":{"x":360,"y":200},"data":{"type":"text_formatter","label":"Text Formatter (2)"}},{"id":"n3","type":"custom","position":{"x":620,"y":200},"data":{"type":"ai_chat_model","label":"Ai Chat Model (3)"}},{"id":"n4","type":"custom","position":{"x":880,"y":200},"data":{"type":"log_output","label":"Log Output (4)"}}]'::jsonb,
  '[{"id":"e1","source":"n1","target":"n2","sourceHandle":"output","targetHandle":"input"},{"id":"e2","source":"n2","target":"n3","sourceHandle":"output","targetHandle":"input"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"output","targetHandle":"input"}]'::jsonb,
  'Intermediate',
  21,
  ARRAY['IT', 'schedule', 'text-formatter', 'ai-chat-model', 'log-output'],
  true,
  false,
  COALESCE((SELECT user_id FROM public.user_roles WHERE role = 'admin' LIMIT 1), (SELECT id FROM auth.users ORDER BY created_at LIMIT 1))
);


-- Template #468
INSERT INTO public.templates (name, description, category, nodes, edges, difficulty, estimated_setup_time, tags, is_active, is_featured, created_by)
VALUES (
  'Sales Ops: Score ticket updates',
  'Starter workflow: Sales Ops: Score ticket updates. Linear flow (webhook → clickup → function → log_output). Configure credentials and fields per node; extend in the canvas.',
  'CRM & Sales',
  '[{"id":"n1","type":"custom","position":{"x":100,"y":200},"data":{"type":"webhook","label":"Webhook (1)"}},{"id":"n2","type":"custom","position":{"x":360,"y":200},"data":{"type":"clickup","label":"Clickup (2)"}},{"id":"n3","type":"custom","position":{"x":620,"y":200},"data":{"type":"function","label":"Function (3)"}},{"id":"n4","type":"custom","position":{"x":880,"y":200},"data":{"type":"log_output","label":"Log Output (4)"}}]'::jsonb,
  '[{"id":"e1","source":"n1","target":"n2","sourceHandle":"output","targetHandle":"input"},{"id":"e2","source":"n2","target":"n3","sourceHandle":"output","targetHandle":"input"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"output","targetHandle":"input"}]'::jsonb,
  'Advanced',
  22,
  ARRAY['CRM & Sales', 'webhook', 'clickup', 'function', 'log-output'],
  true,
  false,
  COALESCE((SELECT user_id FROM public.user_roles WHERE role = 'admin' LIMIT 1), (SELECT id FROM auth.users ORDER BY created_at LIMIT 1))
);


-- Template #469
INSERT INTO public.templates (name, description, category, nodes, edges, difficulty, estimated_setup_time, tags, is_active, is_featured, created_by)
VALUES (
  'Data Analytics: Normalize candidate applications',
  'Starter workflow: Data Analytics: Normalize candidate applications. Linear flow (form → javascript → mysql → log_output). Configure credentials and fields per node; extend in the canvas.',
  'Data & BI',
  '[{"id":"n1","type":"custom","position":{"x":100,"y":200},"data":{"type":"form","label":"Form (1)"}},{"id":"n2","type":"custom","position":{"x":360,"y":200},"data":{"type":"javascript","label":"Javascript (2)"}},{"id":"n3","type":"custom","position":{"x":620,"y":200},"data":{"type":"mysql","label":"Mysql (3)"}},{"id":"n4","type":"custom","position":{"x":880,"y":200},"data":{"type":"log_output","label":"Log Output (4)"}}]'::jsonb,
  '[{"id":"e1","source":"n1","target":"n2","sourceHandle":"output","targetHandle":"input"},{"id":"e2","source":"n2","target":"n3","sourceHandle":"output","targetHandle":"input"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"output","targetHandle":"input"}]'::jsonb,
  'Beginner',
  23,
  ARRAY['Data & BI', 'form', 'javascript', 'mysql', 'log-output'],
  true,
  false,
  COALESCE((SELECT user_id FROM public.user_roles WHERE role = 'admin' LIMIT 1), (SELECT id FROM auth.users ORDER BY created_at LIMIT 1))
);


-- Template #470
INSERT INTO public.templates (name, description, category, nodes, edges, difficulty, estimated_setup_time, tags, is_active, is_featured, created_by)
VALUES (
  'Security & GRC: Route schema migrations',
  'Starter workflow: Security & GRC: Route schema migrations. Linear flow (interval → mongodb → telegram → log_output). Configure credentials and fields per node; extend in the canvas.',
  'Security',
  '[{"id":"n1","type":"custom","position":{"x":100,"y":200},"data":{"type":"interval","label":"Interval (1)"}},{"id":"n2","type":"custom","position":{"x":360,"y":200},"data":{"type":"mongodb","label":"Mongodb (2)"}},{"id":"n3","type":"custom","position":{"x":620,"y":200},"data":{"type":"telegram","label":"Telegram (3)"}},{"id":"n4","type":"custom","position":{"x":880,"y":200},"data":{"type":"log_output","label":"Log Output (4)"}}]'::jsonb,
  '[{"id":"e1","source":"n1","target":"n2","sourceHandle":"output","targetHandle":"input"},{"id":"e2","source":"n2","target":"n3","sourceHandle":"output","targetHandle":"input"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"output","targetHandle":"input"}]'::jsonb,
  'Intermediate',
  24,
  ARRAY['Security', 'interval', 'mongodb', 'telegram', 'log-output'],
  true,
  false,
  COALESCE((SELECT user_id FROM public.user_roles WHERE role = 'admin' LIMIT 1), (SELECT id FROM auth.users ORDER BY created_at LIMIT 1))
);


-- Template #471
INSERT INTO public.templates (name, description, category, nodes, edges, difficulty, estimated_setup_time, tags, is_active, is_featured, created_by)
VALUES (
  'Construction: Watermark survey results',
  'Starter workflow: Construction: Watermark survey results. Linear flow (manual_trigger → openai_gpt → ai_agent → log_output). Configure credentials and fields per node; extend in the canvas.',
  'Construction',
  '[{"id":"n1","type":"custom","position":{"x":100,"y":200},"data":{"type":"manual_trigger","label":"Manual Trigger (1)"}},{"id":"n2","type":"custom","position":{"x":360,"y":200},"data":{"type":"openai_gpt","label":"Openai Gpt (2)"}},{"id":"n3","type":"custom","position":{"x":620,"y":200},"data":{"type":"ai_agent","label":"Ai Agent (3)"}},{"id":"n4","type":"custom","position":{"x":880,"y":200},"data":{"type":"log_output","label":"Log Output (4)"}}]'::jsonb,
  '[{"id":"e1","source":"n1","target":"n2","sourceHandle":"output","targetHandle":"input"},{"id":"e2","source":"n2","target":"n3","sourceHandle":"output","targetHandle":"input"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"output","targetHandle":"input"}]'::jsonb,
  'Advanced',
  25,
  ARRAY['Construction', 'manual-trigger', 'openai-gpt', 'ai-agent', 'log-output'],
  true,
  false,
  COALESCE((SELECT user_id FROM public.user_roles WHERE role = 'admin' LIMIT 1), (SELECT id FROM auth.users ORDER BY created_at LIMIT 1))
);


-- Template #472
INSERT INTO public.templates (name, description, category, nodes, edges, difficulty, estimated_setup_time, tags, is_active, is_featured, created_by)
VALUES (
  'Agriculture: Schedule grant submissions',
  'Starter workflow: Agriculture: Schedule grant submissions. Linear flow (schedule → google_drive → filter → log_output). Configure credentials and fields per node; extend in the canvas.',
  'Agriculture',
  '[{"id":"n1","type":"custom","position":{"x":100,"y":200},"data":{"type":"schedule","label":"Schedule (1)"}},{"id":"n2","type":"custom","position":{"x":360,"y":200},"data":{"type":"google_drive","label":"Google Drive (2)"}},{"id":"n3","type":"custom","position":{"x":620,"y":200},"data":{"type":"filter","label":"Filter (3)"}},{"id":"n4","type":"custom","position":{"x":880,"y":200},"data":{"type":"log_output","label":"Log Output (4)"}}]'::jsonb,
  '[{"id":"e1","source":"n1","target":"n2","sourceHandle":"output","targetHandle":"input"},{"id":"e2","source":"n2","target":"n3","sourceHandle":"output","targetHandle":"input"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"output","targetHandle":"input"}]'::jsonb,
  'Beginner',
  26,
  ARRAY['Agriculture', 'schedule', 'google-drive', 'filter', 'log-output'],
  true,
  false,
  COALESCE((SELECT user_id FROM public.user_roles WHERE role = 'admin' LIMIT 1), (SELECT id FROM auth.users ORDER BY created_at LIMIT 1))
);


-- Template #473
INSERT INTO public.templates (name, description, category, nodes, edges, difficulty, estimated_setup_time, tags, is_active, is_featured, created_by)
VALUES (
  'Energy: Publish CSV uploads',
  'Starter workflow: Energy: Publish CSV uploads. Linear flow (webhook → twitter → google_calendar → log_output). Configure credentials and fields per node; extend in the canvas.',
  'Energy',
  '[{"id":"n1","type":"custom","position":{"x":100,"y":200},"data":{"type":"webhook","label":"Webhook (1)"}},{"id":"n2","type":"custom","position":{"x":360,"y":200},"data":{"type":"twitter","label":"Twitter (2)"}},{"id":"n3","type":"custom","position":{"x":620,"y":200},"data":{"type":"google_calendar","label":"Google Calendar (3)"}},{"id":"n4","type":"custom","position":{"x":880,"y":200},"data":{"type":"log_output","label":"Log Output (4)"}}]'::jsonb,
  '[{"id":"e1","source":"n1","target":"n2","sourceHandle":"output","targetHandle":"input"},{"id":"e2","source":"n2","target":"n3","sourceHandle":"output","targetHandle":"input"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"output","targetHandle":"input"}]'::jsonb,
  'Intermediate',
  27,
  ARRAY['Energy', 'webhook', 'twitter', 'google-calendar', 'log-output'],
  true,
  false,
  COALESCE((SELECT user_id FROM public.user_roles WHERE role = 'admin' LIMIT 1), (SELECT id FROM auth.users ORDER BY created_at LIMIT 1))
);


-- Template #474
INSERT INTO public.templates (name, description, category, nodes, edges, difficulty, estimated_setup_time, tags, is_active, is_featured, created_by)
VALUES (
  'Telecom: Archive patient intake forms',
  'Starter workflow: Telecom: Archive patient intake forms. Linear flow (form → function → clickup → log_output). Configure credentials and fields per node; extend in the canvas.',
  'Telecom',
  '[{"id":"n1","type":"custom","position":{"x":100,"y":200},"data":{"type":"form","label":"Form (1)"}},{"id":"n2","type":"custom","position":{"x":360,"y":200},"data":{"type":"function","label":"Function (2)"}},{"id":"n3","type":"custom","position":{"x":620,"y":200},"data":{"type":"clickup","label":"Clickup (3)"}},{"id":"n4","type":"custom","position":{"x":880,"y":200},"data":{"type":"log_output","label":"Log Output (4)"}}]'::jsonb,
  '[{"id":"e1","source":"n1","target":"n2","sourceHandle":"output","targetHandle":"input"},{"id":"e2","source":"n2","target":"n3","sourceHandle":"output","targetHandle":"input"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"output","targetHandle":"input"}]'::jsonb,
  'Advanced',
  28,
  ARRAY['Telecom', 'form', 'function', 'clickup', 'log-output'],
  true,
  false,
  COALESCE((SELECT user_id FROM public.user_roles WHERE role = 'admin' LIMIT 1), (SELECT id FROM auth.users ORDER BY created_at LIMIT 1))
);


-- Template #475
INSERT INTO public.templates (name, description, category, nodes, edges, difficulty, estimated_setup_time, tags, is_active, is_featured, created_by)
VALUES (
  'Gov & Public Sector: Summarize backup manifests',
  'Starter workflow: Gov & Public Sector: Summarize backup manifests. Linear flow (interval → slack_message → ai_service → log_output). Configure credentials and fields per node; extend in the canvas.',
  'Public Sector',
  '[{"id":"n1","type":"custom","position":{"x":100,"y":200},"data":{"type":"interval","label":"Interval (1)"}},{"id":"n2","type":"custom","position":{"x":360,"y":200},"data":{"type":"slack_message","label":"Slack Message (2)"}},{"id":"n3","type":"custom","position":{"x":620,"y":200},"data":{"type":"ai_service","label":"Ai Service (3)"}},{"id":"n4","type":"custom","position":{"x":880,"y":200},"data":{"type":"log_output","label":"Log Output (4)"}}]'::jsonb,
  '[{"id":"e1","source":"n1","target":"n2","sourceHandle":"output","targetHandle":"input"},{"id":"e2","source":"n2","target":"n3","sourceHandle":"output","targetHandle":"input"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"output","targetHandle":"input"}]'::jsonb,
  'Beginner',
  29,
  ARRAY['Public Sector', 'interval', 'slack-message', 'ai-service', 'log-output'],
  true,
  false,
  COALESCE((SELECT user_id FROM public.user_roles WHERE role = 'admin' LIMIT 1), (SELECT id FROM auth.users ORDER BY created_at LIMIT 1))
);


-- Template #476
INSERT INTO public.templates (name, description, category, nodes, edges, difficulty, estimated_setup_time, tags, is_active, is_featured, created_by)
VALUES (
  'E-commerce: Automate experiment logs',
  'Starter workflow: E-commerce: Automate experiment logs. Linear flow (manual_trigger → json_parser → csv → log_output). Configure credentials and fields per node; extend in the canvas.',
  'Commerce & Retail',
  '[{"id":"n1","type":"custom","position":{"x":100,"y":200},"data":{"type":"manual_trigger","label":"Manual Trigger (1)"}},{"id":"n2","type":"custom","position":{"x":360,"y":200},"data":{"type":"json_parser","label":"Json Parser (2)"}},{"id":"n3","type":"custom","position":{"x":620,"y":200},"data":{"type":"csv","label":"Csv (3)"}},{"id":"n4","type":"custom","position":{"x":880,"y":200},"data":{"type":"log_output","label":"Log Output (4)"}}]'::jsonb,
  '[{"id":"e1","source":"n1","target":"n2","sourceHandle":"output","targetHandle":"input"},{"id":"e2","source":"n2","target":"n3","sourceHandle":"output","targetHandle":"input"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"output","targetHandle":"input"}]'::jsonb,
  'Intermediate',
  5,
  ARRAY['Commerce & Retail', 'manual-trigger', 'json-parser', 'csv', 'log-output'],
  true,
  false,
  COALESCE((SELECT user_id FROM public.user_roles WHERE role = 'admin' LIMIT 1), (SELECT id FROM auth.users ORDER BY created_at LIMIT 1))
);


-- Template #477
INSERT INTO public.templates (name, description, category, nodes, edges, difficulty, estimated_setup_time, tags, is_active, is_featured, created_by)
VALUES (
  'Healthcare: Deduplicate court filings',
  'Starter workflow: Healthcare: Deduplicate court filings. Linear flow (schedule → airtable → google_gmail → log_output). Configure credentials and fields per node; extend in the canvas.',
  'Healthcare',
  '[{"id":"n1","type":"custom","position":{"x":100,"y":200},"data":{"type":"schedule","label":"Schedule (1)"}},{"id":"n2","type":"custom","position":{"x":360,"y":200},"data":{"type":"airtable","label":"Airtable (2)"}},{"id":"n3","type":"custom","position":{"x":620,"y":200},"data":{"type":"google_gmail","label":"Google Gmail (3)"}},{"id":"n4","type":"custom","position":{"x":880,"y":200},"data":{"type":"log_output","label":"Log Output (4)"}}]'::jsonb,
  '[{"id":"e1","source":"n1","target":"n2","sourceHandle":"output","targetHandle":"input"},{"id":"e2","source":"n2","target":"n3","sourceHandle":"output","targetHandle":"input"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"output","targetHandle":"input"}]'::jsonb,
  'Advanced',
  6,
  ARRAY['Healthcare', 'schedule', 'airtable', 'google-gmail', 'log-output'],
  true,
  false,
  COALESCE((SELECT user_id FROM public.user_roles WHERE role = 'admin' LIMIT 1), (SELECT id FROM auth.users ORDER BY created_at LIMIT 1))
);


-- Template #478
INSERT INTO public.templates (name, description, category, nodes, edges, difficulty, estimated_setup_time, tags, is_active, is_featured, created_by)
VALUES (
  'Finance & Accounting: Parse form responses',
  'Starter workflow: Finance & Accounting: Parse form responses. Linear flow (webhook → ai_agent → notion → log_output). Configure credentials and fields per node; extend in the canvas.',
  'Finance',
  '[{"id":"n1","type":"custom","position":{"x":100,"y":200},"data":{"type":"webhook","label":"Webhook (1)"}},{"id":"n2","type":"custom","position":{"x":360,"y":200},"data":{"type":"ai_agent","label":"Ai Agent (2)"}},{"id":"n3","type":"custom","position":{"x":620,"y":200},"data":{"type":"notion","label":"Notion (3)"}},{"id":"n4","type":"custom","position":{"x":880,"y":200},"data":{"type":"log_output","label":"Log Output (4)"}}]'::jsonb,
  '[{"id":"e1","source":"n1","target":"n2","sourceHandle":"output","targetHandle":"input"},{"id":"e2","source":"n2","target":"n3","sourceHandle":"output","targetHandle":"input"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"output","targetHandle":"input"}]'::jsonb,
  'Beginner',
  7,
  ARRAY['Finance', 'webhook', 'ai-agent', 'notion', 'log-output'],
  true,
  false,
  COALESCE((SELECT user_id FROM public.user_roles WHERE role = 'admin' LIMIT 1), (SELECT id FROM auth.users ORDER BY created_at LIMIT 1))
);


-- Template #479
INSERT INTO public.templates (name, description, category, nodes, edges, difficulty, estimated_setup_time, tags, is_active, is_featured, created_by)
VALUES (
  'HR & People: Monitor sensor readings',
  'Starter workflow: HR & People: Monitor sensor readings. Linear flow (form → google_calendar → twitter → log_output). Configure credentials and fields per node; extend in the canvas.',
  'HR',
  '[{"id":"n1","type":"custom","position":{"x":100,"y":200},"data":{"type":"form","label":"Form (1)"}},{"id":"n2","type":"custom","position":{"x":360,"y":200},"data":{"type":"google_calendar","label":"Google Calendar (2)"}},{"id":"n3","type":"custom","position":{"x":620,"y":200},"data":{"type":"twitter","label":"Twitter (3)"}},{"id":"n4","type":"custom","position":{"x":880,"y":200},"data":{"type":"log_output","label":"Log Output (4)"}}]'::jsonb,
  '[{"id":"e1","source":"n1","target":"n2","sourceHandle":"output","targetHandle":"input"},{"id":"e2","source":"n2","target":"n3","sourceHandle":"output","targetHandle":"input"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"output","targetHandle":"input"}]'::jsonb,
  'Intermediate',
  8,
  ARRAY['HR', 'form', 'google-calendar', 'twitter', 'log-output'],
  true,
  false,
  COALESCE((SELECT user_id FROM public.user_roles WHERE role = 'admin' LIMIT 1), (SELECT id FROM auth.users ORDER BY created_at LIMIT 1))
);


-- Template #480
INSERT INTO public.templates (name, description, category, nodes, edges, difficulty, estimated_setup_time, tags, is_active, is_featured, created_by)
VALUES (
  'DevOps & SRE: Aggregate compliance exports',
  'Starter workflow: DevOps & SRE: Aggregate compliance exports. Linear flow (interval → linkedin → set_variable → log_output). Configure credentials and fields per node; extend in the canvas.',
  'Developer Tools',
  '[{"id":"n1","type":"custom","position":{"x":100,"y":200},"data":{"type":"interval","label":"Interval (1)"}},{"id":"n2","type":"custom","position":{"x":360,"y":200},"data":{"type":"linkedin","label":"Linkedin (2)"}},{"id":"n3","type":"custom","position":{"x":620,"y":200},"data":{"type":"set_variable","label":"Set Variable (3)"}},{"id":"n4","type":"custom","position":{"x":880,"y":200},"data":{"type":"log_output","label":"Log Output (4)"}}]'::jsonb,
  '[{"id":"e1","source":"n1","target":"n2","sourceHandle":"output","targetHandle":"input"},{"id":"e2","source":"n2","target":"n3","sourceHandle":"output","targetHandle":"input"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"output","targetHandle":"input"}]'::jsonb,
  'Advanced',
  9,
  ARRAY['Developer Tools', 'interval', 'linkedin', 'set-variable', 'log-output'],
  true,
  false,
  COALESCE((SELECT user_id FROM public.user_roles WHERE role = 'admin' LIMIT 1), (SELECT id FROM auth.users ORDER BY created_at LIMIT 1))
);


-- Template #481
INSERT INTO public.templates (name, description, category, nodes, edges, difficulty, estimated_setup_time, tags, is_active, is_featured, created_by)
VALUES (
  'Marketing: Validate feature flags',
  'Starter workflow: Marketing: Validate feature flags. Linear flow (manual_trigger → http_request → google_sheets → log_output). Configure credentials and fields per node; extend in the canvas.',
  'Marketing & Growth',
  '[{"id":"n1","type":"custom","position":{"x":100,"y":200},"data":{"type":"manual_trigger","label":"Manual Trigger (1)"}},{"id":"n2","type":"custom","position":{"x":360,"y":200},"data":{"type":"http_request","label":"Http Request (2)"}},{"id":"n3","type":"custom","position":{"x":620,"y":200},"data":{"type":"google_sheets","label":"Google Sheets (3)"}},{"id":"n4","type":"custom","position":{"x":880,"y":200},"data":{"type":"log_output","label":"Log Output (4)"}}]'::jsonb,
  '[{"id":"e1","source":"n1","target":"n2","sourceHandle":"output","targetHandle":"input"},{"id":"e2","source":"n2","target":"n3","sourceHandle":"output","targetHandle":"input"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"output","targetHandle":"input"}]'::jsonb,
  'Beginner',
  10,
  ARRAY['Marketing & Growth', 'manual-trigger', 'http-request', 'google-sheets', 'log-output'],
  true,
  false,
  COALESCE((SELECT user_id FROM public.user_roles WHERE role = 'admin' LIMIT 1), (SELECT id FROM auth.users ORDER BY created_at LIMIT 1))
);


-- Template #482
INSERT INTO public.templates (name, description, category, nodes, edges, difficulty, estimated_setup_time, tags, is_active, is_featured, created_by)
VALUES (
  'Customer Support: Reconcile asset depreciations',
  'Starter workflow: Customer Support: Reconcile asset depreciations. Linear flow (schedule → telegram → mongodb → log_output). Configure credentials and fields per node; extend in the canvas.',
  'Support',
  '[{"id":"n1","type":"custom","position":{"x":100,"y":200},"data":{"type":"schedule","label":"Schedule (1)"}},{"id":"n2","type":"custom","position":{"x":360,"y":200},"data":{"type":"telegram","label":"Telegram (2)"}},{"id":"n3","type":"custom","position":{"x":620,"y":200},"data":{"type":"mongodb","label":"Mongodb (3)"}},{"id":"n4","type":"custom","position":{"x":880,"y":200},"data":{"type":"log_output","label":"Log Output (4)"}}]'::jsonb,
  '[{"id":"e1","source":"n1","target":"n2","sourceHandle":"output","targetHandle":"input"},{"id":"e2","source":"n2","target":"n3","sourceHandle":"output","targetHandle":"input"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"output","targetHandle":"input"}]'::jsonb,
  'Intermediate',
  11,
  ARRAY['Support', 'schedule', 'telegram', 'mongodb', 'log-output'],
  true,
  false,
  COALESCE((SELECT user_id FROM public.user_roles WHERE role = 'admin' LIMIT 1), (SELECT id FROM auth.users ORDER BY created_at LIMIT 1))
);


-- Template #483
INSERT INTO public.templates (name, description, category, nodes, edges, difficulty, estimated_setup_time, tags, is_active, is_featured, created_by)
VALUES (
  'Education: Notify stakeholders about webhook payloads',
  'Starter workflow: Education: Notify stakeholders about webhook payloads. Linear flow (webhook → csv → email → log_output). Configure credentials and fields per node; extend in the canvas.',
  'Education',
  '[{"id":"n1","type":"custom","position":{"x":100,"y":200},"data":{"type":"webhook","label":"Webhook (1)"}},{"id":"n2","type":"custom","position":{"x":360,"y":200},"data":{"type":"csv","label":"Csv (2)"}},{"id":"n3","type":"custom","position":{"x":620,"y":200},"data":{"type":"email","label":"Email (3)"}},{"id":"n4","type":"custom","position":{"x":880,"y":200},"data":{"type":"log_output","label":"Log Output (4)"}}]'::jsonb,
  '[{"id":"e1","source":"n1","target":"n2","sourceHandle":"output","targetHandle":"input"},{"id":"e2","source":"n2","target":"n3","sourceHandle":"output","targetHandle":"input"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"output","targetHandle":"input"}]'::jsonb,
  'Advanced',
  12,
  ARRAY['Education', 'webhook', 'csv', 'email', 'log-output'],
  true,
  false,
  COALESCE((SELECT user_id FROM public.user_roles WHERE role = 'admin' LIMIT 1), (SELECT id FROM auth.users ORDER BY created_at LIMIT 1))
);


-- Template #484
INSERT INTO public.templates (name, description, category, nodes, edges, difficulty, estimated_setup_time, tags, is_active, is_featured, created_by)
VALUES (
  'Real Estate: Tag and classify shipment events',
  'Starter workflow: Real Estate: Tag and classify shipment events. Linear flow (form → notion → ai_agent → log_output). Configure credentials and fields per node; extend in the canvas.',
  'Real Estate',
  '[{"id":"n1","type":"custom","position":{"x":100,"y":200},"data":{"type":"form","label":"Form (1)"}},{"id":"n2","type":"custom","position":{"x":360,"y":200},"data":{"type":"notion","label":"Notion (2)"}},{"id":"n3","type":"custom","position":{"x":620,"y":200},"data":{"type":"ai_agent","label":"Ai Agent (3)"}},{"id":"n4","type":"custom","position":{"x":880,"y":200},"data":{"type":"log_output","label":"Log Output (4)"}}]'::jsonb,
  '[{"id":"e1","source":"n1","target":"n2","sourceHandle":"output","targetHandle":"input"},{"id":"e2","source":"n2","target":"n3","sourceHandle":"output","targetHandle":"input"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"output","targetHandle":"input"}]'::jsonb,
  'Beginner',
  13,
  ARRAY['Real Estate', 'form', 'notion', 'ai-agent', 'log-output'],
  true,
  true,
  COALESCE((SELECT user_id FROM public.user_roles WHERE role = 'admin' LIMIT 1), (SELECT id FROM auth.users ORDER BY created_at LIMIT 1))
);


-- Template #485
INSERT INTO public.templates (name, description, category, nodes, edges, difficulty, estimated_setup_time, tags, is_active, is_featured, created_by)
VALUES (
  'Legal Ops: Handshake security findings',
  'Starter workflow: Legal Ops: Handshake security findings. Linear flow (interval → ai_chat_model → text_formatter → log_output). Configure credentials and fields per node; extend in the canvas.',
  'Legal',
  '[{"id":"n1","type":"custom","position":{"x":100,"y":200},"data":{"type":"interval","label":"Interval (1)"}},{"id":"n2","type":"custom","position":{"x":360,"y":200},"data":{"type":"ai_chat_model","label":"Ai Chat Model (2)"}},{"id":"n3","type":"custom","position":{"x":620,"y":200},"data":{"type":"text_formatter","label":"Text Formatter (3)"}},{"id":"n4","type":"custom","position":{"x":880,"y":200},"data":{"type":"log_output","label":"Log Output (4)"}}]'::jsonb,
  '[{"id":"e1","source":"n1","target":"n2","sourceHandle":"output","targetHandle":"input"},{"id":"e2","source":"n2","target":"n3","sourceHandle":"output","targetHandle":"input"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"output","targetHandle":"input"}]'::jsonb,
  'Intermediate',
  14,
  ARRAY['Legal', 'interval', 'ai-chat-model', 'text-formatter', 'log-output'],
  true,
  false,
  COALESCE((SELECT user_id FROM public.user_roles WHERE role = 'admin' LIMIT 1), (SELECT id FROM auth.users ORDER BY created_at LIMIT 1))
);


-- Template #486
INSERT INTO public.templates (name, description, category, nodes, edges, difficulty, estimated_setup_time, tags, is_active, is_featured, created_by)
VALUES (
  'Manufacturing: Enrich release notes',
  'Starter workflow: Manufacturing: Enrich release notes. Linear flow (manual_trigger → postgresql → mysql → log_output). Configure credentials and fields per node; extend in the canvas.',
  'Operations',
  '[{"id":"n1","type":"custom","position":{"x":100,"y":200},"data":{"type":"manual_trigger","label":"Manual Trigger (1)"}},{"id":"n2","type":"custom","position":{"x":360,"y":200},"data":{"type":"postgresql","label":"Postgresql (2)"}},{"id":"n3","type":"custom","position":{"x":620,"y":200},"data":{"type":"mysql","label":"Mysql (3)"}},{"id":"n4","type":"custom","position":{"x":880,"y":200},"data":{"type":"log_output","label":"Log Output (4)"}}]'::jsonb,
  '[{"id":"e1","source":"n1","target":"n2","sourceHandle":"output","targetHandle":"input"},{"id":"e2","source":"n2","target":"n3","sourceHandle":"output","targetHandle":"input"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"output","targetHandle":"input"}]'::jsonb,
  'Advanced',
  15,
  ARRAY['Operations', 'manual-trigger', 'postgresql', 'mysql', 'log-output'],
  true,
  false,
  COALESCE((SELECT user_id FROM public.user_roles WHERE role = 'admin' LIMIT 1), (SELECT id FROM auth.users ORDER BY created_at LIMIT 1))
);


-- Template #487
INSERT INTO public.templates (name, description, category, nodes, edges, difficulty, estimated_setup_time, tags, is_active, is_featured, created_by)
VALUES (
  'Nonprofit: Redact course enrollments',
  'Starter workflow: Nonprofit: Redact course enrollments. Linear flow (schedule → ai_service → slack_message → log_output). Configure credentials and fields per node; extend in the canvas.',
  'Nonprofit',
  '[{"id":"n1","type":"custom","position":{"x":100,"y":200},"data":{"type":"schedule","label":"Schedule (1)"}},{"id":"n2","type":"custom","position":{"x":360,"y":200},"data":{"type":"ai_service","label":"Ai Service (2)"}},{"id":"n3","type":"custom","position":{"x":620,"y":200},"data":{"type":"slack_message","label":"Slack Message (3)"}},{"id":"n4","type":"custom","position":{"x":880,"y":200},"data":{"type":"log_output","label":"Log Output (4)"}}]'::jsonb,
  '[{"id":"e1","source":"n1","target":"n2","sourceHandle":"output","targetHandle":"input"},{"id":"e2","source":"n2","target":"n3","sourceHandle":"output","targetHandle":"input"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"output","targetHandle":"input"}]'::jsonb,
  'Beginner',
  16,
  ARRAY['Nonprofit', 'schedule', 'ai-service', 'slack-message', 'log-output'],
  true,
  false,
  COALESCE((SELECT user_id FROM public.user_roles WHERE role = 'admin' LIMIT 1), (SELECT id FROM auth.users ORDER BY created_at LIMIT 1))
);


-- Template #488
INSERT INTO public.templates (name, description, category, nodes, edges, difficulty, estimated_setup_time, tags, is_active, is_featured, created_by)
VALUES (
  'Media & Publishing: Extract metrics from daily KPIs',
  'Starter workflow: Media & Publishing: Extract metrics from daily KPIs. Linear flow (webhook → google_sheets → ollama → log_output). Configure credentials and fields per node; extend in the canvas.',
  'Media',
  '[{"id":"n1","type":"custom","position":{"x":100,"y":200},"data":{"type":"webhook","label":"Webhook (1)"}},{"id":"n2","type":"custom","position":{"x":360,"y":200},"data":{"type":"google_sheets","label":"Google Sheets (2)"}},{"id":"n3","type":"custom","position":{"x":620,"y":200},"data":{"type":"ollama","label":"Ollama (3)"}},{"id":"n4","type":"custom","position":{"x":880,"y":200},"data":{"type":"log_output","label":"Log Output (4)"}}]'::jsonb,
  '[{"id":"e1","source":"n1","target":"n2","sourceHandle":"output","targetHandle":"input"},{"id":"e2","source":"n2","target":"n3","sourceHandle":"output","targetHandle":"input"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"output","targetHandle":"input"}]'::jsonb,
  'Intermediate',
  17,
  ARRAY['Media', 'webhook', 'google-sheets', 'ollama', 'log-output'],
  true,
  false,
  COALESCE((SELECT user_id FROM public.user_roles WHERE role = 'admin' LIMIT 1), (SELECT id FROM auth.users ORDER BY created_at LIMIT 1))
);


-- Template #489
INSERT INTO public.templates (name, description, category, nodes, edges, difficulty, estimated_setup_time, tags, is_active, is_featured, created_by)
VALUES (
  'Logistics: Triage social mentions',
  'Starter workflow: Logistics: Triage social mentions. Linear flow (form → email → csv → log_output). Configure credentials and fields per node; extend in the canvas.',
  'Logistics',
  '[{"id":"n1","type":"custom","position":{"x":100,"y":200},"data":{"type":"form","label":"Form (1)"}},{"id":"n2","type":"custom","position":{"x":360,"y":200},"data":{"type":"email","label":"Email (2)"}},{"id":"n3","type":"custom","position":{"x":620,"y":200},"data":{"type":"csv","label":"Csv (3)"}},{"id":"n4","type":"custom","position":{"x":880,"y":200},"data":{"type":"log_output","label":"Log Output (4)"}}]'::jsonb,
  '[{"id":"e1","source":"n1","target":"n2","sourceHandle":"output","targetHandle":"input"},{"id":"e2","source":"n2","target":"n3","sourceHandle":"output","targetHandle":"input"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"output","targetHandle":"input"}]'::jsonb,
  'Advanced',
  18,
  ARRAY['Logistics', 'form', 'email', 'csv', 'log-output'],
  true,
  false,
  COALESCE((SELECT user_id FROM public.user_roles WHERE role = 'admin' LIMIT 1), (SELECT id FROM auth.users ORDER BY created_at LIMIT 1))
);


-- Template #490
INSERT INTO public.templates (name, description, category, nodes, edges, difficulty, estimated_setup_time, tags, is_active, is_featured, created_by)
VALUES (
  'Hospitality: Transform partner SLAs',
  'Starter workflow: Hospitality: Transform partner SLAs. Linear flow (interval → filter → google_drive → log_output). Configure credentials and fields per node; extend in the canvas.',
  'Hospitality',
  '[{"id":"n1","type":"custom","position":{"x":100,"y":200},"data":{"type":"interval","label":"Interval (1)"}},{"id":"n2","type":"custom","position":{"x":360,"y":200},"data":{"type":"filter","label":"Filter (2)"}},{"id":"n3","type":"custom","position":{"x":620,"y":200},"data":{"type":"google_drive","label":"Google Drive (3)"}},{"id":"n4","type":"custom","position":{"x":880,"y":200},"data":{"type":"log_output","label":"Log Output (4)"}}]'::jsonb,
  '[{"id":"e1","source":"n1","target":"n2","sourceHandle":"output","targetHandle":"input"},{"id":"e2","source":"n2","target":"n3","sourceHandle":"output","targetHandle":"input"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"output","targetHandle":"input"}]'::jsonb,
  'Beginner',
  19,
  ARRAY['Hospitality', 'interval', 'filter', 'google-drive', 'log-output'],
  true,
  false,
  COALESCE((SELECT user_id FROM public.user_roles WHERE role = 'admin' LIMIT 1), (SELECT id FROM auth.users ORDER BY created_at LIMIT 1))
);


-- Template #491
INSERT INTO public.templates (name, description, category, nodes, edges, difficulty, estimated_setup_time, tags, is_active, is_featured, created_by)
VALUES (
  'SaaS Product: Back up on-call incidents',
  'Starter workflow: SaaS Product: Back up on-call incidents. Linear flow (manual_trigger → hubspot → clickup → log_output). Configure credentials and fields per node; extend in the canvas.',
  'Product',
  '[{"id":"n1","type":"custom","position":{"x":100,"y":200},"data":{"type":"manual_trigger","label":"Manual Trigger (1)"}},{"id":"n2","type":"custom","position":{"x":360,"y":200},"data":{"type":"hubspot","label":"Hubspot (2)"}},{"id":"n3","type":"custom","position":{"x":620,"y":200},"data":{"type":"clickup","label":"Clickup (3)"}},{"id":"n4","type":"custom","position":{"x":880,"y":200},"data":{"type":"log_output","label":"Log Output (4)"}}]'::jsonb,
  '[{"id":"e1","source":"n1","target":"n2","sourceHandle":"output","targetHandle":"input"},{"id":"e2","source":"n2","target":"n3","sourceHandle":"output","targetHandle":"input"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"output","targetHandle":"input"}]'::jsonb,
  'Intermediate',
  20,
  ARRAY['Product', 'manual-trigger', 'hubspot', 'clickup', 'log-output'],
  true,
  false,
  COALESCE((SELECT user_id FROM public.user_roles WHERE role = 'admin' LIMIT 1), (SELECT id FROM auth.users ORDER BY created_at LIMIT 1))
);


-- Template #492
INSERT INTO public.templates (name, description, category, nodes, edges, difficulty, estimated_setup_time, tags, is_active, is_featured, created_by)
VALUES (
  'IT Service Desk: Sync room bookings',
  'Starter workflow: IT Service Desk: Sync room bookings. Linear flow (schedule → set_variable → linkedin → log_output). Configure credentials and fields per node; extend in the canvas.',
  'IT',
  '[{"id":"n1","type":"custom","position":{"x":100,"y":200},"data":{"type":"schedule","label":"Schedule (1)"}},{"id":"n2","type":"custom","position":{"x":360,"y":200},"data":{"type":"set_variable","label":"Set Variable (2)"}},{"id":"n3","type":"custom","position":{"x":620,"y":200},"data":{"type":"linkedin","label":"Linkedin (3)"}},{"id":"n4","type":"custom","position":{"x":880,"y":200},"data":{"type":"log_output","label":"Log Output (4)"}}]'::jsonb,
  '[{"id":"e1","source":"n1","target":"n2","sourceHandle":"output","targetHandle":"input"},{"id":"e2","source":"n2","target":"n3","sourceHandle":"output","targetHandle":"input"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"output","targetHandle":"input"}]'::jsonb,
  'Advanced',
  21,
  ARRAY['IT', 'schedule', 'set-variable', 'linkedin', 'log-output'],
  true,
  false,
  COALESCE((SELECT user_id FROM public.user_roles WHERE role = 'admin' LIMIT 1), (SELECT id FROM auth.users ORDER BY created_at LIMIT 1))
);


-- Template #493
INSERT INTO public.templates (name, description, category, nodes, edges, difficulty, estimated_setup_time, tags, is_active, is_featured, created_by)
VALUES (
  'Sales Ops: Score calendar holds',
  'Starter workflow: Sales Ops: Score calendar holds. Linear flow (webhook → mysql → javascript → log_output). Configure credentials and fields per node; extend in the canvas.',
  'CRM & Sales',
  '[{"id":"n1","type":"custom","position":{"x":100,"y":200},"data":{"type":"webhook","label":"Webhook (1)"}},{"id":"n2","type":"custom","position":{"x":360,"y":200},"data":{"type":"mysql","label":"Mysql (2)"}},{"id":"n3","type":"custom","position":{"x":620,"y":200},"data":{"type":"javascript","label":"Javascript (3)"}},{"id":"n4","type":"custom","position":{"x":880,"y":200},"data":{"type":"log_output","label":"Log Output (4)"}}]'::jsonb,
  '[{"id":"e1","source":"n1","target":"n2","sourceHandle":"output","targetHandle":"input"},{"id":"e2","source":"n2","target":"n3","sourceHandle":"output","targetHandle":"input"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"output","targetHandle":"input"}]'::jsonb,
  'Beginner',
  22,
  ARRAY['CRM & Sales', 'webhook', 'mysql', 'javascript', 'log-output'],
  true,
  false,
  COALESCE((SELECT user_id FROM public.user_roles WHERE role = 'admin' LIMIT 1), (SELECT id FROM auth.users ORDER BY created_at LIMIT 1))
);


-- Template #494
INSERT INTO public.templates (name, description, category, nodes, edges, difficulty, estimated_setup_time, tags, is_active, is_featured, created_by)
VALUES (
  'Data Analytics: Normalize help-center articles',
  'Starter workflow: Data Analytics: Normalize help-center articles. Linear flow (form → ollama → google_sheets → log_output). Configure credentials and fields per node; extend in the canvas.',
  'Data & BI',
  '[{"id":"n1","type":"custom","position":{"x":100,"y":200},"data":{"type":"form","label":"Form (1)"}},{"id":"n2","type":"custom","position":{"x":360,"y":200},"data":{"type":"ollama","label":"Ollama (2)"}},{"id":"n3","type":"custom","position":{"x":620,"y":200},"data":{"type":"google_sheets","label":"Google Sheets (3)"}},{"id":"n4","type":"custom","position":{"x":880,"y":200},"data":{"type":"log_output","label":"Log Output (4)"}}]'::jsonb,
  '[{"id":"e1","source":"n1","target":"n2","sourceHandle":"output","targetHandle":"input"},{"id":"e2","source":"n2","target":"n3","sourceHandle":"output","targetHandle":"input"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"output","targetHandle":"input"}]'::jsonb,
  'Intermediate',
  23,
  ARRAY['Data & BI', 'form', 'ollama', 'google-sheets', 'log-output'],
  true,
  false,
  COALESCE((SELECT user_id FROM public.user_roles WHERE role = 'admin' LIMIT 1), (SELECT id FROM auth.users ORDER BY created_at LIMIT 1))
);


-- Template #495
INSERT INTO public.templates (name, description, category, nodes, edges, difficulty, estimated_setup_time, tags, is_active, is_featured, created_by)
VALUES (
  'Security & GRC: Route board packets',
  'Starter workflow: Security & GRC: Route board packets. Linear flow (interval → google_gmail → airtable → log_output). Configure credentials and fields per node; extend in the canvas.',
  'Security',
  '[{"id":"n1","type":"custom","position":{"x":100,"y":200},"data":{"type":"interval","label":"Interval (1)"}},{"id":"n2","type":"custom","position":{"x":360,"y":200},"data":{"type":"google_gmail","label":"Google Gmail (2)"}},{"id":"n3","type":"custom","position":{"x":620,"y":200},"data":{"type":"airtable","label":"Airtable (3)"}},{"id":"n4","type":"custom","position":{"x":880,"y":200},"data":{"type":"log_output","label":"Log Output (4)"}}]'::jsonb,
  '[{"id":"e1","source":"n1","target":"n2","sourceHandle":"output","targetHandle":"input"},{"id":"e2","source":"n2","target":"n3","sourceHandle":"output","targetHandle":"input"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"output","targetHandle":"input"}]'::jsonb,
  'Advanced',
  24,
  ARRAY['Security', 'interval', 'google-gmail', 'airtable', 'log-output'],
  true,
  false,
  COALESCE((SELECT user_id FROM public.user_roles WHERE role = 'admin' LIMIT 1), (SELECT id FROM auth.users ORDER BY created_at LIMIT 1))
);


-- Template #496
INSERT INTO public.templates (name, description, category, nodes, edges, difficulty, estimated_setup_time, tags, is_active, is_featured, created_by)
VALUES (
  'Construction: Watermark vendor bills',
  'Starter workflow: Construction: Watermark vendor bills. Linear flow (manual_trigger → outlook → twitter → log_output). Configure credentials and fields per node; extend in the canvas.',
  'Construction',
  '[{"id":"n1","type":"custom","position":{"x":100,"y":200},"data":{"type":"manual_trigger","label":"Manual Trigger (1)"}},{"id":"n2","type":"custom","position":{"x":360,"y":200},"data":{"type":"outlook","label":"Outlook (2)"}},{"id":"n3","type":"custom","position":{"x":620,"y":200},"data":{"type":"twitter","label":"Twitter (3)"}},{"id":"n4","type":"custom","position":{"x":880,"y":200},"data":{"type":"log_output","label":"Log Output (4)"}}]'::jsonb,
  '[{"id":"e1","source":"n1","target":"n2","sourceHandle":"output","targetHandle":"input"},{"id":"e2","source":"n2","target":"n3","sourceHandle":"output","targetHandle":"input"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"output","targetHandle":"input"}]'::jsonb,
  'Beginner',
  25,
  ARRAY['Construction', 'manual-trigger', 'outlook', 'twitter', 'log-output'],
  true,
  false,
  COALESCE((SELECT user_id FROM public.user_roles WHERE role = 'admin' LIMIT 1), (SELECT id FROM auth.users ORDER BY created_at LIMIT 1))
);


-- Template #497
INSERT INTO public.templates (name, description, category, nodes, edges, difficulty, estimated_setup_time, tags, is_active, is_featured, created_by)
VALUES (
  'Agriculture: Schedule prescription refills',
  'Starter workflow: Agriculture: Schedule prescription refills. Linear flow (schedule → text_formatter → ai_chat_model → log_output). Configure credentials and fields per node; extend in the canvas.',
  'Agriculture',
  '[{"id":"n1","type":"custom","position":{"x":100,"y":200},"data":{"type":"schedule","label":"Schedule (1)"}},{"id":"n2","type":"custom","position":{"x":360,"y":200},"data":{"type":"text_formatter","label":"Text Formatter (2)"}},{"id":"n3","type":"custom","position":{"x":620,"y":200},"data":{"type":"ai_chat_model","label":"Ai Chat Model (3)"}},{"id":"n4","type":"custom","position":{"x":880,"y":200},"data":{"type":"log_output","label":"Log Output (4)"}}]'::jsonb,
  '[{"id":"e1","source":"n1","target":"n2","sourceHandle":"output","targetHandle":"input"},{"id":"e2","source":"n2","target":"n3","sourceHandle":"output","targetHandle":"input"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"output","targetHandle":"input"}]'::jsonb,
  'Intermediate',
  26,
  ARRAY['Agriculture', 'schedule', 'text-formatter', 'ai-chat-model', 'log-output'],
  true,
  false,
  COALESCE((SELECT user_id FROM public.user_roles WHERE role = 'admin' LIMIT 1), (SELECT id FROM auth.users ORDER BY created_at LIMIT 1))
);


-- Template #498
INSERT INTO public.templates (name, description, category, nodes, edges, difficulty, estimated_setup_time, tags, is_active, is_featured, created_by)
VALUES (
  'Energy: Publish inventory deltas',
  'Starter workflow: Energy: Publish inventory deltas. Linear flow (webhook → clickup → function → log_output). Configure credentials and fields per node; extend in the canvas.',
  'Energy',
  '[{"id":"n1","type":"custom","position":{"x":100,"y":200},"data":{"type":"webhook","label":"Webhook (1)"}},{"id":"n2","type":"custom","position":{"x":360,"y":200},"data":{"type":"clickup","label":"Clickup (2)"}},{"id":"n3","type":"custom","position":{"x":620,"y":200},"data":{"type":"function","label":"Function (3)"}},{"id":"n4","type":"custom","position":{"x":880,"y":200},"data":{"type":"log_output","label":"Log Output (4)"}}]'::jsonb,
  '[{"id":"e1","source":"n1","target":"n2","sourceHandle":"output","targetHandle":"input"},{"id":"e2","source":"n2","target":"n3","sourceHandle":"output","targetHandle":"input"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"output","targetHandle":"input"}]'::jsonb,
  'Advanced',
  27,
  ARRAY['Energy', 'webhook', 'clickup', 'function', 'log-output'],
  true,
  false,
  COALESCE((SELECT user_id FROM public.user_roles WHERE role = 'admin' LIMIT 1), (SELECT id FROM auth.users ORDER BY created_at LIMIT 1))
);


-- Template #499
INSERT INTO public.templates (name, description, category, nodes, edges, difficulty, estimated_setup_time, tags, is_active, is_featured, created_by)
VALUES (
  'Telecom: Archive warehouse scans',
  'Starter workflow: Telecom: Archive warehouse scans. Linear flow (form → javascript → mysql → log_output). Configure credentials and fields per node; extend in the canvas.',
  'Telecom',
  '[{"id":"n1","type":"custom","position":{"x":100,"y":200},"data":{"type":"form","label":"Form (1)"}},{"id":"n2","type":"custom","position":{"x":360,"y":200},"data":{"type":"javascript","label":"Javascript (2)"}},{"id":"n3","type":"custom","position":{"x":620,"y":200},"data":{"type":"mysql","label":"Mysql (3)"}},{"id":"n4","type":"custom","position":{"x":880,"y":200},"data":{"type":"log_output","label":"Log Output (4)"}}]'::jsonb,
  '[{"id":"e1","source":"n1","target":"n2","sourceHandle":"output","targetHandle":"input"},{"id":"e2","source":"n2","target":"n3","sourceHandle":"output","targetHandle":"input"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"output","targetHandle":"input"}]'::jsonb,
  'Beginner',
  28,
  ARRAY['Telecom', 'form', 'javascript', 'mysql', 'log-output'],
  true,
  false,
  COALESCE((SELECT user_id FROM public.user_roles WHERE role = 'admin' LIMIT 1), (SELECT id FROM auth.users ORDER BY created_at LIMIT 1))
);


-- Template #500
INSERT INTO public.templates (name, description, category, nodes, edges, difficulty, estimated_setup_time, tags, is_active, is_featured, created_by)
VALUES (
  'Gov & Public Sector: Summarize NPS feedback',
  'Starter workflow: Gov & Public Sector: Summarize NPS feedback. Linear flow (interval → mongodb → telegram → log_output). Configure credentials and fields per node; extend in the canvas.',
  'Public Sector',
  '[{"id":"n1","type":"custom","position":{"x":100,"y":200},"data":{"type":"interval","label":"Interval (1)"}},{"id":"n2","type":"custom","position":{"x":360,"y":200},"data":{"type":"mongodb","label":"Mongodb (2)"}},{"id":"n3","type":"custom","position":{"x":620,"y":200},"data":{"type":"telegram","label":"Telegram (3)"}},{"id":"n4","type":"custom","position":{"x":880,"y":200},"data":{"type":"log_output","label":"Log Output (4)"}}]'::jsonb,
  '[{"id":"e1","source":"n1","target":"n2","sourceHandle":"output","targetHandle":"input"},{"id":"e2","source":"n2","target":"n3","sourceHandle":"output","targetHandle":"input"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"output","targetHandle":"input"}]'::jsonb,
  'Intermediate',
  29,
  ARRAY['Public Sector', 'interval', 'mongodb', 'telegram', 'log-output'],
  true,
  false,
  COALESCE((SELECT user_id FROM public.user_roles WHERE role = 'admin' LIMIT 1), (SELECT id FROM auth.users ORDER BY created_at LIMIT 1))
);


COMMIT;
