export const NODE_LAYMAN_DESCRIPTIONS: Record<string, string> = {
  // ── Triggers ──────────────────────────────────────────────────────────────
  chat_trigger:     "Starts your workflow when someone types a message in a chat interface",
  error_trigger:    "Runs a recovery workflow automatically whenever another workflow crashes or fails",
  interval:         "Runs your workflow repeatedly on a fixed timer — like every 5 minutes or every hour, forever",
  manual_trigger:   "You press a button to start the workflow yourself, whenever you want",
  schedule:         "Works like an alarm clock — runs your workflow automatically at a specific time you set each day",
  webhook:          "Starts your workflow the moment another app sends it data — like a doorbell for your automation",
  workflow_trigger: "Lets one workflow kick off another — useful for chaining automations together",
  form:             "Starts your workflow when someone fills out and submits a web form you built",

  // ── Core Logic ────────────────────────────────────────────────────────────
  error_handler:          "Catches errors so your workflow can retry or recover instead of stopping completely",
  filter:                 "Keeps only the items that match your rule and discards the rest — like filtering rows in a spreadsheet",
  if_else:                "Makes a yes/no decision: if something is true, go one way; otherwise go another",
  loop:                   "Repeats a set of actions for each item in a list — like doing the same thing for every row",
  merge:                  "Combines results coming from two paths into one",
  noop:                   "Does nothing — passes data through unchanged; useful as a placeholder",
  split_in_batches:       "Breaks a large list into smaller chunks and processes them group by group",
  stop_and_error:         "Deliberately stops the workflow and raises an error — enforces a rule that must not be broken",
  switch:                 "Routes your data down different paths depending on a value — like a multi-way traffic signal",
  wait:                   "Pauses the workflow for a set amount of time before continuing",
  human_approval:         "Pauses and waits for a real person to review and approve before continuing",
  escalation_router:      "Routes a request to the right team based on how urgent it is",
  fallback_router:        "Tries a backup option if the main path fails — your automation's safety net",
  retry_with_backoff:     "Automatically retries a failed step, waiting a bit longer each time before trying again",
  timeout_guard:          "Cancels a step that takes too long, preventing your workflow from hanging indefinitely",
  circuit_breaker:        "Stops calling a failing service after too many errors, giving it time to recover",
  workflow_state_manager: "Saves a snapshot of your workflow's progress so it can pick up where it left off",
  execution_context_store:"Stores a value mid-workflow so later steps can read it — like a shared sticky note",
  session_manager:        "Creates and tracks a user session to identify the same person across multiple steps",

  // ── Data Manipulation ─────────────────────────────────────────────────────
  aggregate:      "Adds up, averages, or counts a list of values into a single result",
  csv:            "Reads or writes spreadsheet-style CSV files — converts rows and columns into usable data",
  edit_fields:    "Changes specific fields in your data — add, rename, or delete individual properties",
  execute_command:"Runs a system command on your server — powerful, use with care",
  function:       "Runs a small piece of custom code you write, giving you full control over data transformation",
  function_item:  "Runs custom code on each item in a list, one at a time",
  item_lists:     "Tools for working with lists — split, combine, or rearrange items in an array",
  javascript:     "Writes and runs any JavaScript you like to transform or process your data",
  json_parser:    "Picks a specific value out of a JSON structure using a path — like finding a needle in a haystack",
  limit:          "Cuts a list down to a maximum number of items — keeps only the first N results",
  merge_data:     "Combines two pieces of data together — merges objects or joins arrays",
  rename_keys:    "Renames the field names in your data — like renaming column headers in a spreadsheet",
  set:            "Adds or overwrites specific fields with values you provide",
  set_variable:   "Saves a value under a name so you can reuse it in later steps",
  sort:           "Sorts a list alphabetically, numerically, or by date",
  text_formatter: "Builds a piece of text by filling in a template with your data — like mail merge",

  // ── Google ────────────────────────────────────────────────────────────────
  google_bigquery:  "Runs queries against Google's massive cloud database — great for analyzing huge datasets",
  google_calendar:  "Read, create, update, or delete events in your Google Calendar",
  google_contacts:  "Read or manage the contacts saved in your Google account",
  google_doc:       "Read from or write to a Google Doc — create documents or update them automatically",
  google_drive:     "Upload, download, list, or delete files in your Google Drive",
  google_gmail:     "Send emails from your Gmail account or read and search messages in your inbox",
  google_sheets:    "Read rows from a Google Sheet or write new data into one — like Excel, but automated",
  google_tasks:     "Create, complete, or manage your Google Tasks to-do items automatically",

  // ── AI & ML ───────────────────────────────────────────────────────────────
  ai_agent:                    "An autonomous AI brain that reasons, makes decisions, and uses tools on your behalf",
  anthropic_claude:            "Sends your text to Anthropic's Claude AI and gets back a smart conversational response",
  claude:                      "Sends prompts to Claude AI and gets back generated text — great for writing or answering questions",
  google_gemini:               "Uses Google's Gemini AI to generate text, answer questions, or analyze content",
  google_veo:                  "Generates short videos from a text description using Google's Veo AI model",
  text_summarizer:             "Condenses long text into a shorter summary using AI",
  sentiment_analyzer:          "Reads a piece of text and tells you whether the tone is positive, negative, or neutral",
  memory:                      "Saves conversation history so your AI can remember things across multiple steps",
  llm_chain:                   "Runs a sequence of AI prompts one after another, where each step builds on the last",
  azure_openai:                "Uses Microsoft Azure's hosted version of OpenAI's GPT models — enterprise-ready AI",
  hugging_face:                "Runs any AI model from the Hugging Face library — text, classification, translation, and more",
  cohere:                      "Uses Cohere's AI to generate text, classify content, or understand natural language",
  mistral:                     "Sends your message to Mistral AI and gets back a fast, high-quality response — great for chat, summarisation, and code",
  huggingface:                 "Runs open-source AI models from Hugging Face — summarise text, translate between languages, and more",
  ollama:                      "Runs open-source AI models locally on your own server — no cloud keys needed",
  openai_gpt:                  "Sends your prompt to OpenAI's ChatGPT and gets back an AI-written response",
  embeddings:                  "Converts text into numbers that represent its meaning — used for finding similar content",
  vector_store:                "Stores or searches text vectors so you can find content by meaning, not just exact keywords",
  chat_model:                  "A flexible AI chat node that works with OpenAI, Claude, Gemini, or your own local model",
  intent_classification_agent: "Reads a message and figures out what the person is trying to ask or do",
  sentiment_analysis_agent:    "Analyzes the emotional tone of text in detail — joy, anger, sadness, and more",
  confidence_scoring_agent:    "Rates how certain an AI answer is, flagging vague or speculative claims",
  lead_qualification_agent:    "Reviews a sales lead's details and decides whether they're worth following up on",
  lead_scoring_agent:          "Assigns a score to each lead based on their profile — higher score means hotter prospect",
  skill_matching_agent:        "Compares a candidate's skills to a job's requirements and highlights gaps",
  document_qa_agent:           "Answers questions about a document by finding the relevant section and citing it",
  policy_reasoning_agent:      "Reads a policy and applies it to a situation to decide if something is allowed",
  compliance_check_agent:      "Checks your data against a set of rules to find any compliance violations",
  anomaly_detection_agent:     "Spots unusual values in a dataset that don't fit the normal pattern",
  root_cause_analysis_agent:   "Looks at an incident and its logs to figure out what caused the problem",
  conversation_summarizer:     "Takes a back-and-forth conversation and summarizes it into a few key sentences",
  meeting_notes_agent:         "Reads a meeting transcript and extracts agenda, decisions, and action items",
  action_items_extractor:      "Scans text for tasks and to-dos, and lists who should do what by when",
  workflow_planner_agent:      "Takes a goal you describe and suggests a step-by-step workflow plan to achieve it",
  decision_recommendation_agent: "Evaluates options against your criteria and recommends the best one",
  workflow_generator_agent:    "Generates a full workflow from a plain-language description of what you want to automate",
  node_selector_agent:         "Picks the most appropriate node type for a given task based on context",
  prompt_synthesizer:          "Combines several inputs into a single well-formed AI prompt",
  multi_agent_coordinator:     "Runs multiple AI agents in parallel and merges their results",
  agent_role_assigner:         "Gives each AI agent in a team a specific role before they start working",
  agent_voting_consensus:      "Has multiple AI agents vote on an answer and picks the one they agree on most",
  execution_explainer:         "Explains what a workflow step did in plain English after it runs",
  workflow_summary_generator:  "Generates a plain-English summary of an entire workflow's purpose and steps",
  langchain:                   "Runs a LangChain pipeline — a powerful framework for building complex AI chains",

  // ── HTTP & API ────────────────────────────────────────────────────────────
  http_request:       "Calls any web URL and gets data back — your universal connector to the internet",
  graphql:            "Queries a GraphQL API to fetch exactly the data fields you need — nothing more",
  respond_to_webhook: "Sends a response back to the app that triggered your webhook",
  http_post:          "Sends data to a URL — like filling out and submitting a web form programmatically",

  // ── Communication / Output ────────────────────────────────────────────────
  slack_message:              "Sends a message to a Slack channel or person — great for notifications",
  slack_webhook:              "Posts a message to Slack using a simple webhook URL — no app setup needed",
  chat_send:                  "Sends a reply in a chat conversation — works with a chat trigger to create a bot",
  discord:                    "Sends messages or notifications to a Discord server channel",
  discord_webhook:            "Posts a message to Discord using a webhook URL — simplest way to notify a channel",
  microsoft_teams:            "Sends a message or notification to a Microsoft Teams channel",
  telegram:                   "Sends messages to a Telegram chat or bot conversation",
  whatsapp_cloud:             "Sends WhatsApp messages to customers via the official WhatsApp Cloud API",
  mailgun:                    "Sends transactional emails via Mailgun — a reliable email delivery service",
  sendgrid:                   "Sends emails via SendGrid — a popular service for marketing and transactional mail",
  amazon_ses:                 "Sends emails via Amazon Simple Email Service — reliable bulk email delivery",
  twilio:                     "Sends SMS text messages or makes phone calls via Twilio",
  zoom_video:                 "Creates Zoom meetings, retrieves recordings, or manages meeting participants",
  database_write:             "Writes a record to your database — like inserting a new row into a table",
  log_output:                 "Writes a message to your workflow's log for debugging or auditing",
  email_sequence_sender:      "Sends a series of emails in a timed sequence — like a drip campaign",
  auto_followup_sender:       "Automatically sends a follow-up if no reply is received after a set time",
  human_handoff_notification: "Alerts a human agent that a conversation needs their personal attention",
  approval_request_sender:    "Sends an approval request to a designated reviewer and waits for their decision",
  reminder_scheduler:         "Schedules a reminder to be sent at a future date and time",

  // ── Database ──────────────────────────────────────────────────────────────
  database_read: "Reads records from your database — like running a search query",
  postgresql:    "Connects to a PostgreSQL database to run queries or insert data",
  supabase:      "Reads from or writes to your Supabase database — a Firebase alternative built on Postgres",
  mysql:         "Connects to a MySQL database to run queries or manage records",
  mongodb:       "Reads from or writes to a MongoDB document database",
  firebase:      "Reads from or writes to a Google Firebase / Firestore database",
  redis:         "Gets or sets values in a Redis store — extremely fast for caching",
  mssql:         "Connects to a Microsoft SQL Server database",
  sqlite:        "Reads from or writes to a lightweight SQLite database file",
  snowflake:     "Runs queries against your Snowflake cloud data warehouse for large-scale analytics",

  // ── File & Storage ────────────────────────────────────────────────────────
  google_cloud_storage:    "Uploads, downloads, or lists files in a Google Cloud Storage bucket",
  read_binary_file:        "Reads the raw contents of a file — images, PDFs, or any binary data",
  aws_s3:                  "Uploads or downloads files from an Amazon S3 storage bucket",
  ftp:                     "Transfers files to or from a server using the classic FTP protocol",
  sftp:                    "Securely transfers files to or from a server over SSH",
  dropbox:                 "Uploads or downloads files from your Dropbox account",
  onedrive:                "Uploads or downloads files from Microsoft OneDrive or SharePoint",
  box:                     "Uploads, downloads, or manages files in Box cloud storage",
  minio:                   "Uploads or downloads files from a self-hosted MinIO object storage server",
  write_binary_file:       "Writes raw data — like an image or PDF — to a file on disk",
  document_ocr:            "Scans an image or PDF and extracts the text it contains — reads text from pictures",
  resume_parser:           "Reads a resume file and pulls out name, skills, and experience in a structured format",
  invoice_parser:          "Reads an invoice and extracts line items, totals, and vendor details",
  document_classifier:     "Looks at a document and categorizes it (e.g., invoice, contract, or report)",
  file_metadata_extractor: "Reads a file's metadata — its name, size, type, and creation date",

  // ── Utility ───────────────────────────────────────────────────────────────
  date_time:          "Works with dates and times — format them, convert timezones, or calculate differences",
  math:               "Performs calculations on your data — add, subtract, multiply, or apply formulas",
  crypto:             "Encrypts, decrypts, or hashes data for security purposes",
  html_extract:       "Pulls specific content out of an HTML web page — like scraping a field from a site",
  xml:                "Parses XML data into a structured format your workflow can read",
  rss_feed_read:      "Reads the latest posts or articles from an RSS news feed",
  pdf:                "Reads text from a PDF file or creates a new PDF document",
  image_manipulation: "Resizes, crops, converts, or processes image files",

  // ── CRM & Marketing ───────────────────────────────────────────────────────
  hubspot:                "Create, update, or find contacts, deals, and companies in HubSpot CRM",
  salesforce:             "Read or write records in Salesforce — leads, contacts, opportunities, and more",
  microsoft_dynamics:     "Connects to Microsoft Dynamics 365 to manage customer records",
  sap:                    "Connects to SAP enterprise systems to read or write business data",
  tally:                  "Reads financial data or creates accounting entries in Tally ERP",
  zoho_crm:               "Create or update contacts, leads, and deals in Zoho CRM",
  pipedrive:              "Manages deals, contacts, and activities in Pipedrive sales CRM",
  intuit_smes:            "Connects to QuickBooks for accounting and invoicing",
  odoo:                   "Reads or writes data in your Odoo ERP — sales, inventory, or HR",
  freshdesk:              "Create, update, or search customer support tickets in Freshdesk",
  intercom:               "Sends messages or looks up user conversations in Intercom",
  mailchimp:              "Manages email lists and campaigns in Mailchimp — add subscribers or trigger campaigns",
  activecampaign:         "Manages contacts, lists, and automations in ActiveCampaign",
  crm_lead_router:        "Automatically assigns a new lead to the right salesperson based on rules you set",
  crm_ticket_prioritizer: "Looks at a support ticket and decides how urgent it is",
  crm_sla_monitor:        "Watches your support tickets to make sure they're resolved within your promised time",
  crm_duplicate_detector: "Checks if a contact or lead already exists before creating a duplicate",

  // ── DevOps ────────────────────────────────────────────────────────────────
  github:                   "Reads code, creates pull requests, opens issues, or manages your GitHub repositories",
  gitlab:                   "Manages GitLab projects, merge requests, and pipelines",
  bitbucket:                "Reads repositories, pull requests, or code from Bitbucket",
  jenkins:                  "Triggers or monitors builds and deployments in your Jenkins CI/CD server",
  docker:                   "Starts, stops, or inspects Docker containers on your server",
  kubernetes:               "Manages Kubernetes workloads — deploy apps, check pod status, or scale services",
  pagerduty:                "Creates incidents, manages on-call alerts, or checks service health in PagerDuty",
  datadog:                  "Fetches metrics, sends events, or creates monitors in your Datadog dashboard",
  sentry:                   "Reads error reports and release information from Sentry error tracking",
  alert_correlation_engine: "Groups related alerts so you see one big problem instead of dozens of noise events",
  incident_classifier:      "Reads an incident and classifies it by type and severity automatically",
  auto_remediation_planner: "Analyzes an incident and suggests or executes automated fix steps",
  postmortem_generator:     "Writes a structured post-mortem report after an incident resolves",
  vercel:                   "Deploys projects, checks deployment status, or manages your Vercel projects",

  // ── Social Media ──────────────────────────────────────────────────────────
  twitter:   "Posts tweets, searches content, or reads your Twitter/X timeline",
  facebook:  "Posts to Facebook pages, reads comments, or manages your Facebook presence",
  instagram: "Posts to Instagram or reads comments and media from your account",
  linkedin:  "Posts updates to LinkedIn or reads professional network content",
  youtube:   "Uploads videos, reads analytics, or manages your YouTube channel",
  reddit:    "Reads posts and comments from Reddit or submits content to a subreddit",

  // ── Productivity ──────────────────────────────────────────────────────────
  notion:                    "Creates, reads, or updates pages and databases in Notion",
  airtable:                  "Reads rows from an Airtable base or adds new records — like a smarter spreadsheet",
  clickup:                   "Creates or updates tasks, lists, and spaces in ClickUp project management",
  trello:                    "Adds cards, moves items across boards, or manages lists in Trello",
  asana:                     "Creates or updates tasks and projects in Asana",
  jira:                      "Creates or updates issues, sprints, and projects in Jira",
  monday:                    "Reads or updates items and boards in Monday.com project management",
  todoist:                   "Creates or completes tasks in Todoist, your to-do list app",
  knowledge_base_search:     "Searches your internal knowledge base and returns the most relevant articles",
  onboarding_flow_generator: "Generates a personalized onboarding checklist or guide for a new user",
  policy_sync_node:          "Keeps a policy document in sync across multiple systems whenever it changes",
  employee_faq_indexer:      "Indexes employee questions and answers so they're searchable across your HR tools",
  schedulewise:              "Manages complex scheduling, shift planning, or resource availability",

  // ── Authentication ────────────────────────────────────────────────────────
  oauth2:   "Handles the login permission flow so your workflow can act on behalf of a user",
  jwt:      "Creates or validates a security token — a compact way to prove someone's identity",
  ldap:     "Looks up or authenticates users against a corporate Active Directory server",
  okta:     "Manages user authentication and identity through Okta's single sign-on platform",
  auth0:    "Handles user login and authentication using Auth0's identity service",
  keycloak: "Manages user accounts and single sign-on through your self-hosted Keycloak server",

  // ── Payment ───────────────────────────────────────────────────────────────
  stripe:                  "Charges customers, manages subscriptions, or reads payment data from Stripe",
  razorpay:                "Processes payments and manages orders in Razorpay — popular for India-based businesses",
  paypal:                  "Sends or receives money and reads payment details through PayPal",
  quickbooks:              "Reads or creates invoices, payments, and accounting records in QuickBooks",
  expense_categorizer:     "Reads an expense and automatically assigns it to the right budget category",
  payment_reminder_engine: "Sends automatic payment reminders to customers with outstanding balances",
  audit_trail_generator:   "Creates a tamper-evident log entry of an action for compliance and auditing",
  tax_rule_engine:         "Applies the correct tax rates to a transaction based on location and product type",
  fraud_detection_node:    "Analyzes a transaction for suspicious patterns that might indicate fraud",

  // ── E-commerce ────────────────────────────────────────────────────────────
  shopify:     "Reads or manages orders, products, and customers in your Shopify store",
  woocommerce: "Reads or manages orders and products in your WooCommerce WordPress store",
  magento:     "Reads or manages orders, customers, and catalog data in your Magento store",
  bigcommerce: "Reads or manages products, orders, and customers in your BigCommerce store",

  // ── Data Analytics ────────────────────────────────────────────────────────
  google_analytics:          "Fetches website traffic, event, and user data from Google Analytics",
  mixpanel:                  "Reads event and user analytics data from Mixpanel",
  segment:                   "Sends or reads customer event data from Segment's data platform",
  amplitude:                 "Reads product analytics and user behavior data from Amplitude",
  elasticsearch:             "Searches or indexes documents in an Elasticsearch cluster",
  agent_performance_tracker: "Tracks how well your AI agent is performing over time — quality, speed, and errors",
  cost_monitor:              "Calculates and logs the API cost of each AI node execution",
  accuracy_evaluator:        "Compares an AI output to an expected answer and scores how accurate it is",
  feedback_loop_collector:   "Gathers human ratings on AI responses so you can improve your models over time",
  compliance_log_writer:     "Writes a structured compliance audit log entry for a completed workflow step",

  // ── Enterprise / Misc ─────────────────────────────────────────────────────
  zoho:            "Connects to various Zoho apps — Books, Inventory, Desk — to read or write business data",
  xero:            "Reads invoices, contacts, and financial data from your Xero accounting system",
  oracle_database: "Runs queries or procedures against an Oracle Database",
  workday:         "Reads or manages HR, payroll, and financial data in Workday",
  netlify:         "Deploys sites, triggers builds, or manages your Netlify projects",
  pinecone:        "Stores or searches vector embeddings in Pinecone — used for AI-powered semantic search",
  chargebee:       "Manages subscriptions, invoices, and customers in Chargebee billing",
  typeform:        "Reads responses submitted to your Typeform surveys and forms",
  google_forms:    "Reads responses submitted to a Google Form",
  wordpress:       "Creates or updates posts, pages, and media in a WordPress site",
  contentful:      "Reads or creates content entries in your Contentful headless CMS",
  zendesk:         "Creates or updates support tickets and reads customer data in Zendesk",
  calendly:        "Reads scheduled meetings, event types, or user info from Calendly",
};
