// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Check for missing environment variables (only warn, don't block)
if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  console.warn('⚠️ Missing Supabase environment variables!');
  console.warn('VITE_SUPABASE_URL:', SUPABASE_URL ? '✓' : '✗ Missing');
  console.warn('VITE_SUPABASE_PUBLISHABLE_KEY:', SUPABASE_PUBLISHABLE_KEY ? '✓' : '✗ Missing');
  console.warn('Please create a .env file with these variables.');
  console.warn('Copy .env.example to .env and fill in your Supabase credentials.');
  console.warn('The app will continue to run but authentication features may not work.');
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Create client with fallback values to prevent crashes
export const supabase = createClient<Database>(
  SUPABASE_URL || 'https://placeholder.supabase.co',
  SUPABASE_PUBLISHABLE_KEY || 'placeholder-key',
  {
    auth: {
      storage: typeof window !== 'undefined' ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    },
    // ✅ WORLD-CLASS: Graceful WebSocket error handling
    realtime: {
      // Disable automatic reconnection attempts (we'll handle manually)
      params: {
        eventsPerSecond: 10,
      },
      // Handle WebSocket errors gracefully
      heartbeatIntervalMs: 30000,
      reconnectAfterMs: (tries: number) => {
        // Exponential backoff: 1s, 2s, 4s, 8s, max 30s
        return Math.min(1000 * Math.pow(2, tries), 30000);
      },
    },
  }
);

// ✅ WORLD-CLASS: Graceful WebSocket error handling
// Handle WebSocket connection failures without crashing the app
if (typeof window !== 'undefined') {
  // Listen for WebSocket errors and handle them gracefully
  const originalError = console.error;
  const originalWarn = console.warn;
  
  const wsErrorPattern = /WebSocket.*failed|WebSocket.*closed|realtime.*error/i;
  const clockSkewPattern = /Session as retrieved from URL was issued in the future|clock.*skew/i;
  
  // Override console.error to catch WebSocket errors
  const wsErrorHandler = (...args: any[]) => {
    const errorMessage = args.join(' ');
    if (wsErrorPattern.test(errorMessage)) {
      // Log as warning instead of error (non-critical)
      console.warn('[Supabase] WebSocket connection issue (non-critical):', ...args);
      console.warn('[Supabase] The app will continue to work, but real-time updates may be unavailable.');
      return; // Don't log as error
    }
    originalError(...args);
  };
  
  // Override console.warn to suppress clock skew warnings (non-critical)
  const warnHandler = (...args: any[]) => {
    const warnMessage = args.join(' ');
    if (clockSkewPattern.test(warnMessage)) {
      // Suppress clock skew warning - it's non-critical and authentication still works
      // User can fix by syncing their system clock
      if (import.meta.env.DEV) {
        console.debug('[Supabase] Clock skew detected (non-critical). Sync your system clock to remove this warning.');
      }
      return; // Don't log the warning
    }
    originalWarn(...args);
  };
  
  // Only override in development to avoid production issues
  if (import.meta.env.DEV) {
    console.error = wsErrorHandler;
    console.warn = warnHandler;
    // Store original for potential restoration
    (window as any).__originalConsoleError = originalError;
    (window as any).__originalConsoleWarn = originalWarn;
  }
}